...

diff --git a/mod/hub/lib/file b/mod/hub/lib/file
--- a/mod/hub/lib/file
+++ b/mod/hub/lib/file
@@ -104,6 +104,20 @@ ___x_cmd_hub_file_upload(){
     ___x_cmd_hub_client_file_upload "$localfp" "$respath"
 }
 
+___x_cmd_hub_file_upload_dist(){
+    local localfp="${1:?Provide local file}"
+    local respath="${2:?provide respath}"
+
+    x wx pkg "$localfp" ___x_cmd_hub_tmp.wx || {
+        hub:error "Failed to wx pkg: $localfp"
+        return 1
+    }
+
+    respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
+    ___x_cmd_hub_client_file_upload ___x_cmd_hub_tmp.wx "$respath"
+    rm -rf ___x_cmd_hub_tmp.wx
+}
+
 # EndSection
 
 # Section(share): share, private
diff --git a/mod/pkg/lib/download b/mod/pkg/lib/download
--- a/mod/pkg/lib/download
+++ b/mod/pkg/lib/download
@@ -9,6 +9,7 @@ ___x_cmd_pkg_download(){
     local pkg_name="${1:?Provide pkg name}"
     local version="${2:-$(___x_cmd_pkg___default_version "$pkg_name")}"
     local osarch="${3:-${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}}"
+    [ -n "$version" ] || return
 
     local sb_repo
     local sb_app
@@ -19,10 +20,14 @@ ___x_cmd_pkg_download(){
     fi
 
     local url_list
-    local file_suffix
     url_list="$(___x_cmd_pkg___list "$pkg_name" "$version" "$osarch" "url.${___X_CMD_WHICHNET:-_}" )"
-    ___x_cmd_pkg___attr "$pkg_name" "$version" "$osarch" file_suffix
+    [ -n "$url_list" ] || {
+        pkg:error "Not found url."
+        return 1
+    }
 
+    local file_suffix
+    ___x_cmd_pkg___attr "$pkg_name" "$version" "$osarch" file_suffix
     local url
     local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$pkg_name/$version.$file_suffix"
     mkdir -p "$___X_CMD_PKG_DOWNLOAD_PATH/$pkg_name"
@@ -78,7 +83,7 @@ ___x_cmd_pkg_download_file___from_static_build_and_deflate(){
 
     local exe
     case "$osname" in
-        win)    exe=$app.x64.exe        ;;
+        win)    exe=$app.${osname}.${arch}.exe        ;;
         *)      exe=$app.${osname}.${arch}  ;;
     esac
     # Rely
