...

diff --git a/mod/hub/lib/file b/mod/hub/lib/file
--- a/mod/hub/lib/file
+++ b/mod/hub/lib/file
@@ -20,7 +20,7 @@ ___x_cmd_hub_file_normalize_respath(){
 
 # EndSection
 
-# Section: CRUD
+# Section(list): ls、 la
 
 ___x_cmd_hub_file_ls(){
     local respath="${1:-@me/}"
@@ -40,6 +40,28 @@ ___x_cmd_hub_file_ls(){
         { jiget_after_tokenize_unquote($0, ".") }'
 }
 
+___x_cmd_hub_file_la(){
+    local respath="${1:-@me/}"
+    respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
+
+    local res
+    if ! res="$(___x_cmd_hub_client_file_la "$respath")" ; then
+        hub:error "Failed to ls file: $res"
+        return 1
+    fi
+
+    if [ -t 1 ]; then
+        x ui table json PATH=.path IS_PUBLIC=.isPublic \
+            -- 'printf "%s" "$res"'
+    else
+        printf "%s" "$res" #| x ja '(k() ~ "_id|filePath|userId|isPublic") { print v(); }'
+    fi
+}
+
+# EndSection
+
+# Section: rm
+
 ___x_cmd_hub_file_rm(){
     local respath="${1:-@me/}"
     local recursive="${2:-false}"
@@ -52,6 +74,10 @@ ___x_cmd_hub_file_rm(){
     fi
     hub:debug "response: ${res}"
 }
+
+# EndSection
+
+# Section: which upload
 
 ___x_cmd_hub_file_which(){
     local respath="${1:?Provide respath}"
@@ -80,7 +106,7 @@ ___x_cmd_hub_file_upload(){
 
 # EndSection
 
-# Section(share): share, share_list, private
+# Section(share): share, private
 
 ___x_cmd_hub_file_share(){
     local respath="${1:?Please provide path}"
@@ -92,18 +118,6 @@ ___x_cmd_hub_file_share(){
     fi
 
     hub:info "File shared successfully: $res"
-}
-
-___x_cmd_hub_file_share_list(){
-    local respath="${1}"
-    respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
-
-    if ! res="$(___x_cmd_hub_client_file_share_list "${respath}")" ; then
-        hub:error "Failed to share list file: $res"
-        return 1
-    fi
-
-    printf "%s\n" "$res"
 }
 
 ___x_cmd_hub_file_private(){
diff --git a/mod/pkg/lib/download b/mod/pkg/lib/download
--- a/mod/pkg/lib/download
+++ b/mod/pkg/lib/download
@@ -15,7 +15,16 @@ ___x_cmd_pkg_download(){
 
     local url
     local ball="$___X_CMD_PKG_DOWNLOAD_PATH/$pkg_name/$version.$file_suffix"
-    pkg:debug "Download url_list: $url_list ball: $ball"
+    mkdir -p "$___X_CMD_PKG_DOWNLOAD_PATH/$pkg_name"
+
+    local sb_repo
+    local sb_app
+    ___x_cmd_pkg___static_build_attr "$@" "$osarch"
+    if [ -n "$sb_repo" ] && [ -n "$sb_app" ]; then
+        ___x_cmd_pkg_download_file___from_static_build_and_deflate "$sb_repo" "$sb_app"
+        return
+    fi
+    pkg:debug "Download package url_list: $url_list ball: $ball"
 
     local md5
     local sha1
@@ -30,10 +39,10 @@ ___x_cmd_pkg_download(){
         pkg:warn "File corrupted. Download the $ball again."
         x rmrf "$ball"
     fi
-
     while read -r url; do
         # TODO: ___x_cmd_httpget support 302
         # ___x_cmd_httpget "$url" "$ball" || {
+        pkg:info "Download package from $url to $ball"
         curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball" || {
             pkg:warn "Fail to download from $url"
             continue
@@ -48,6 +57,75 @@ $url_list
 A
 
 }
+
+___x_cmd_pkg_download_file___from_static_build_and_deflate(){
+    local IFS='
+    '
+    local repo="${1:?Provide repo name, like p7zip}"
+    local app="${2:-${repo}}"
+    pkg:debug "Download from static-build. repo: $repo app: $app"
+
+    local target="$HOME/.x-cmd/.bin/$app"
+    mkdir -p "$target"
+
+    local arch
+    arch="$(os arch)"
+    local osname
+    osname="$(os name)"
+
+    local exe
+    case "$osname" in
+        win)    exe=$repo.x64.exe        ;;
+        *)      exe=$repo.${osname}.${arch}  ;;
+    esac
+    # Rely
+    if [ ! -f "$target/$exe" ]; then
+
+        pkg:info "Downloading: ${repo}/bin/$exe.7z"
+
+        if ! ___x_cmd_curl_gitx static-build "${repo}" main "bin/$exe.7z" "$target/$exe.7z"; then
+            pkg:warn "Download failure: $repo/main bin/$exe.7z"
+            pkg:warn "File Not Found. Perhaps the platform is NOT supported: $exe"
+            return 1
+        fi
+
+        (
+            cd "$target" && {
+                local size
+
+                size=$(wc -c "$exe.7z")
+                size=${size% *}
+                size=$(printf "%s" $size)   # Notice: Intentionary let it unquoted.
+
+                xrc p7zip
+                if [ "$size" -gt 20 ]; then
+                    p7zd x "$exe.7z" 1>/dev/null 2>/dev/null
+                else
+                    size="$(cat "$exe.7z")"
+                    local i
+                    local suffix
+
+                    # TODO: using job for concurrency.
+                    for i in $(seq "$size"); do
+                        # suffix="$(printf "%03s" "$i")" # Not work in gnu bash
+                        suffix="$(printf "%3s" "$i" | tr " " 0)"
+                        if ! ___x_cmd_curl_gitx static-build "${repo}" main "bin/$exe.7z.$suffix" "$target/$exe.7z.$suffix"; then
+                            pkg:warn "Download failure in $exe.7z.$suffix" >&2
+                            return 1
+                        fi
+                    done
+
+                    pkg:info "Using p7zd to decompress: $target/$exe.7z.001"
+                    cat $target/$exe.7z.0* > $exe.7z
+                    p7zd x "$exe.7z" 1>/dev/null 2>/dev/null
+                fi && chmod +x "$exe" \
+                    && pkg:info "Finish file decompress and chmod."
+            }
+        )
+    fi && return 0
+    return 1
+}
+
 
 ___x_cmd_pkg_download___check_hashsum(){
     local filepath="$1"
diff --git a/mod/pkg/lib/xbin b/mod/pkg/lib/xbin
--- a/mod/pkg/lib/xbin
+++ b/mod/pkg/lib/xbin
@@ -3,38 +3,70 @@
 ___x_cmd_pkg_xbin(){
     case "$1" in
         init)       shift; ___x_cmd_pkg_xbin_init "$@" ;;
+        path)       shift; ___x_cmd_pkg_xbin_path "$@" ;;
         *)          return 1 ;;
     esac
 }
 
-
-
-___x_cmd_pkg_xbin_init(){
-    local bin_mod_name="${1:?Provide bin mod name}"
-    if [ -z "$___X_CMD_PKG_BINMOD_MAP" ]; then
-        ___X_CMD_PKG_BINMOD_MAP="$(cat ...)"
+___x_cmd_pkg_xbin_path(){
+    local pkg_name="${1:?Provide pkg name}"
+    local version="${2:?Provide version}"
+    pkg:debug "xbin: $*"
+    local sb_repo
+    local sb_app
+    local INSTALL_PATH="$___X_CMD_PKG_INSTALL_PATH/$pkg_name"
+    ___x_cmd_pkg___static_build_attr "$@"
+    if [ -n "$sb_repo" ] && [ -n "$sb_app" ]; then
+        INSTALL_PATH="$HOME/.x-cmd/.bin/$sb_app"
     fi
-
-    local package_name="${___X_CMD_PKG_BINMOD_MAP#*:$bin_mod_name:}"
-    if [ "$package_name" = "${___x_CMD_PKG_BINMOD_MAP}" ]; then
-        pkg:error "Not found: ${___x_CMD_PKG_BINMOD_MAP}"
-        return 1
-    fi
-
-    package_name="${package_name%%
-*}"
-
-    local version
-    eval "version=\"\${___X_CMD_PKG_XBIN_DEFAULT_${package_name}\""
-
-    eval "$(___x_cmd_pkg___all_info "$package_name" "${version}" | awk \
-        -v INSTALL_PATH="$___X_CMD_PKG_INSTALL_PATH" \
+    pkg:debug "xbin INSTALL_PATH: $INSTALL_PATH"
+    ___x_cmd_pkg___all_info "$pkg_name" "${version}" | awk \
+        -v INSTALL_PATH="$INSTALL_PATH" \
+        -v BIN_MOD_NAME="${bin_mod_name:-$pkg_name}" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/default.awk" \
         -f "$___X_CMD_ROOT_MOD/awk/lib/jqparse.awk" \
         -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/util.awk" \
         -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg._.awk" \
         -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/pkg.xbin.awk"
-    )"
 }
+___x_cmd_pkg_xbin_init(){
+    local bin_mod_name="${1:?Provide bin mod name}"
+    if [ -z "$___X_CMD_PKG_BINMOD_MAP" ]; then
+        ___X_CMD_PKG_BINMOD_MAP="$(cat $___X_CMD_PKG_RAWPATH/binmod.txt)"
+    fi
+
+    local pkg_name="${___X_CMD_PKG_BINMOD_MAP#*:$bin_mod_name:}"
+    if [ "$pkg_name" = "${___X_CMD_PKG_BINMOD_MAP}" ]; then
+        pkg:error "Not found: ${bin_mod_name}"
+        return 1
+    fi
+
+    pkg_name="${pkg_name%%
+*}"
+
+    local version
+    eval "version=\"\$(___x_cmd_pkg___default_version ${pkg_name})\""
+    pkg:debug "xbin_init. bin_mod_name: $bin_mod_name pkg_name:$pkg_name version: $version"
+
+    # ___x_cmd_pkg_download
+    local bin_path
+    bin_path=$(___x_cmd_pkg_xbin_path "$pkg_name" "$version")
+    pkg:debug "bin_path: $bin_path"
+
+    if ! [ -f "$bin_path" ]; then
+        ___x_cmd_pkg_install "$pkg_name" "$version"
+    fi
+    if ! [ -x "$bin_path" ]; then
+        return 1
+    fi
+    eval "
+        ___x_cmd_$bin_mod_name(){
+            $bin_path \"\$@\"
+        }
+    "
+
+}
+
+
 
 ### EndSection
