...

diff --git a/mod/hub/lib/file b/mod/hub/lib/file
--- a/mod/hub/lib/file
+++ b/mod/hub/lib/file
@@ -1,61 +1,6 @@
 # shellcheck shell=sh disable=SC3043
 
-___x_cmd_hub_file(){
-    param:dsl<<A
-subcommands:
-    ls          "List files in hub"
-    which       "Find file in hub"
-    upload      "Update file to hub"
-    share       "Set file to public"
-    private     "Set file to private"
-A
-    param:run
-    [ -z "${PARAM_SUBCMD}" ] && ___x_cmd_hub_file help && return
-    "___x_cmd_hub_file_$PARAM_SUBCMD" "$@"
-}
-
-___x_cmd_hub_file_ls(){
-    param:void
-    local respath="${1:-@me/}"
-    respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
-
-    local res
-    if ! res="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/ls?token=$(___x_cmd_hub_token)&res=${respath}")" ; then
-        hub:error "Failed to ls file: $res"
-        return 1
-    fi
-    hub:debug "response: ${res}"
-
-    local code
-    code="$(xrc cat awk/lib/default.awk awk/lib/json.awk awk/lib/jiter.awk )"
-    printf "%s" "$res" | awk "$code"'
-        { jiget_after_tokenize_unquote($0, ".") }'
-}
-
-___x_cmd_hub_file_which(){
-    param:dsl<<A
-advise:
-    #1    x hub file ls
-option:
-    #1    "Resourse path"
-A
-    param:run
-    local respath="${1:?Provide respath}"
-    respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
-
-    local cache_path="${___X_CMD_HUB_ENV}/.cache/${respath#/}"
-    local cache_expiration=1
-    mkdir -p "${cache_path%/*}"
-    local error_msg
-    if ___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/cat?token=$(___x_cmd_hub_token)&res=${respath}" "$cache_path" "$cache_expiration" error_msg; then
-        chmod +x "$cache_path"
-        hub:debug "Downloaded ${respath} to ${cache_path}"
-        printf "%s\n" "$cache_path"
-    else
-        hub:error "Failed: $error_msg. Please check the respath."
-        return 1
-    fi
-}
+# Section(util): normalize_respath
 
 # TODO: Should be review. @el
 ___x_cmd_hub_file_normalize_respath(){
@@ -73,8 +18,52 @@ ___x_cmd_hub_file_normalize_respath(){
     esac
 }
 
+# EndSection
+
+___x_cmd_hub_file_ls(){
+    local respath="${1:-@me/}"
+    respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
+
+    local res
+    if ! res="$(___x_cmd_hub_client_file_ls "$respath")" ; then
+        hub:error "Failed to ls file: $res"
+        return 1
+    fi
+    hub:debug "response: ${res}"
+
+    # TODO: Use jo or ja
+    local code
+    code="$(xrc cat awk/lib/default.awk awk/lib/json.awk awk/lib/jiter.awk )"
+    printf "%s" "$res" | awk "$code"'
+        { jiget_after_tokenize_unquote($0, ".") }'
+}
+
+___x_cmd_hub_file_rm(){
+    local respath="${1:-@me/}"
+    local recursive="${2:-false}"
+
+    respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
+    local res
+    if ! res="$(___x_cmd_hub_client_file_rm "$respath" "$recursive")" ; then
+        hub:error "Failed to rm file, res:$res, respath:$respath, recursive:$recursive"
+        return 1
+    fi
+    hub:debug "response: ${res}"
+}
+
+___x_cmd_hub_file_which(){
+    local respath="${1:?Provide respath}"
+    respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
+
+    if ! res=$(___x_cmd_hub_client_file_cat "$respath"); then
+        hub:error "Failed: $res. Please check the respath."
+        return 1
+    fi
+
+    printf "%s\n" "$res"
+}
+
 ___x_cmd_hub_file_upload(){
-    param:void
     local localfp="${1:?Provide local file}"
     local respath="${2:?provide respath}"
 
@@ -84,18 +73,14 @@ ___x_cmd_hub_file_upload(){
     }
 
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
-
-    # TODO: Wait ___x_cmd_httpget support -F "file=@$localfp"
-    curl -F "file=@$localfp" "$___X_CMD_HUB_SERVICE_URL/api/v0/file/upload?token=$(___x_cmd_hub_token)&res=${respath}" 2>/dev/null
-    printf "\n"
+    ___x_cmd_hub_client_file_upload "$localfp" "$respath"
 }
 
 ___x_cmd_hub_file_share(){
-    param:void
     local respath="${1:?Please provide path}"
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
 
-    if ! res="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/share/true?token=$(___x_cmd_hub_token)&res=${respath}")" ; then
+    if ! res="$(___x_cmd_hub_client_file_share "${respath}")" ; then
         hub:error "Failed to share file: $res"
         return 1
     fi
@@ -104,11 +89,10 @@ ___x_cmd_hub_file_share(){
 }
 
 ___x_cmd_hub_file_private(){
-    param:void
     local respath="${1:?Please provide path}"
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
 
-    if ! res="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/share/false?token=$(___x_cmd_hub_token)&res=${respath}")" ; then
+    if ! res="$(___x_cmd_hub_client_file_private "${respath}")" ; then
         hub:error "Failed to private file: $res"
         return 1
     fi
