...

diff --git a/mod/hub/lib/msg b/mod/hub/lib/msg
--- a/mod/hub/lib/msg
+++ b/mod/hub/lib/msg
@@ -9,3 +9,13 @@ ___x_cmd_hub_msg_telegram(){
     fi
     hub:info "response: ${res}"
 }
+
+___x_cmd_hub_msg_wechat(){
+    local msg="${1}"
+    local res
+    if ! res="$(___x_cmd_hub_client_send_wechat_msg "$msg")" ; then
+        hub:error "Failed to send msg, res:$res, msg:$msg"
+        return 1
+    fi
+    hub:info "response: ${res}"
+}
