Squashed 'mod/cd/' changes from 8ca29356..c4814a08
c4814a08 Merge branch 'main' of gitee.com:x-bash/boot
8fcb583b ...
360cb7c4 refactor(main): xrc env/latest
3e18235b ...
469517c2 ...
fb1b14f1 fix xrc to source null
a48f3554 support bash_profile no just in Darwin
2f6b6d97 Merge branch 'main' of gitee.com:x-bash/boot update
7a12d7b2 support bash_profile no just in Darwin
c4e7c0b6 Merge branch 'main' of gitee.com:x-bash/boot
3dee548c ...
cf4a0b41 feat: boot help
1b406854 ...
8a19a96b ...
9bbca215 ...
353a33e1 ...
145186c8 ...
REVERT: 8ca29356 fix(cd): update use ___x_cmd_ui_gridselect
REVERT: 1f5c9d92 update: use ui gridselect
REVERT: d5d98adf ...
REVERT: a8f07abc Merge branch 'main' of https://gitee.com/x-bash/cd into main
REVERT: a5ff7f8e ...
REVERT: d29d785d fix ui select
REVERT: 91321e80 fix: use ui select
REVERT: 33b0b020 fix history record
REVERT: ef9f1d6b ...
REVERT: 7c498ada ...
REVERT: c91dc7e8 add: xrc ui code
REVERT: 90acc9fe feat: use ui select in choose
REVERT: fdbbc55d ___X_CMD_THEME_ENV -> ___X_CMD_PWD
REVERT: 45b95c16 use ldict to set env
REVERT: ac5236b4 ...
REVERT: 4db6abec ...
REVERT: 0c2fa096 ...
REVERT: 5f7745cb ...
REVERT: 740e1aab ...
REVERT: fa195b2d ...
REVERT: 98edbbd2 ...
REVERT: bcd72da3 ...
REVERT: d8cd7e0a ...
REVERT: cc09144c ...
REVERT: 89cc9d9b ...
REVERT: 20f1c1a0 ...
REVERT: 3e717b87 ...
REVERT: ba6ee495 ...
REVERT: b9e71aa5 ...
REVERT: 081f97f2 ...
REVERT: 479b28ef ...
REVERT: 1cfafaaf ...
REVERT: 1f56a15d ...
REVERT: b1057126 ...

git-subtree-dir: mod/cd
git-subtree-split: c4814a080cdc32aab084c1738717f6ffc4004c63

diff --git a/latest b/latest
--- a/latest
+++ b/latest
@@ -1,329 +1,205 @@
-# shellcheck shell=sh disable=SC3043,SC2164 # xrc
+# shellcheck shell=sh disable=SC3043,SC2120 # xrc
 
-# author:       Li Junhao           l@x-cmd.com
-# license:      GPLv3
-
-# Section: main
-
-# jump to a folder contains: jc bin
-# jump to a child folder: jc lib
-# jump to a father folder: jo opening; cd .
-
-# cd backward
-# cd forward = find
-# cd - = history in environment
-# cd <filename> = unmatch to search history or rules
-# cd ,<pattern> = find
-
-# cd /u/l/
-xrc ui/lib/gridselect
-
-___x_cmd_cd_set_domain(){
-    local varname="$1"
-    local value="$2"
-    # varname="$(printf "%s" "$1" | tr "[:lower:]" "[:upper:]")"  # optimized using bash/zsh inline
-
-    # xrc "$varname"
-    # if command "___x_cmd_$varname_cd" 2>/dev/
-
-    ___x_cmd_ldict_unshift  ___X_CMD_PWD "$varname" "$value"
-}
-
-___x_cmd_cd(){
-    local p="$1"
-
-    local nomatch=
-    case "$p" in
-        # alias
-        "")      ___x_cmd_cd_origin              ;;
-        -)
-                # cd to most recent
-                ___x_cmd_cd_origin -
-                ;;
-        *)
-                nomatch=1
-    esac
-
-    [ -z "$nomatch" ] && return 0
-
-    if [ -d "$p" ]; then
-        ___x_cmd_cd_origin "$p"
-        return
-    fi
-
-    # No such directory ... Then magic happens.
-    case "$p" in
-        :)          printf "%s" "${___X_CMD_CD_PWD_LIST#
-}" ;;
-        :*/*)     p=${p#:} ; ___x_cmd_cd_set_domain "${p%%/*}" "${p#*/}" ;;
-        :*)       p=${p#:} ; ___x_cmd_ldict_get ___X_CMD_PWD "${p%%/*}" ;;
-
-        # cd back
-        ...)     ___x_cmd_cd_origin ../..        ;;
-        ....)    ___x_cmd_cd_origin ../../../    ;;
-
-        .../*)    ___x_cmd_cd_back "${p#.../}"     ;;
-
-        # cd-forward
-        ./*)     ___x_cmd_cd_choose "$(find . -name "*${p#./}*" -type d 2>/dev/null)" ;;
-
-        # cd: about history
-        --list-history)
-            ___X_CMD_CD_HISTORY="$(printf "%s" "$___X_CMD_CD_HISTORY" | ___x_cmd_cd_util_uniq_head 200)"
-            printf "%s\n" "$___X_CMD_CD_HISTORY"
-            ;;
-        --clear-history)
-            # very less used
-            ___X_CMD_CD_HISTORY=
-            ;;
-
-        # cd: history
-        --)
-            ___X_CMD_CD_HISTORY="$(printf "%s" "$___X_CMD_CD_HISTORY" | ___x_cmd_cd_util_uniq_head 200)"
-            local target="${___X_CMD_CD_HISTORY#*
-*
-}"
-            [ "$target" = "$___X_CMD_CD_HISTORY" ] && printf "%s\n" "cd: no such directory: " >&2 && return
-            target="${target%%
-*}"
-            ___x_cmd_cd_origin "$target"
-            ;;
-        -*) # using the first match
-            ___X_CMD_CD_HISTORY="$(printf "%s" "$___X_CMD_CD_HISTORY" | ___x_cmd_cd_util_uniq_head 200)"
-            ___x_cmd_cd_origin "$(awk "FNR <= 1" <<A
-$(printf "%s" "$___X_CMD_CD_HISTORY" | grep "${p#-}")
-A
-)"
-            ;;
-
-        # cd with find
-        ,*)
-            p=${p#,}
-            local ans
-            ans="$(find "$HOME" \
-                -path "$HOME/Library" -prune \
-                -o -path "$HOME/.*" -prune \
-                -o -path "*/.git" -prune \
-                -o -name "*$p*" -type d -print 2>/dev/null)"
-            if [ "$ans" = "" ]; then
-                printf "%s\n" "not found: " 2>/dev/null
-                return 1
-            fi
-            ___x_cmd_cd_choose "$ans"
-            ;;
-
-        /*)    ___x_cmd_cd_choose "$(___x_cmd_cd_iter / "${p#/}")" ;;
-        */*)   ___x_cmd_cd_choose "$(___x_cmd_cd_iter . "${p}")"   ;;
-
-        *)
-            ___X_CMD_CD_HISTORY="$(printf "%s" "$___X_CMD_CD_HISTORY" | ___x_cmd_cd_util_uniq_head 200)"
-            ___x_cmd_cd_choose "$(printf "%s" "$___X_CMD_CD_HISTORY" | grep "${p#-}")"
-            ;;
-    esac
-}
-# EndSection
-
-# Section: choose
-
-# TODO: better ui
-___x_cmd_cd_choose_data(){
-    printf "%s\n" "Select an option to change directory:"
-    printf "%s\n" "$*"
-    printf "%s\n" "---
----"
-}
-
-___x_cmd_cd_choose(){
-
-    # If no interactive, return false
-    if [ "$1" = "" ] || [ "${-#*i}${___X_CMD_FS_DEBUG}" = "$-" ]; then
-        printf "%s\n" "cd: no such directory: $p " >&2
+# Section: bootrc consider external module.
+___x_cmd_boot(){
+    local subcmd="$1"; [ $# -gt 0 ] && shift
+    if ! mkdir -p "$HOME/.x-cmd/.boot"; then
+        printf "boot abort for mkdir fails: %s\n" "$HOME/.x-cmd/.boot" >/dev/stderr
         return 1
     fi
-    local ___X_CMD_UI_GRIDSELECT_CURRENT_ITEM
-    local ___X_CMD_UI_GRIDSELECT_FINAL_COMMAND
-    ___x_cmd_ui_gridselect num ___x_cmd_cd_choose_data "$@"
-    [ "$___X_CMD_UI_GRIDSELECT_FINAL_COMMAND" = "q" ] && return 0
-    ___x_cmd_cd_origin "$___X_CMD_UI_GRIDSELECT_CURRENT_ITEM"
-}
-# EndSection
 
-# Section: cd back
-___x_cmd_cd_back(){
-    local p
-    p="$(cd .. && pwd)"
-    local pat="$1"
-    local target
-    if target="$(printf "" | awk -v p="$p" -v target="$pat" '
-BEGIN {
-    return_code = 1
-    arrl = split(p, arr, "/")
-    for (i=arrl; i>=1; i--) {
-        if (match(arr[i], target)) {
-            res = ""
-            for (j=1; j<=i; ++j) {
-                if (arr[j] == "") continue
-                res = res "/" arr[j]
-            }
-            print res
-            return_code = 0
-            exit(0)
-        }
-    }
-    exit(1)
-}
+    case "$subcmd" in
+        setup)
+            cat > "$HOME/.x-cmd/.boot/boot" <<A
+# Do NOT modify manually for this file is auto generated by command: x boot setup
 
-END {
-    exit(return_code)
-}
-'
-)"; then
-        ___x_cmd_cd_origin "$target"
-    fi
-}
-# EndSection
-
-# Section: iter and other...
-___x_cmd_cd_iter()(
-    local root="$1"
-    local iter_path="$2"
-
-    ___x_cmd_cd_origin "$root" 2>/dev/null
-
-    local cur="${iter_path%%/*}"
-
-    if [ "$cur" = "$iter_path" ]; then
-        # this is final
-        if [ "${cur%*}" = "$cur" ]; then
-            cur="$cur*"
-        fi
-        eval "ls -d $cur/" 2>/dev/null | awk -v root="$root" '{ printf("%s%s\n", root, $0) }'
-    else
-        local elem
-        iter_path="${iter_path#*/}"
-        if [ "${cur%*}" = "$cur" ]; then
-            cur="$cur*"
-        fi
-        eval "ls -d $cur/" 2>/dev/null | while read -r elem; do
-            ___x_cmd_cd_iter "${root%/}/$elem" "$iter_path"
-        done
-    fi
-)
-
-mkdir -p "$___X_CMD_ROOT/.tmp/cd"
-
-___x_cmd_cd_util_uniq_head(){
-    awk -v head="${1:-100}" '
-{
-    if (count > head) { exit(exit_code); }
-    if (uniq_map[$0] == "") {
-        uniq_map[$0] = 1
-        print $0
-        count = count + 1
-    } else {
-        exit_code = 1
-    }
-}
-END {
-    exit(exit_code)
-}
-'
-}
-
-___x_cmd_cd_load_history(){
-    if [ -f "$___X_CMD_ROOT/.tmp/cd/history" ]; then
-    ___X_CMD_CD_HISTORY=$(awk '
-BEGIN {
-    res_len = 0
-    len = 0
-}
-{
-    data[ len ] = $0
-    len = len + 1
-}
-END {
-    for (j=0; j<len && res_len<200; j++) {
-        if (map[ data[ len-j-1 ] ] != "") {
-            continue
-        }
-        map[ data[ len-j-1 ] ] = 1
-        res_len = res_len + 1
-        print data[ len-j-1 ]
-    }
-}' <"$___X_CMD_ROOT/.tmp/cd/history")
+if command -v xrc >/dev/null 2>&1; then
+    return 0
+elif [ -f "$HOME/.x-cmd/xrc/latest" ]; then
+    . "$HOME/.x-cmd/xrc/latest"
+else
+    printf "%s\n  %s" 'xrc/latest not found. You can reinstall using:' 'eval "\$(curl https://get.x-cmd.com)"'
+    return 1
 fi
 
-    printf "%s" "$___X_CMD_CD_HISTORY" | awk '
-BEGIN {
-    res_len=0
-    len=0
-}
-{
-    data[ len ] = $0
-    len = len + 1
-}
-END {
-    for (j=0; j<len ; j++) {
-        print data[ len-j-1 ]
-    }
-}
-    ' > "$___X_CMD_ROOT/.tmp/cd/history"
-}
-___x_cmd_cd_load_history
-# EndSection
-
-# Section: cd origin
-
-# 1. Explictly Inject to cd: x cd :inject
-# alias cd=___x_cmd_cd_origin
-___x_cmd_cd_origin(){
-    # `command cd` will not execute buildin command `cd` in zsh, refer: https://linux.die.net/man/1/zshbuiltins
-    if [ -n "$ZSH_VERSION" ]; then
-        builtin cd "$@"
-    else
-        command cd "$@"
-    fi
-
-    [ "${-#*i}${___X_CMD_FS_DEBUG}" = "$-" ] && return
-
-#     ___X_CMD_CD_HISTORY="$(pwd | tee -a "$___X_CMD_ROOT/.tmp/cd/history")${___X_CMD_CD_HISTORY:+
-# }${___X_CMD_CD_HISTORY}"
-    printf "%s\n" "$PWD" >>"$___X_CMD_ROOT/.tmp/cd/history"
-    ___X_CMD_CD_HISTORY="$PWD${___X_CMD_CD_HISTORY:+
-}${___X_CMD_CD_HISTORY}"
-
-}
-
-# EndSection
-
-# Section: advise
-___x_cmd_cd_advise_candidates(){
-    local can="$1"
-    case "$can" in
-        "")
-            cat <<A
-=
--
-...
-../
-$(ls)
+xrc env/latest
+[ -f "$HOME/.x-cmd/.boot/mod" ] && x boot mod load
+[ -f "$HOME/.x-cmd/.boot/rc" ] && . "$HOME/.x-cmd/.boot/rc"
+:
 A
-        ;;
-        ./*)
-            ;;
-        ../*)
-            ;;
-        -)  ;;
-        --)
-            ;;
-        -*)
-            ;;
-        /*) ;;
-        */*) ;;
+            (
+                if [ "$BASH_VERSION" ]; then
+                    # The bash login mode will not source the .bashrc file but the .bash_profile file.
+                    # Ref: https://blog.flowblok.id.au/2013-02/shell-startup-scripts.html
+                    CAN="$HOME/.bashrc $HOME/.bash_profile"
+                    # [ "$(uname)" = "Darwin" ]  &&   CAN="$CAN $HOME/.bash_profile"
+                elif [ "$ZSH_VERSION" ]; then       CAN="$HOME/.zshrc"
+                elif [ "$KSH_VERSION" ]; then       CAN="$HOME/.kshrc"
+                else                                CAN="$HOME/.shinit"
+                fi
 
+                X_STR="[ -f \"\$HOME/.x-cmd/.boot/boot\" ] && . \"\$HOME/.x-cmd/.boot/boot\""
+                IFS=" "
+                for i in $CAN; do
+                    if grep -F "$X_STR" "$i" >/dev/null; then
+                        printf "%s\n" "[x-cmd]: Already installed in $i" >&2
+                    else
+                        printf "\n%s\n" "$X_STR" >> "$i"
+                        printf "%s\n" "[x-cmd]: Successfully Installed in: $i" >&2
+                    fi
+                done
+            )
+            ;;
+        rc)
+            subcmd="$1"; shift
+            local ___X_CMD_ROOT_RC="$HOME/.x-cmd/.boot/rc"
+            local IFS=' '
+            case "$subcmd" in
+                add|+)
+                        local keyword="${1:?Provide keyword}"; shift
+                        local text
+                        [ -f "$___X_CMD_ROOT_RC" ] && text="$(cat "$___X_CMD_ROOT_RC")"
 
+                        printf "%s" "$text" | awk -v code="$*" -v keyword="$keyword" '
+                            BEGIN {
+                                COMMENT = "# auto generated: " keyword
+                                COMMENT_LEN = length(COMMENT)
+                            }
+                            {
+                                len = length($0)
+                                s = index($0, COMMENT)
+
+                                if ( (s <= 0) || (s+COMMENT_LEN-1)!=len ) {
+                                    print $0
+                                } else {
+                                    print code " " COMMENT
+                                    done = 1
+                                }
+                            }
+                            END {
+                                if (done != 1) {
+                                    print code " " COMMENT
+                                }
+                            }
+                            ' >"$___X_CMD_ROOT_RC"
+                        ;;
+                del|-)
+                        local keyword="${1:?Provide keyword}"; shift
+                        local text
+                        [ -f "$___X_CMD_ROOT_RC" ] && text="$(cat "$___X_CMD_ROOT_RC")"
+
+                        printf "%s" "$text" | awk -v code="$*" -v keyword="$keyword" '
+                            BEGIN {
+                                COMMENT = "# auto generated: " keyword
+                                COMMENT_LEN = length(COMMENT)
+                            }
+                            {
+                                len = length($0)
+                                s = index($0, COMMENT)
+
+                                if ( (s <= 0) || (s+COMMENT_LEN-1)!=len ) {
+                                    print $0
+                                } else {
+                                    done = 1
+                                }
+                            }
+                            END {
+                                if (done == 1) {
+                                    exit(0)
+                                } else {
+                                    exit(1)
+                                }
+                            }
+                            ' >"$___X_CMD_ROOT_RC"
+                        ;;
+                ls|*)   cat "$___X_CMD_ROOT_RC" ;;
+            esac
+            ;;
+        mod)
+                subcmd="$1"; shift
+                local ___X_CMD_BOOT_MOD="$___X_CMD_ROOT/.boot/mod"
+                case "$subcmd" in
+                    path)       printf "%s" "$___X_CMD_BOOT_MOD" ;;
+                    add|+)
+
+                                (
+                                    s="$(cat "$___X_CMD_BOOT_MOD" 2>/dev/null)"
+                                    {
+                                        if [ "$s" = "" ]; then
+                                            s="$(printf "%s\n" "# Do NOT modifiy this file manually for it is auto generated.")"
+                                            printf "%s\n" "# Do NOT modifiy this file manually for it is auto generated."
+                                        fi
+                                        # Intentionally, because "$()" will trim the last \n
+                                        s="$s
+"
+                                        for mod in "$@"; do
+                                            if [ "$s" = "${s#*
+$mod
+}" ]; then
+                                                printf "%s\n" "$mod"
+                                                printf "Module will be automatically imported during boot: %s\n" "$mod" >&2
+                                            else
+                                                printf "Module ALREADY automatically imported during boot: %s\n" "$mod" >&2
+                                            fi
+                                        done
+                                    } >> "$___X_CMD_BOOT_MOD"
+                                ) ;;
+                    del|-)
+                                (
+                                    s="$(cat "$___X_CMD_BOOT_MOD" 2>/dev/null)"
+                                    s="$s
+"
+                                    d="$s"
+                                    for mod in "$@"; do
+                                        d2="${d#*
+$mod
+}"
+                                        [ "$d2" = "$d" ] && continue
+                                        d1="${d%
+$mod
+*}"
+                                        d="$d1
+$d2"
+                                    done
+
+                                    if [ "$d" != "$s" ]; then
+                                        printf "%s" "$d" > "$___X_CMD_BOOT_MOD"
+                                    fi
+                                )
+                                ;;
+                    load)
+                                local mod_list
+                                mod_list="$(awk '$1~/[A-Za-z0-9_\-]+/{ print $1;  }'<"$___X_CMD_BOOT_MOD" | tr '\n' ' ')"
+                                [ -n "${mod_list}" ] && eval xrc "$mod_list"
+                                ;;
+                    ask)        (
+                                    for i in "$@"; do
+                                        if ! ( x boot mod ls | grep "$i" >/dev/null); then
+                                            xrc ui
+                                            local answer
+                                            ui 'select' answer "Not found in boot. Automatically import this module during boot: $*" "YES" "NO"
+                                            if [ "$answer" = 1 ]; then
+                                                x boot mod add "$i"
+                                            fi
+                                        fi
+                                    done
+                                )
+                                ;;
+                    which)      printf "%s\n" "$___X_CMD_BOOT_MOD" ;;
+                    cat)        cat "$___X_CMD_BOOT_MOD" 2>/dev/null ;;
+                    ls|*)
+                                if [ -e "$___X_CMD_BOOT_MOD" ]; then
+                                    awk '$1~/[A-Za-z0-9_\-]+/{ print $1;  }'<"$___X_CMD_BOOT_MOD"
+                                else
+                                    touch "$___X_CMD_BOOT_MOD"
+                                    return 0
+                                fi
+                                ;;
+                esac
+                ;;
+        *)  xrc advise/lib/advise_get
+            ___x_cmd_advise_get_help "$(xrc which x-cmd/_v0/x.json)" boot '' ;;
     esac
 }
-# EndSection
 
-xrc setmain ___x_cmd_cd
+xrc setmain ___x_cmd_boot
