Squashed 'mod/x-cmd/' changes from b9beede..5cb8bff
5cb8bff fix printf file url
c1fc686 ...
cf60488 Merge branch 'main' of gitee.com:x-bash/x-cmd
4bff81d ...

git-subtree-dir: mod/x-cmd
git-subtree-split: 5cb8bff43cd023d0dc57c29c672e30fa1889d731

diff --git a/latest b/latest
--- a/latest
+++ b/latest
@@ -860,21 +860,22 @@ ___x_cmd_main_otherwise(){
 
     # static build
     # update the static-build files
-    local p
+    local ___X_CMD_WHICH_ONE_RESULT
+    local ___X_CMD_WHICH_ONE_RESOURCE_TYPE
     if ___x_cmd_which_one "$subcmd"; then
-        p="$___X_CMD_WHICH_ONE_RESULT"
+        local p="$___X_CMD_WHICH_ONE_RESULT"
         case "$___X_CMD_WHICH_ONE_RESOURCE_TYPE" in
-            workspace)      ___x_cmd_exe_workspace "$p" "$@" ;;
-            local)          ___x_cmd_run_by_file "$p" "$@" ;;
-            hub)            ___x_cmd_run_by_file "$p" "$@" ;;
-            official)       ___x_cmd_run_by_file "$p" "$@" ;;
+            workspace)      ___x_cmd_exe_workspace  "$p" "$@" ;;
+            local)          ___x_cmd_run_by_file    "$p" "$@" ;;
+            hub)            ___x_cmd_run_by_file    "$p" "$@" ;;
+            official)       ___x_cmd_run_by_file    "$p" "$@" ;;
         esac
-        return
+        ___xrc_log debug "$p"
+        return 0
     else
         printf "%s" "Error" >&2
         return 1
     fi
-    printf "%s" "$p"
 }
 
 ___x_cmd_ws(){
@@ -922,6 +923,16 @@ ___x_cmd_ws_(){
 }
 
 ___x_cmd_alias_init ___x_cmd
+
+___x_cmd_which_panic(){
+    local ___X_CMD_WHICH_ONE_RESULT
+    if ! ___x_cmd_which_one "$p"; then
+        printf "%s\n" "Fail to find path for $p" >&2
+        return 1
+    else
+        printf "%s\n" "$___X_CMD_WHICH_ONE_RESULT"
+    fi
+}
 
 ___x_cmd_main(){
     local IFS=" "
@@ -1018,12 +1029,7 @@ ___x_cmd_main(){
         search_path)                            ___x_cmd_search_path "$@"       ;;
         which|w)                                local p
                                                 for p in "$@"; do
-                                                    if ! ___x_cmd_which_one "$p"; then
-                                                        printf "%s\n" "Fail to find path for $p" >&2
-                                                        return
-                                                    else
-                                                        printf "%s\n" "$___X_CMD_WHICH_ONE_RESULT"
-                                                    fi
+                                                    ___x_cmd_which_panic || return 1
                                                 done
                                                 ;;
         _x_cmd_advise_json)                     ___x_cmd_x_cmd_advise_json "$@" ;;
