Squashed 'mod/env/' changes from 659fdae5..d70b6e27
d70b6e27 feat(env): update lsenv return value
14a17e6a Merge branch 'main' of https://gitee.com/x-bash/env into main
3e001299 fix(.zshenv): lsenv.awk
fc8472d7 !9 env | Debug the code after calling the review | 2022-03-22 Merge pull request !9 from Zero/issue_I4YUOU_zjq
5b26c0ca fix(env): redirect exception output to stderr
d679bcba refactor(env): use the find command to determine whether the installation package exists
ba6b0255 fix(env): debug the review code
d2143c9d !8 修复了maven unpack Merge pull request !8 from mnnna/issue_I4XW5Y_gradle_lth
db853a22 fix function list of maven
105b98b6 fix maven
dcbce067 fix maven
dd77edbb modified maven

git-subtree-dir: mod/env
git-subtree-split: d70b6e279a50f234744360ed74633bf58c0f5e67

diff --git a/latest b/latest
--- a/latest
+++ b/latest
@@ -15,7 +15,7 @@ ___x_cmd_env_util_add_path(){
     local tmp="$PATH:"
 
     if [ ! -d "$dir" ] ; then
-        env_log error "Failed to add path: $dir, not a directory"
+        printf "%s\n" "Failed to add path: $dir, not a directory" >&2
         return 1
     fi
 
