...

diff --git a/mod/env/lib/config b/mod/env/lib/config
--- a/mod/env/lib/config
+++ b/mod/env/lib/config
@@ -3,55 +3,53 @@
 ___X_CMD_ENV_VERSION_CONFIG_PATH="$___X_CMD_ROOT/.boot/env"
 
 ___x_cmd_env_config_load(){
-    if ! ___X_CMD_ENV_VERSION_CONFIG="$(cat "$___X_CMD_ENV_VERSION_CONFIG_PATH" 2>/dev/null)"; then
-        x mkdirp "${___X_CMD_ENV_VERSION_CONFIG_PATH%/*}"
-        touch "$___X_CMD_ENV_VERSION_CONFIG_PATH"
+    local configstr
+    if ! configstr="$(cat "$___X_CMD_ENV_VERSION_CONFIG_PATH" 2>/dev/null)"; then
+        x touch "$___X_CMD_ENV_VERSION_CONFIG_PATH"
         env:debug "Config file not found then create $___X_CMD_ENV_VERSION_CONFIG_PATH file"
     fi
 
     local line
     while read -r line; do
+        [ -n "$line" ] || continue
         ___x_cmd_env_try "$line"
     done <<A
-$(___x_cmd_ldict_print ___X_CMD_ENV_VERSION_CONFIG)
+$configstr
 A
 
 }
 
 ___x_cmd_env_config_save(){
-    local tgt="${1:-"$___X_CMD_ENV_VERSION_CONFIG_PATH"}"
+    ___x_cmd_env_config___write "$___X_CMD_ENV_VERSION_CONFIG"
+}
 
-    if ! x mkdirp "${tgt%/*}"; then
-        env:error "Couldn't create folder: ${tgt%/*}"
+___x_cmd_env_config___write(){
+    local configstr="${1:?Provide config string}"
+    local tgt="${2:-"$___X_CMD_ENV_VERSION_CONFIG_PATH"}"
+
+    if ! x touch "$tgt"; then
+        env:error "Couldn't create file: ${tgt}"
         return 1
     fi
 
-    ___x_cmd_ldict_print ___X_CMD_ENV___CONFIGSTR_SET_ > "$tgt"
-}
-
-# set
-___x_cmd_env_config_set(){
-    ___x_cmd_env___configstr_set_ "$___X_CMD_ENV_VERSION_CONFIG_PATH" "$@"
-    ___x_cmd_env_config_save "$___X_CMD_ENV_VERSION_CONFIG_PATH"
+    printf "%s\n" "$1" > "$tgt"
 }
 
 ___x_cmd_env___configstr_set_(){
-    local file="${1:-Provide file}"
-    ___x_cmd_ldict_load ___X_CMD_ENV___CONFIGSTR_SET_ "$file"
-    shift
-    local pkg_name_version
+    ___X_CMD_ENV___CONFIGSTR_SET_="${1:-""}";   shift
+
     local name
     local version
-    for pkg_name_version in "$@"; do
+
+    local IFS=" "; local pkg_name_version; for pkg_name_version in "$@"; do
         name="${pkg_name_version%=*}"
         version="${pkg_name_version#*=}"
 
-        if [ -n "$version" ]; then
-            ___x_cmd_ldict_put ___X_CMD_ENV___CONFIGSTR_SET_ "$name" "$(___x_cmd_env_get_version "$pkg_name_version")"
+        if [ -z "$version" ] || [ "$version" = "$pkg_name_version" ]; then
+            ___x_cmd_env___sdict rm     ___X_CMD_ENV___CONFIGSTR_SET_ "$name"
         else
-            ___x_cmd_ldict_rm ___X_CMD_ENV___CONFIGSTR_SET_ "$name"
+            ___x_cmd_env___sdict put    ___X_CMD_ENV___CONFIGSTR_SET_ "$name" "$version"
         fi
     done
-
 }
 
diff --git a/mod/pkg/lib/main b/mod/pkg/lib/main
--- a/mod/pkg/lib/main
+++ b/mod/pkg/lib/main
@@ -1,3 +1,4 @@
+# shellcheck    shell=sh            disable=SC3043      # xrc
 
 
 # # Rely on ll or ls
@@ -24,21 +25,21 @@
 
 ___x_cmd_pkg___which_p7zip()(
     ___x_cmd_mkdirp "$___X_CMD_PKG_RAWPATH"
-
     local p7zip="$___X_CMD_ROOT_TMP/pkg/all.7z"
     if ! ___x_cmd_httpget_gitx x-cmd pkg main "dist/all.7z" "$p7zip" "${1:-3600}"; then # 1-day
         if [ ! -f "$p7zip" ]; then
-            x:error "Unaviable all.7z. Unable to fetch all.7z."
+            pkg:error "Unaviable all.7z. Unable to fetch all.7z."
             return 1
         fi
     fi
 
     if [ "$___X_CMD_HTTPGET_AGE" = 0 ]; then
-        pkg:info "Deflate the all.7z"
+        xrc p7zip
         x rmrf "$___X_CMD_PKG_RAWPATH"
         ___x_cmd_mkdirp "$___X_CMD_PKG_RAWPATH"
-        if ! cd "${p7zip%/*}" && cp all.7z raw/all.7z && cd raw && x uz all.7z 1>/dev/null && x rmrf all.7z; then
-            x:error "Deflation failure."
+        pkg:debug "Deflate the all.7z"
+        if ! ( cd "${p7zip%/*}" && cp all.7z raw/all.7z && cd raw && p7zd x all.7z 1>/dev/null && x rmrf all.7z ); then
+            pkg:error "Deflation failure."
             x rmrf "$p7zip"
         fi
     fi
@@ -47,4 +48,5 @@ ___x_cmd_pkg___which_p7zip()(
 
 ___x_cmd_pkg_update(){
     ___x_cmd_pkg___which_p7zip - || return # Force Update
+    pkg:info "Update the all.7z"
 }
