...

diff --git a/mod/env/lib/exec b/mod/env/lib/exec
--- a/mod/env/lib/exec
+++ b/mod/env/lib/exec
@@ -21,45 +21,54 @@ ___x_cmd___env_exec_set(){
     while [ $# -gt 0 ]; do
         case "$1" in
             --)     break ;;
-            -*)     ___x_cmd_env untry "${1#-}" ;;
-            *=)     ___x_cmd_env untry "${1%=}" ;;
+            -*)     ___x_cmd_env untry "${1#*-}" ;;
+            *=)     ___x_cmd_env untry "${1%=*}" ;;
             *=-)
                     local ___X_CMD_ENV_PREV_
-                    ___x_cmd_env_prev_ "${1%=-}"
-                    ___x_cmd_env try "${1%=-}=${___X_CMD_ENV_PREV_}" ;;
+                    ___x_cmd_env_prev_ "${1%=-*}"
+                    [ -z "$___X_CMD_ENV_PREV_" ] || ___x_cmd_env try "${1%=-*}=${___X_CMD_ENV_PREV_}" ;;
             *=*)    ___x_cmd_env try "$1" ;;
         esac
+        shift
     done
 }
 
 ___x_cmd___env_exec_set_and_run_and_unset(){
     local ___X_CMD_ENV_RECOVER_CODE=
+    local ___X_CMD_ENV_RECOVER_DEACTIVATE_CODE=
     while [ $# -gt 0 ]; do
         case "$1" in
             --)
                 shift; "$@"; break ;;
             -*)
-                ___x_cmd___env_exec_set_and_run_and_unset_recover "${1#-}"
-                ___x_cmd_pkg deactivate "${1#-}"
+                ___x_cmd___env_exec_set_and_run_and _unset_recover "${1#*-}"
+                ___x_cmd_pkg deactivate "${1#*-}"
                 ;;
             *=)
-                ___x_cmd___env_exec_set_and_run_and_unset_recover "${1%=}"
-                ___x_cmd_pkg deactivate "${1%=}"
+                ___x_cmd___env_exec_set_and_run_and_unset_recover "${1%=*}"
+                ___x_cmd_pkg deactivate "${1%=*}"
                 ;;
             *=-)
-                ___x_cmd___env_exec_set_and_run_and_unset_recover "${1%=}"
+                ___x_cmd___env_exec_set_and_run_and_unset_recover "${1%=*}"
                 local ___X_CMD_ENV_PREV_
                 ___x_cmd_env prev_ "$pkg"
-                ___x_cmd_pkg activate "${1%=-}=$___X_CMD_ENV_PREV_"
+                [ -z "$___X_CMD_ENV_PREV_" ] || ___x_cmd_pkg activate "${1%=-*} $___X_CMD_ENV_PREV_"
                 ;;
             *=*)
-                ___x_cmd___env_exec_set_and_run_and_unset_recover "${1%=}"
-                ___x_cmd_pkg activate "$1"
+                ___x_cmd___env_exec_set_and_run_and_unset_recover "${1%=*}"
+                if ! ___x_cmd_pkg install "${1%=*}" "${1#*=}"; then
+                    env:error "Cannot install package: ${1%=*} ${1#*=}"
+                    return 1
+                fi
+                ___x_cmd_pkg activate "${1%=*}" "${1#*=}"
+                ___X_CMD_ENV_RECOVER_DEACTIVATE_CODE="$___X_CMD_ENV_RECOVER_DEACTIVATE_CODE
+___x_cmd_pkg deactivate ${1%=*}"
                 ;;
         esac
-        [ -z "$___X_CMD_ENV_RECOVER_CODE" ] || eval "$___X_CMD_ENV_RECOVER_CODE"
-
+        shift
     done
+    [ -z "$___X_CMD_ENV_RECOVER_DEACTIVATE_CODE" ] || eval "$___X_CMD_ENV_RECOVER_DEACTIVATE_CODE"
+    [ -z "$___X_CMD_ENV_RECOVER_CODE" ] || eval "$___X_CMD_ENV_RECOVER_CODE"
 }
 
 ___x_cmd___env_exec_set_and_run_and_unset_recover(){
@@ -67,10 +76,9 @@ ___x_cmd___env_exec_set_and_run_and_unset_recover(){
     local pkg="$1"
     ___x_cmd_env current_ "$pkg"
     if [ -n "$___X_CMD_ENV_CURRENT_" ]; then
-        ___x_cmd_pkg deactivate "$pkg=$___X_CMD_ENV_CURRENT_"
+        ___x_cmd_pkg deactivate "$pkg"
         ___X_CMD_ENV_RECOVER_CODE="$___X_CMD_ENV_RECOVER_CODE
 ___x_cmd_pkg deactivate $pkg
-___x_cmd_pkg activate $pkg=$___X_CMD_ENV_CURRENT_"
+___x_cmd_pkg activate $pkg $___X_CMD_ENV_CURRENT_"
     fi
 }
-
diff --git a/mod/env/lib/main b/mod/env/lib/main
--- a/mod/env/lib/main
+++ b/mod/env/lib/main
@@ -5,7 +5,7 @@ ___x_cmd_env_get_version(){
     if [ "$version" != "$pkg_name" ]; then
         printf "%s\n" "$version"
     else
-        x pkg default_version "$pkg_name"
+        ___x_cmd_pkg default_version "$pkg_name"
     fi
 }
 
@@ -14,7 +14,7 @@ ___x_cmd___env_pasre__pkg__version(){
         *=-)
             ___X_CMD___ENV_PARSE_PKG="${1%=-}"
             ___x_cmd_env_prev_ "${1%=-}"
-            ___X_CMD___ENV_PARSE_VERSION="$___X_CMD_ENV_PREV_"
+            ___X_CMD___ENV_PARSE_VERSION="$___X_CMD_ENV_PREV"
             ;;
         *=*)
             ___X_CMD___ENV_PARSE_PKG="${1%=*}"
@@ -22,7 +22,7 @@ ___x_cmd___env_pasre__pkg__version(){
             ;;
         *)
             ___X_CMD___ENV_PARSE_PKG="${1}"
-            ___X_CMD___ENV_PARSE_VERSION="$(x pkg default_version "$1")"
+            ___X_CMD___ENV_PARSE_VERSION="$(___x_cmd_pkg default_version "$1")"
     esac
 }
 
@@ -32,9 +32,10 @@ ___x_cmd_env_try(){
 
     local i
     for i in "$@"; do
-        pkg:info "Prepare ${i%=*} $(___x_cmd_env_get_version "$i")"
-        if ! x pkg install "${i%=*}" "$(___x_cmd_env_get_version "$i")"; then
-            pkg:error "Cannot install package: $i"
+        ___x_cmd___env_pasre__pkg__version "$i"
+        env:info "Prepare $___X_CMD___ENV_PARSE_PKG $___X_CMD___ENV_PARSE_VERSION"
+        if ! ___x_cmd_pkg install "$___X_CMD___ENV_PARSE_PKG" "$___X_CMD___ENV_PARSE_VERSION"; then
+            env:error "Cannot install package: $___X_CMD___ENV_PARSE_PKG $___X_CMD___ENV_PARSE_VERSION"
             return 1
         fi
     done
@@ -42,14 +43,17 @@ ___x_cmd_env_try(){
     local ___X_CMD___ENV_PARSE_PKG
     local ___X_CMD___ENV_PARSE_VERSION
     for i in "$@"; do
-        ___x_cmd___env_store_prev "$i"
-        x pkg activate "$___X_CMD___ENV_PARSE_PKG" "$___X_CMD___ENV_PARSE_VERSION"
+        ___x_cmd___env_pasre__pkg__version "$i"
+        ___x_cmd___env_store_prev "$___X_CMD___ENV_PARSE_PKG"
+        env:debug "Try $___X_CMD___ENV_PARSE_PKG $___X_CMD___ENV_PARSE_VERSION"
+        ___x_cmd_pkg deactivate "$___X_CMD___ENV_PARSE_PKG" 2>/dev/null
+        [ -n "$___X_CMD___ENV_PARSE_VERSION" ] || return 0
+        ___x_cmd_pkg activate "$___X_CMD___ENV_PARSE_PKG" "$___X_CMD___ENV_PARSE_VERSION"
         ___x_cmd___env_store_current "$___X_CMD___ENV_PARSE_PKG" "$___X_CMD___ENV_PARSE_VERSION"
     done
 
-    local ___X_CMD_ENV___CONFIGSTR_SET_
-    ___x_cmd_env___configstr_set_ "$___X_CMD_ENV___CONFIGSTR_SET_" "$@"
-    ___X_CMD_ENV_VERSION_CONFIG="$___X_CMD_ENV___CONFIGSTR_SET_"
+    ___x_cmd_env___configstr_set_ "$___X_CMD_ENV_VERSION_CONFIG_PATH" "$@"
+    ___X_CMD_ENV_VERSION_CONFIG="$(___x_cmd_ldict_print ___X_CMD_ENV___CONFIGSTR_SET_)"
 }
 
 # use = try + save-config
@@ -57,30 +61,39 @@ ___x_cmd_env_use(){
     x:trace env/use
     ___x_cmd_env_try "$@" || return
 
-    ___x_cmd_env_configfile_set "$@"
+    ___x_cmd_env_config_set "$@"
 }
 
 # TODO
-___x_cmd_env_unuse(){
+___x_cmd_env_untry(){
     local i
     local pkg_name
     local version
+    local ___X_CMD_ENV_PREV
 
-    local code=___x_cmd_env_config_set
+    local code=___x_cmd_env___configstr_set_
     for i in "$@"; do
         pkg_name="${i%=*}"
-        x pkg deactivate "$pkg_name"
-        ___x_cmd___env_store_prev "$pkg_name"
-        ___x_cmd___env_store_current "$pkg_name"
+        ___x_cmd_pkg deactivate "$pkg_name"
+        ___x_cmd_env_prev_ "$pkg_name"
+        env:debug "untry $pkg_name recover $___X_CMD_ENV_PREV"
+        [ -z "$___X_CMD_ENV_PREV" ] || ___x_cmd___env_store_current "$pkg_name" "$___X_CMD_ENV_PREV"
         code="$code $pkg_name="
     done
 
-    eval "$code"        # Remove config in file
+    eval "$code"
 }
+___x_cmd_env_unuse(){
+    x:trace env/unuse
+    ___x_cmd_env_untry "$@" || return
+    ___x_cmd_env_config_save "$___X_CMD_ENV_VERSION_CONFIG_PATH"
+}
+
+
 
 ___x_cmd_env_which(){
     local i
     for i in "$@"; do
-        x pkg xbin path "${i%=*}" "$(___x_cmd_env_get_version "$i")"
+        ___x_cmd_pkg xbin path "${i%=*}" "$(___x_cmd_env_get_version "$i")"
     done
 }
diff --git a/mod/ffmpeg/latest b/mod/ffmpeg/latest
--- a/mod/ffmpeg/latest
+++ b/mod/ffmpeg/latest
@@ -1,35 +1,6 @@
 # Author:       Li Junhao       l@x-cmd.com                 # xrc
 # shellcheck    shell=sh        disable=SC2039,3043
 
-xrc param pkg/lib/staticbin os
-
-___x_cmd_ffmpeg_download(){
-    local arch
-    arch="$(os arch)"
-    local osname
-    osname="$(os name)"
-    local exe
-    case "$osname" in
-        win)    exe=ffmpeg.x64.exe        ;;
-        *)      exe=ffmpeg.${osname}.${arch}  ;;
-    esac
-    ___x_cmd_staticbin_init \
-        ___x_cmd_ffmpeg_download \
-            "$___X_CMD_ROOT/.bin/ffmpeg" "$exe" "$(___x_cmd_ffmpeg_bin_download_url "$exe")" \
-        && (
-            cd "$___X_CMD_ROOT/.bin/ffmpeg" && chmod +x "$exe"
-        )&& ___x_cmd_ffmpeg_download "$@"
-}
-
-___x_cmd_ffmpeg_bin_download_url(){
-    local exe="${1:?Provide app name}"
-    if [ "$___X_CMD_WHICHNET" != cn ]; then
-        printf "%s/%s" "https://raw.githubusercontent.com/static-build/ffmpeg/main/bin" "$exe.7z"
-    else
-        printf "%s/%s" "https://gitcode.net/x-bash/ffmpeg/-/raw/master/bin" "$exe.7z"
-    fi
-}
-
 ___x_cmd_ffmpeg(){
     local op="$1"
 
@@ -37,14 +8,17 @@ ___x_cmd_ffmpeg(){
         show)       shift; ___x_cmd_ffmpeg_show "$@" ;;
         convert)    shift; ___x_cmd_ffmpeg_convert "$@" ;;
         play)       shift; ___x_cmd_ffmpeg_play "$@" ;;
-        -*)         shift; ___x_cmd_ffmpeg_origin "$@" ;;
-        *)          ___x_cmd_ffmpeg_download "$@" ;;
+        *)          shift; ___x_cmd_ffmpeg_origin "$@" ;;
     esac
 
 }
 
 ___x_cmd_ffmpeg_origin(){
-    command ffmpeg "$@"
+    if ! ___x_cmd_pkg_xbin_init ffmpeg ___x_cmd_ffmpeg_origin; then
+        x:error "Fail to pkg_xbin_init ffmpeg"
+        return 1
+    fi
+    ___x_cmd_ffmpeg_origin "$@"
 }
 
 ___x_cmd_ffmpeg_show(){
