...

diff --git a/mod/env/lib/ls b/mod/env/lib/ls
--- a/mod/env/lib/ls
+++ b/mod/env/lib/ls
@@ -4,7 +4,6 @@ ___X_CMD_PKG_INSTALL_PATH="$___X_CMD_ROOT_TMP/pkg/installed"
 ___X_CMD_PKG_RAWPATH="$___X_CMD_ROOT_TMP/pkg/raw"
 
 ___x_cmd_env_ls(){
-    param:void
     case "$1" in
         i|installed)      shift;  ___x_cmd_env_ls_installed "$@" ;;
         a|activated)      shift;  ___x_cmd_env_ls_activated "$@" ;;
@@ -16,12 +15,20 @@ ___x_cmd_env_ls(){
 # Invoked pkg ls installed
 ___x_cmd_env_ls_installed()(
     if ! [ -d "$___X_CMD_PKG_INSTALL_PATH" ]; then return 0; fi
-    cd "$___X_CMD_PKG_INSTALL_PATH/$1"
+    if ! cd "$___X_CMD_PKG_INSTALL_PATH/$1"; then
+        pkg:debug "No pkg found."
+        return 0
+    fi
+
     pkg:debug "dir $___X_CMD_PKG_INSTALL_PATH/$1"
     for i in *; do
         printf "%s\n" "$i"
     done
-    cd - 1>/dev/null
+
+    if ! cd "$OLD_PWD"; then
+        pkg:warn "Cannot go back $OLD_PWD"
+        return 0
+    fi
     # printf "%s\n" "$___X_CMD_ENV_VERSION_CONFIG" | awk '$0!=""{gsub("=", "\t", $0); print $0}'
 )
 
diff --git a/mod/pkg/lib/main b/mod/pkg/lib/main
--- a/mod/pkg/lib/main
+++ b/mod/pkg/lib/main
@@ -14,3 +14,24 @@ ___x_cmd_pkg_version(){
         -f "$___X_CMD_ROOT_MOD/awk/pkg.lsversion.awk"
 }
 
+xrc p7zip
+
+___x_cmd_pkg___which_p7zip(){
+    ___x_cmd_ensuredir "$___X_CMD_PKG_RAWPATH"
+
+    local p7zip="$___X_CMD_ROOT_TMP/pkg/all.7z"
+    if ! ___x_cmd_httpget_gitx x-cmd pkg main "dist/all.7z" "$p7zip" "${1:-3600}"; then # 1-day
+        if [ ! -f "$p7zip" ]; then
+            x:error "Unaviable all.7z. Unable to fetch all.7z."
+            return 1
+        fi
+    fi
+
+    [ "$___X_CMD_HTTPGET_AGE" != 0 ] || (
+        pkg:info "Deflate the all.7z"
+        x rmrf "$___X_CMD_PKG_RAWPATH"
+        ___x_cmd_ensuredir "$___X_CMD_PKG_RAWPATH"
+        cd "${p7zip%/*}" && cp all.7z raw/all.7z && cd raw && p7zd x all.7z 1>/dev/null && rm all.7z
+    )
+}
+
