...

diff --git a/mod/env/lib/main b/mod/env/lib/main
--- a/mod/env/lib/main
+++ b/mod/env/lib/main
@@ -13,7 +13,8 @@ perl
 springboot
 deno
 kotlin
-gradle"
+gradle
+"
 
 }
 
@@ -68,8 +69,6 @@ A
 ___x_cmd_env_run_common_if_notfound(){
     local op="${1:?Provide op}";  shift
     local candidate="${1:?Provide candidate}";  shift
-
-    # TODO: It might be better to have one folder for one language.
     xrc:mod:lib env "candidate/$candidate"
 
     local cmd="___x_cmd_env_${candidate}_${op}"
@@ -94,7 +93,7 @@ options:
 A
     param:run
 
-    local candidate="${1}"
+    local candidate="${1}"; shift
     if [ -z "$candidate" ]; then
         env:warn "No candidate specified"
         ___x_cmd_env_main_ls --help
@@ -104,8 +103,7 @@ A
     # TODO: 增加 本地简写版本对应关系 和 全局简写版本对应关系
     # TODO: V8 -> V8.2   --> (Remote) V8.6
     if [ -n "$remote" ] ; then
-        ___x_cmd_env_run_common_if_notfound ls_remote "$@"
-        # ___x_cmd_env_run_common_if_notfound gen "$candidate" "$@"
+        ___x_cmd_env_run_common_if_notfound ls_remote "$candidate" "$@"
         return
     fi
 
@@ -132,8 +130,8 @@ A
 
     local candidate="${1}"
     local version
-    if ! version="$(___x_cmd_env_run_common_if_notfound full_version "$candidate" "$2")"; then
-        env:error "Version of $candidate not found: $version"
+    if ! version="$(___x_cmd_env_run_common_if_notfound full_version_local "$candidate" "$2")"; then
+        env:error "Version of $candidate local not found: ${version}${2}"
         return 1
     fi
     shift 2
@@ -155,13 +153,12 @@ A
 
     local candidate="${1}"
     local version
-    if ! version="$(___x_cmd_env_run_common_if_notfound full_version "$candidate" "$2")"; then
-        env:error "Version of $candidate not found: $version"
+    if ! version="$(___x_cmd_env_run_common_if_notfound full_version_remote "$candidate" "$2")"; then
+        env:error "Version of $candidate local not found: ${version}${2}"
         return 1
     fi
-    shift 2
 
-    ___x_cmd_env_run_common_if_notfound use "$candidate" "$version" "$use_shims" "$@"
+    ___x_cmd_env_run_common_if_notfound use "$candidate" "$version" "$use_shims"
 }
 
 ___x_cmd_env_main_ws(){
@@ -176,6 +173,16 @@ ___x_cmd_env_main_ws(){
 
 # Section: current
 ___x_cmd_env_main_current(){
+    if [ $# -eq 0 ]; then
+        local version
+        ___x_cmd_env_candidate_all | while read -r candidate; do
+            if version="$(___x_cmd_env_run_common_if_notfound current "$candidate" 2>/dev/null)" ; then
+                printf "%-16s  %s\n" "$candidate" "$version"
+            fi
+        done
+        return
+    fi
+
     param:scope "env"
     param:dsl <<A
 options:
@@ -190,7 +197,6 @@ A
 
 # Section: install, uninstall
 ___x_cmd_env_main_install(){
-    # TODO: You can do more better in #2 advise json
     param:scope "env"
     param:dsl <<A
 advise:
@@ -202,26 +208,18 @@ options:
 A
     param:run
 
-    local candidate="${1}"
+    local candidate="$1"
+    local version="$2"
     if [ -z "$candidate" ]; then
-        xrc:mod:lib env app/lsenv && ___x_cmd_ui_lsenv
-        # TODO: how to use shims
-        if [ "$___X_CMD_UI_LSENV_FINAL_COMMAND" = "ENTER" ]; then
-            candidate="$___X_CMD_UI_LSENV_CURRENT_CANDIDATE"
-            local version="$___X_CMD_UI_LSENV_CURRENT_VERSION"
-            ___x_cmd_env_run_common_if_notfound install "$candidate" "$version" "$@"
-        fi
-        return 0
+        xrc:mod:lib env   app/lsenv && ___x_cmd_ui_lsenv || return 1
     fi
 
-    local version
-    if ! version="$(___x_cmd_env_run_common_if_notfound full_version "$candidate" "$2")"; then
-        env:error "Version of $candidate not found: $version"
+    if ! version="$(___x_cmd_env_run_common_if_notfound full_version_remote "$candidate" "$version")"; then
+        env:error "Version of $candidate not found: ${version}${2}"
         return 1
     fi
-    shift 2
 
-    ___x_cmd_env_run_common_if_notfound install "$candidate" "$version" "$use_shims" "$@"
+    ___x_cmd_env_run_common_if_notfound install "$candidate" "$version" "$use_shims"
 }
 
 ___x_cmd_env_main_uninstall(){
@@ -231,7 +229,7 @@ advise:
     #2        xrc env/latest && ___x_cmd_env_advise_ls_local_version
 options:
     #1        "Environment Candidates" <candidates>:candidates_list
-    #2        "Version"                <version>
+    #2        "Version"
 A
     param:run
 
@@ -242,13 +240,14 @@ A
     fi
 
     local version
-    if ! version="$(___x_cmd_env_run_common_if_notfound full_version "$candidate" "$2")"; then
-        env:error "Version of $candidate not found: $version"
+    version="${2:-"$(___x_cmd_env_run_common_if_notfound current "$candidate")"}"
+    version="$(___x_cmd_env_run_common_if_notfound full_version_local "$candidate" "$version")"
+    if [ -z "$version" ] || [ "$version" = "system" ]; then
+        env:error "Version of $candidate was not installed by xenv: ${version}${2}"
         return 1
     fi
-    shift 2
 
-    ___x_cmd_env_run_common_if_notfound uninstall "$candidate" "$version" "$@"
+    ___x_cmd_env_run_common_if_notfound uninstall "$candidate" "$version"
 }
 # EndSection
 
@@ -265,29 +264,22 @@ options:
 A
     param:run
 
-    local candidate="${1}"
+    local candidate="$1"
+    local version="$2"
     if [ -z "$candidate" ]; then
-        xrc env/lib/app/lsenv && ___x_cmd_ui_lsenv
-        # TODO: how to use shims
-        if [ "$___X_CMD_UI_LSENV_FINAL_COMMAND" = "ENTER" ]; then
-            candidate="$___X_CMD_UI_LSENV_CURRENT_CANDIDATE"
-            local version="$___X_CMD_UI_LSENV_CURRENT_VERSION"
-            ___x_cmd_env_run_common_if_notfound download "$candidate" "$version" "$@"
-        fi
-        return 0
+        xrc:mod:lib env   app/lsenv && ___x_cmd_ui_lsenv || return 1
     fi
 
-    local version
-    if ! version="$(___x_cmd_env_run_common_if_notfound full_version "$candidate" "$2")"; then
+    if ! version="$(___x_cmd_env_run_common_if_notfound full_version_remote "$candidate" "$version")"; then
         env:error "Version of $candidate not found: $version"
         return 1
     fi
-    shift 2
 
     ___x_cmd_env_run_common_if_notfound download "$candidate" "$version" "$@"
 }
 
 ___x_cmd_env_main_which(){
+
     param:scope "env"
     param:dsl <<A
 advise:
@@ -340,7 +332,7 @@ A
         *=*) version="${1#*=}" ;;
     esac
 
-    if ! version="$(___x_cmd_env_run_common_if_notfound full_version "$candidate" "$version")"; then
+    if ! version="$(___x_cmd_env_run_common_if_notfound full_version_remote "$candidate" "$version")"; then
         env:error "Version of $candidate not found: $2"
         return 1
     fi
diff --git a/mod/log/latest b/mod/log/latest
--- a/mod/log/latest
+++ b/mod/log/latest
@@ -60,7 +60,7 @@ ${logger_name}_log(){     ___x_cmd_log_pr $logger_name \"\$@\";   }
     for level_code in 1 2 3 4; do
         ___x_cmd_log_level_code_to_level_name "$level_code"
         code="$code
-alias ${logger_name}:$level_name='test $level_code -lt \"\${___X_CMD_LOG__${logger_name}:-2}\" || O=${logger_name} ___x_cmd_log_pr_${level_name}'
+alias ${logger_name}:$level_name='test -z \"\$___X_CMD_LOG_DEBUG\" -a $level_code -lt \"\${___X_CMD_LOG__${logger_name}:-2}\" || O=${logger_name} ___x_cmd_log_pr_${level_name}'
 "
     done
 
@@ -157,11 +157,12 @@ ___x_cmd_log_level_code_to_level_name(){
 }
 
 ___x_cmd_log_set_level(){
+    x:trace x/log
     local logger_name="${1:?Provide loggername}"
 
     # TODO: how to check the logger_name is valid?
     if ! ___x_cmd_validenvname "${logger_name}"; then
-        ___x_cmd_log_pr log error "Logger Name should be match [0-9A-Za-z_]+ "
+        ___x_cmd_log_pr x error "Logger Name should be match [0-9A-Za-z_]+ "
         return 1
     fi
 
@@ -187,7 +188,13 @@ ___x_cmd_log_set_level(){
     fi
 
     # eval "$O:debug  \"Level of logger [\$logger_name] is set to [\$level]\""
-    ___x_cmd_log_pr log info "Level of logger [$logger_name] is set to [$level_name]"
+    ___x_cmd_log_pr x info "Level of logger [$logger_name] is set to [$level_name]"
+}
+
+___x_cmd_log_get_level_name(){
+    # local level_name
+    eval ___x_cmd_log_level_code_to_level_name "\$___X_CMD_LOG__${1:?Provide logger name}"
+    # printf "%s" "$level_name"
 }
 
 ___x_cmd_log_show_level(){
@@ -221,12 +228,12 @@ ___x_cmd_log_help(){
 
 # Section: printer
 # TODO: To move xrc_log
-___X_CMD_LOG_C_TF=
+___X_CMD_LOG_C_TF="${___X_CMD_LOG_C_TF:-""}"
 
 ___X_CMD_LOG__TIMESTAMP_FORMAT=      # "+%H:%M:%S"      # Enable Timestamp.
 
 ___X_CMD_LOG_C_MSG="${___X_CMD_LOG_C_MSG:-""}"
-___X_CMD_LOG_C_DEBUG="${___X_CMD_LOG_C_DEBUG:-"\\033[0;35m"}"
+___X_CMD_LOG_C_DEBUG="${___X_CMD_LOG_C_DEBUG:-"\\033[2;35m"}"
 ___X_CMD_LOG_C_INFO="${___X_CMD_LOG_C_INFO:-"\\033[1;36m"}"
 ___X_CMD_LOG_C_WARN="${___X_CMD_LOG_C_WARN:-"\\033[1;33m"}"
 ___X_CMD_LOG_C_ERROR="${___X_CMD_LOG_C_ERROR:-"\\033[1;31m"}"
@@ -236,11 +243,11 @@ ___X_CMD_LOG_C_TIMESTAMP_END="${___X_CMD_LOG_C_WARN:-"]"}"
 
 ___x_cmd_log_pr(){
     case "${2:?Provide level}" in
-        debug)      eval "test 1 -ge \"\${___X_CMD_LOG__${1#:}:-2}\"" && { local O="${1#:}"; shift 2; L=DBG C="$___X_CMD_LOG_C_DEBUG"  ___x_cmd_log_0 "$@"; } ;;
-        info)       eval "test 2 -ge \"\${___X_CMD_LOG__${1#:}:-2}\"" && { local O="${1#:}"; shift 2; L=INF C="$___X_CMD_LOG_C_INFO"   ___x_cmd_log_0 "$@"; } ;;
-        warn)       eval "test 3 -ge \"\${___X_CMD_LOG__${1#:}:-2}\"" && { local O="${1#:}"; shift 2; L=WRN C="$___X_CMD_LOG_C_WARN"   ___x_cmd_log_0 "$@"; } ;;
-        error)      eval "test 4 -ge \"\${___X_CMD_LOG__${1#:}:-2}\"" && { local O="${1#:}"; shift 2; L=ERR C="$___X_CMD_LOG_C_ERROR"  ___x_cmd_log_0 "$@"; } ;;
-        *)          eval "test 3 -ge \"\${___X_CMD_LOG__${1#:}:-2}\"" && { local O="${1#:}"; shift 1; L=INF C="$___X_CMD_LOG_C_INFO"   ___x_cmd_log_0 "$@"; } ;;
+        debug)      eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 1 -lt \"\${___X_CMD_LOG__${1#:}:-2}\"" || { local O="${1#:}"; shift 2; L=DBG C="$___X_CMD_LOG_C_DEBUG"  ___x_cmd_log_0 "$@"; } ;;
+        info)       eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 2 -lt \"\${___X_CMD_LOG__${1#:}:-2}\"" || { local O="${1#:}"; shift 2; L=INF C="$___X_CMD_LOG_C_INFO"   ___x_cmd_log_0 "$@"; } ;;
+        warn)       eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 3 -lt \"\${___X_CMD_LOG__${1#:}:-2}\"" || { local O="${1#:}"; shift 2; L=WRN C="$___X_CMD_LOG_C_WARN"   ___x_cmd_log_0 "$@"; } ;;
+        error)      eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 4 -lt \"\${___X_CMD_LOG__${1#:}:-2}\"" || { local O="${1#:}"; shift 2; L=ERR C="$___X_CMD_LOG_C_ERROR"  ___x_cmd_log_0 "$@"; } ;;
+        *)          eval "test -z \"\$___X_CMD_LOG_DEBUG\" -a 3 -lt \"\${___X_CMD_LOG__${1#:}:-2}\"" || { local O="${1#:}"; shift 1; L=INF C="$___X_CMD_LOG_C_INFO"   ___x_cmd_log_0 "$@"; } ;;
     esac
 }
 
@@ -264,6 +271,9 @@ ___x_cmd_log_0(){
     local IFS=" "
     local timestamp
 
+    # ${___X_CMD_TRACE_LINE_LOCAL+<${___X_CMD_TRACE_LINE_LOCAL#"$O"}>
+    local track="${___X_CMD_TRACE_LINE_LOCAL}"
+    [ -z "$track" ] || track="<${track#"$O/"}> "
     if [ -n "$___X_CMD_LOG_C_TF" ] || [ -t 2 ]; then
         if [ -n "$___X_CMD_LOG__TIMESTAMP_FORMAT" ]; then
             timestamp="$(date "${___X_CMD_LOG__TIMESTAMP_FORMAT}")"
@@ -272,17 +282,17 @@ ___x_cmd_log_0(){
 
         if [ $# -gt 0 ]; then
             [ "$L" != "INF" ] || local ___X_CMD_LOG_C_MSG="\\033[1m"
-            printf "${timestamp}${C}[%s] <%s>: \033[0m${___X_CMD_LOG_C_MSG:-"$C"}%s\033[0m\n" "$L" "$O" "$*"
+            printf "${timestamp}${C}[%s] <%s>: $track\033[0m${___X_CMD_LOG_C_MSG:-"$C"}%s\033[0m\n" "$L" "$O" "$*"
         else
-            printf "${timestamp}${C}[%s] <%s>:" "$L" "$O"
+            printf "${timestamp}${C}[%s] <%s>: $track" "$L" "$O"
             cat | awk 'NR==1{ print($0) }; NR>=2{ print("> " $0); }; END{ printf("%s", "\033[0m"); }'
         fi
     else
         [ -z "$___X_CMD_LOG__TIMESTAMP_FORMAT" ] || timestamp="$(date "${___X_CMD_LOG__TIMESTAMP_FORMAT}") "
         if [ $# -gt 0 ]; then
-            printf "${timestamp}[%s] <%s>: %s\n" "$L" "$O" "$*"
+            printf "${timestamp}[%s] <%s>: $track%s\n" "$L" "$O" "$*"
         else
-            printf "${timestamp}[%s] <%s>:" "$L" "$O"
+            printf "${timestamp}[%s] <%s>: $track" "$L" "$O"
             cat | awk 'NR==1{ print($0) }; NR>=2{ print("> " $0); }; }'
         fi
     fi >&2
diff --git a/mod/yanfa/lib/release b/mod/yanfa/lib/release
--- a/mod/yanfa/lib/release
+++ b/mod/yanfa/lib/release
@@ -87,6 +87,7 @@ ___X_CMD_YANFA_RELEASE_TMP="${TMPDIR}/release/mod"
 
 
 ___x_cmd_yanfa_release_add()(
+    x:trace yanfa/relesae/add
     local name="${1:?Provide module name}"
     # local position="${2:-"git@gitee.com/x-bash/$name.git"}"
     local position="${2:-"https://$(___x_cmd_yanfa_release_gitx)/x-bash/$name.git"}"
@@ -96,19 +97,20 @@ ___x_cmd_yanfa_release_add()(
 
     for ((i=1; i<=3; i=i+1)); do
         if git clone --quiet --depth=1 "$position" -b "$branch"; then
-            yanfa:debug "<release-add> [$mod/$branch] Cloning success from $position"
+            yanfa:info "[$mod/$branch] Cloning success from $position"
             exit 0
         fi
-        yanfa:info "<release-add> Fail to git clone. Retry it after 5 seconds"
+        yanfa:info "Fail to git clone. Retry it after 5 seconds"
         if ! sleep 5; then
-            yanfa:info "<release-add> Sleep interrupted."
+            yanfa:warn "Sleep interrupted."
         fi
     done
-    yanfa:debug error "<release-add> Fail to git clone after 3 attemps. Mission abort."
+    yanfa:error "Fail to git clone after 3 attemps. Mission abort."
     exit 1
 )
 
 ___x_cmd_yanfa_release_update(){
+    x:trace yanfa/relesae/update
     param:void
 
     local IFS=""
@@ -134,9 +136,9 @@ ___x_cmd_yanfa_release_update(){
         esac
     done
 
-    yanfa:debug "<release-cpfile> Starting"
+    yanfa:debug "Starting CPFILE"
     ___x_cmd_yanfa_release_cpfile
-    yanfa:debug "<release-cpfile> exit: $?"
+    yanfa:debug "FINISIH CPFILE exit: $?"
 }
 
 # EndSection
@@ -145,6 +147,7 @@ ___x_cmd_yanfa_release_update(){
 
 # shellcheck disable=SC2120
 ___x_cmd_yanfa_release_lsmod(){
+    x:trace yanfa/relesae/lsmod
     param:void
     ___x_cmd_yanfa_mod_ls "$@"
     local code=$?
@@ -153,6 +156,7 @@ ___x_cmd_yanfa_release_lsmod(){
 }
 
 ___x_cmd_yanfa_release_lsfile()(
+    x:trace yanfa/relesae/lsfile
     param:void
     [ -d "$___X_CMD_YANFA_RELEASE_TMP" ] || return 1
 
@@ -177,6 +181,7 @@ ___x_cmd_yanfa_release_lsfile()(
 )
 
 ___x_cmd_yanfa_release_cpfile_inner(){
+    # x:trace yanfa/relesae/cpfile/inner        # Use debug
     if [ -d "$2" ]; then
         local p="$2/$1"
         [ -d "${p%/*}" ] || mkdir -p "${p%/*}"
@@ -191,6 +196,8 @@ ___x_cmd_yanfa_release_cpfile_inner(){
 }
 
 ___x_cmd_yanfa_release_cpfile()(
+    x:trace yanfa/relesae/cpfile
+    yanfa:debug "Staring"
     local tgt
     tgt="$(x wsroot)/mod"
     [ -d "$tgt" ] && rm -rf "$tgt"
@@ -204,10 +211,11 @@ ___x_cmd_yanfa_release_cpfile()(
         )
     done
     # TODO: In Github Action, it return 1. Resulting in breaking. cpfile_inner is OK. The bug might be in while pipe.
-    yanfa:debug "<release_cpfile> exit: $?"
+    yanfa:debug "exit: $?"
 )
 
 ___x_cmd_yanfa_release_wc(){
+    x:trace yanfa/relesae/wc
     param:void
     cd "$(x wsroot)/mod" &&
         ___x_cmd_yanfa_release_lsfile "$@" | xargs wc | sort -n -r | less
