...

diff --git a/mod/gl/lib/groups/main b/mod/gl/lib/groups/main
--- a/mod/gl/lib/groups/main
+++ b/mod/gl/lib/groups/main
@@ -2,11 +2,11 @@
 # shellcheck disable=SC2039,3043
 
 # define lazy loader
-# ___x_cmd_definelazyloader   ___x_cmd_gitlab_groups_member           gitlab/lib/groups/member
+# ___x_cmd_definelazyloader   ___x_cmd_gl_groups_member           gl/lib/groups/member
 
-___x_cmd_gitlab_groups(){
-    param:scope     ___x_cmd_gitlab
-    param:subcmd ___x_cmd_gitlab_groups                                                 \
+___x_cmd_gl_groups(){
+    param:scope     ___x_cmd_gl
+    param:subcmd ___x_cmd_gl_groups                                                 \
         ls                      "List all groups"                                       \
         info                    "Show groups information"                               \
         create                  "Create groups"                                         \
@@ -17,29 +17,29 @@ ___x_cmd_gitlab_groups(){
     param:subcmd:try
     param:run
 
-    ___x_cmd_gitlab_groups _param_help_doc
-    gitlab_log warn "Subcmd Not Found."
+    ___x_cmd_gl_groups _param_help_doc
+    gl_log warn "Subcmd Not Found."
     return 1
 }
 
-___x_cmd_gitlab_subgroup(){
-    param:scope     ___x_cmd_gitlab
-    param:subcmd ___x_cmd_gitlab_subgroup               \
+___x_cmd_gl_subgroup(){
+    param:scope     ___x_cmd_gl
+    param:subcmd ___x_cmd_gl_subgroup               \
         ls                      "List all subgroups"    \
         create                  "Create subgroups"
     param:subcmd:try
     param:run
 
-    ___x_cmd_gitlab_subgroup _param_help_doc
-    gitlab_log warn "Subcmd Not Found."
+    ___x_cmd_gl_subgroup _param_help_doc
+    gl_log warn "Subcmd Not Found."
     return 1
 }
 
 # Section: list & info
 # shellcheck disable=SC2154
 # skip_groups  正则	array of integers
-___x_cmd_gitlab_groups_ls(){
-    param:scope     ___x_cmd_gitlab
+___x_cmd_gl_groups_ls(){
+    param:scope     ___x_cmd_gl
     param:dsl       '
 type:
     order_by = name path id  similarity
@@ -60,13 +60,13 @@ options:
 '
     param:run
 
-    ___gitlab_ui_mutual ___x_cmd_gitlab_get_multi "/groups" per_page  page <<A
+    ___gl_ui_mutual ___x_cmd_gl_get_multi "/groups" per_page  page <<A
         ___ui_table_json Id=.id Name=.name Path=.path Visibility=.visibility Url=.web_url -- \$@
 A
 }
 
-___x_cmd_gitlab_subgroup_ls(){
-    param:scope     ___x_cmd_gitlab
+___x_cmd_gl_subgroup_ls(){
+    param:scope     ___x_cmd_gl
     param:dsl       '
 type:
     order_by = name path id  similarity
@@ -86,14 +86,14 @@ options:
 '
     param:run
 
-    ___gitlab_ui_mutual ___x_cmd_gitlab_get_multi "/groups/$1/subgroups" <<A
+    ___gl_ui_mutual ___x_cmd_gl_get_multi "/groups/$1/subgroups" <<A
         ___ui_table_json Id=.id Name=.name Path=.path Visibility=.visibility Url=.web_url -- \$@
 A
 }
 
 # shellcheck disable=SC2154
-___x_cmd_gitlab_groups_info(){
-    param:scope     ___x_cmd_gitlab
+___x_cmd_gl_groups_info(){
+    param:scope     ___x_cmd_gl
     param:dsl       '
 options:
     #1|--groups                 "The ID or URL-encoded path of the group"     <>=""
@@ -102,7 +102,7 @@ options:
 '
     param:run
 
-    ___x_cmd_gitlab_http get "/groups/${1:?Provide groups ID or path}" | \
+    ___x_cmd_gl_http get "/groups/${1:?Provide groups ID or path}" | \
     {
         ___x_cmd_git_json_query_rename id=.id name=.name dir=.path visibility=.visibility url=.web_url
         if [ -n "$id" ]; then
@@ -117,9 +117,9 @@ options:
 
 # Section: create
 # shellcheck disable=SC2181
-# TODO:On GitLab SaaS, you must use the GitLab UI to create groups without a parent group. You cannot use the API to do this.???
-___x_cmd_gitlab_groups_create(){
-    param:scope     ___x_cmd_gitlab
+# TODO:On gl SaaS, you must use the gl UI to create groups without a parent group. You cannot use the API to do this.???
+___x_cmd_gl_groups_create(){
+    param:scope     ___x_cmd_gl
     param:dsl       '
 options:
     -p|--path                   "groups path"                   <>=""
@@ -131,13 +131,13 @@ options:
     param:run
     local name
     name="$1"
-    [ $# -ne 0 ] || { gitlab_log error "Please provide groups name"; return 1; }
-    local gitlab_path="$name"
-    [ -z "$p" ] || gitlab_path="$p"
-    local gen_gitlab_json
-    gen_gitlab_json="$(param:option2json -p +name path=gitlab_path)"
+    [ $# -ne 0 ] || { gl_log error "Please provide groups name"; return 1; }
+    local gl_path="$name"
+    [ -z "$p" ] || gl_path="$p"
+    local gen_gl_json
+    gen_gl_json="$(param:option2json -p +name path=gl_path)"
 
-    ___x_cmd_gitlab_http post "/groups" "$gen_gitlab_json" | \
+    ___x_cmd_gl_http post "/groups" "$gen_gl_json" | \
     {
         ___x_cmd_git_json_query_rename id=.id
         if [ -n "$id" ]; then
@@ -152,9 +152,9 @@ options:
 
 # Section: create subgroup
 # shellcheck disable=SC2181
-# TODO:On GitLab SaaS, you must use the GitLab UI to create groups without a parent group. You cannot use the API to do this.???
-___x_cmd_gitlab_subgroup_create(){
-    param:scope     ___x_cmd_gitlab
+# TODO:On gl SaaS, you must use the gl UI to create groups without a parent group. You cannot use the API to do this.???
+___x_cmd_gl_subgroup_create(){
+    param:scope     ___x_cmd_gl
     param:dsl       '
 options:
     --parent_id         "parent groups id."    <>
@@ -164,8 +164,8 @@ options:
     param:run
     local group_path="$subgroup_path"
     [ -n "$group_path" ] || group_path="$name"
-    gen_gitlab_json="$(param:option2json -subgroup_path path=group_path)"
-    ___x_cmd_gitlab_http post "/groups" "$gen_gitlab_json"| \
+    gen_gl_json="$(param:option2json -subgroup_path path=group_path)"
+    ___x_cmd_gl_http post "/groups" "$gen_gl_json"| \
     {
         ___x_cmd_git_json_query_rename id=.id
         if [ -n "$id" ]; then
@@ -179,8 +179,8 @@ options:
 # EndSection
 
 # Section:groups update
-___x_cmd_gitlab_groups_update(){
-    param:scope     ___x_cmd_gitlab
+___x_cmd_gl_groups_update(){
+    param:scope     ___x_cmd_gl
     param:dsl       '
 options:
     -p|--path                   "groups path"                   <>=""
@@ -191,13 +191,13 @@ options:
     #1                          "The ID of the group."
 '
     param:run
-    [ $# -ne 0 ] || { gitlab_log error "Please provide groups ID"; return 1; }
-    local gitlab_path="$p"
-    local gen_gitlab_json
-    # path=gitlab_path
-    gen_gitlab_json="$(param:option2json -p path=gitlab_path)"
+    [ $# -ne 0 ] || { gl_log error "Please provide groups ID"; return 1; }
+    local gl_path="$p"
+    local gen_gl_json
+    # path=gl_path
+    gen_gl_json="$(param:option2json -p path=gl_path)"
 
-    ___x_cmd_gitlab_http put "/groups/$1" "$gen_gitlab_json" | \
+    ___x_cmd_gl_http put "/groups/$1" "$gen_gl_json" | \
     {
         ___x_cmd_git_json_query_rename id=.id
         if [ -n "$id" ]; then
@@ -211,20 +211,20 @@ options:
 # EndSection
 
 # Section: groups repo
-___x_cmd_gitlab_groups_repo(){
-    param:subcmd ___x_cmd_gitlab_groups_repo    \
+___x_cmd_gl_groups_repo(){
+    param:subcmd ___x_cmd_gl_groups_repo    \
         ls          "list repo"
         # create      "groups repo create"
     param:subcmd:try
     param:run
 
-    ___x_cmd_gitlab_groups_repo _param_help_doc
-    gitlab_log warn "Subcmd Not Found."
+    ___x_cmd_gl_groups_repo _param_help_doc
+    gl_log warn "Subcmd Not Found."
     return 1
 }
 
-___x_cmd_gitlab_groups_repo_ls(){
-    param:scope     ___x_cmd_gitlab
+___x_cmd_gl_groups_repo_ls(){
+    param:scope     ___x_cmd_gl
     param:dsl       '
 options:
     #1|--id        "The ID or group path"           <>:Address
@@ -235,7 +235,7 @@ options:
 '
     param:run
 
-    ___gitlab_ui_mutual ___x_cmd_gitlab_get_multi "/groups/$id/projects" page per_page visibility archived <<A
+    ___gl_ui_mutual ___x_cmd_gl_get_multi "/groups/$id/projects" page per_page visibility archived <<A
         ___ui_table_json Id=.id Name=.name path=.path visibility=.visibility web_url=.web_url -- \$@
 A
 }
@@ -245,8 +245,8 @@ A
 
 
 # Section: groups issue ls
-___x_cmd_gitlab_groups_issue(){
-    param:scope     ___x_cmd_gitlab
+___x_cmd_gl_groups_issue(){
+    param:scope     ___x_cmd_gl
     param:dsl       '
 options:
    --id                                    "The ID or URL-encoded path of the project owned by the authenticated user"                                                  <>
@@ -280,7 +280,7 @@ options:
 '
  param:run
 
-  ___gitlab_ui_mutual  ___x_cmd_gitlab_get_multi  "/groups/$id/issues" sort order_by search state  <<A
+  ___gl_ui_mutual  ___x_cmd_gl_get_multi  "/groups/$id/issues" sort order_by search state  <<A
         ___ui_table_json Id=.id iid=.iid project_id=.project_id title=.title state=.state web_url=.web_url -- \$@
 A
 }
diff --git a/mod/gl/lib/project/main b/mod/gl/lib/project/main
--- a/mod/gl/lib/project/main
+++ b/mod/gl/lib/project/main
@@ -1,9 +1,9 @@
 # shellcheck shell=sh
 # shellcheck disable=SC2039,3043
 
-___x_cmd_gitlab_project(){
-    param:scope         ___x_cmd_gitlab
-    param:subcmd ___x_cmd_gitlab_project                                   \
+___x_cmd_gl_project(){
+    param:scope         ___x_cmd_gl
+    param:subcmd ___x_cmd_gl_project                                   \
         create          "Create project"                                   \
         ls              "List project of owner"                            \
         info            "Show detailed information of project"             \
@@ -14,15 +14,15 @@ ___x_cmd_gitlab_project(){
     param:subcmd:try
     param:run
 
-    ___x_cmd_gitlab_project _param_help_doc
-    gitlab_log warn "Subcmd Not Found."
+    ___x_cmd_gl_project _param_help_doc
+    gl_log warn "Subcmd Not Found."
     return 1
 }
 
 # Section: create
 # shellcheck disable=SC2154
-___x_cmd_gitlab_project_create(){
-    param:scope     ___x_cmd_gitlab
+___x_cmd_gl_project_create(){
+    param:scope     ___x_cmd_gl
     param:dsl       '
 option:
     #1                                                  "project names"                                                                     <>:RepoName
@@ -90,17 +90,17 @@ option:
     --only_allow_merge_if_all_discussions_are_resolved  "Set whether merge requests can only be merged when all the discussions are resolved."
 '
     param:run
-    [ $# -ne 0 ] || { gitlab_log error "Please provide project name"; return 1; }
-    local gitlab_path="$1"
-    [ -z "$p" ] || gitlab_path="$p"
+    [ $# -ne 0 ] || { gl_log error "Please provide project name"; return 1; }
+    local gl_path="$1"
+    [ -z "$p" ] || gl_path="$p"
     local name="$1"
-    local gen_gitlab_json
-    gen_gitlab_json="$(param:option2json +name -p path=gitlab_path)"
-    ___x_cmd_gitlab_http post "/projects" "$gen_gitlab_json" | ___x_cmd_gitlab_project_create_status_handler
+    local gen_gl_json
+    gen_gl_json="$(param:option2json +name -p path=gl_path)"
+    ___x_cmd_gl_http post "/projects" "$gen_gl_json" | ___x_cmd_gl_project_create_status_handler
 }
 
 # shellcheck disable=SC2154
-___x_cmd_gitlab_project_create_status_handler(){
+___x_cmd_gl_project_create_status_handler(){
     if [ ! -t 1 ] || [ -n "$ENFORCE_JSON" ]; then
         cat
         return
@@ -118,15 +118,15 @@ ___x_cmd_gitlab_project_create_status_handler(){
 
 # Section: list
 # shellcheck disable=SC2154,SC2145
-___x_cmd_gitlab_project_ls(){
-    param:scope     ___x_cmd_gitlab
+___x_cmd_gl_project_ls(){
+    param:scope     ___x_cmd_gl
     param:dsl       '
 options:
 
 '
     param:run
-    ___x_cmd_gitlab_current_owner 1>/dev/null
-    ___gitlab_ui_mutual  ___x_cmd_gitlab_get_multi "/users/$___X_CMD_GITLAB_DEFAULT_OWNER/projects"  <<A
+    ___x_cmd_gl_current_owner 1>/dev/null
+    ___gl_ui_mutual  ___x_cmd_gl_get_multi "/users/$___x_cmd_gl_DEFAULT_OWNER/projects"  <<A
     ___ui_table_json Id=.id Name=.name Owner=.owner.username Url=.web_url -- \$@
 A
 }
@@ -135,8 +135,8 @@ A
 # Section: update
 
 # shellcheck disable=SC2154,SC2034
-___x_cmd_gitlab_project_update(){
-    param:scope     ___x_cmd_gitlab
+___x_cmd_gl_project_update(){
+    param:scope     ___x_cmd_gl
     param:dsl       '
 options:
     #1|--project|--id                                      "The ID or URL-encoded path of the project."      <>:RepoName
@@ -169,7 +169,7 @@ options:
     --merge_pipelines_enabled                           "Enable or disable merge pipelines.."
     --merge_requests_access_level                       "One of disabled, private, or enabled"                                                                                                          <>=""
     --merge_requests_enabled                            "(Deprecated) Enable merge requests for this project. Use instead."
-    --merge_requests_template                           "Default description for merge requests. Description is parsed with GitLab Flavored Markdown."                                                  <>=""
+    --merge_requests_template                           "Default description for merge requests. Description is parsed with gl Flavored Markdown."                                                  <>=""
     --merge_trains_enabled                              "Enable or disable merge trains.."
     --mirror_overwrites_diverged_branches               "Pull mirror overwrites diverged branches."
     --mirror_trigger_builds                             "mirror_trigger_builds"
@@ -202,21 +202,21 @@ options:
     --squash_commit_template                            "Template used to create squash commit message in merge requests"                                                                               <>=""
     --squash_option                                     "One of never, always, default_on, or default_off"                                                                                              <>=""
     --suggestion_commit_message                         "The commit message used to apply merge request suggestions."                                                                                   <>=""
-    --tag_list                                          "(Deprecated in GitLab 14.0) The list of tags for a project; put array of tags, that should be finally assigned to a project. Use instead."     <>:array=""
-    --topics                                            "The list of topics for the project. This replaces any existing topics that are already added to the project. (Introduced in GitLab 14.0.)."    <>:array=""
+    --tag_list                                          "(Deprecated in gl 14.0) The list of tags for a project; put array of tags, that should be finally assigned to a project. Use instead."     <>:array=""
+    --topics                                            "The list of topics for the project. This replaces any existing topics that are already added to the project. (Introduced in gl 14.0.)."    <>:array=""
     --visibility                                        "See project visibility level."                                                                                                                 <>=""
     --wiki_access_level                                 "One of disabled, private, or enabled"                                                                                                          <>="disabled"
     --wiki_enabled                                      "(Deprecated) Enable wiki for this project. Use instead. wiki_access_level"                                                                     <>
 '
     param:run
-    ___x_cmd_gitlab_param_init_owner_project
-    local gen_gitlab_json
-    gen_gitlab_json="$(param:option2json -project)"
+    ___x_cmd_gl_param_init_owner_project
+    local gen_gl_json
+    gen_gl_json="$(param:option2json -project)"
     # project name urlecode
-    ___x_cmd_gitlab_http put "/projects/$1" "$gen_gitlab_json" | ___x_cmd_gitlab_project_update_status_handler
+    ___x_cmd_gl_http put "/projects/$1" "$gen_gl_json" | ___x_cmd_gl_project_update_status_handler
 }
 
-___x_cmd_gitlab_project_update_status_handler(){
+___x_cmd_gl_project_update_status_handler(){
     if [ ! -t 1 ] || [ -n "$ENFORCE_JSON" ]; then
         cat
         return
@@ -234,8 +234,8 @@ ___x_cmd_gitlab_project_update_status_handler(){
 
 # Section: info
 # shellcheck disable=SC2154
-___x_cmd_gitlab_project_info(){
-    param:scope     ___x_cmd_gitlab
+___x_cmd_gl_project_info(){
+    param:scope     ___x_cmd_gl
     param:dsl       '
 options:
     #1|--id                                 "The ID or URL-encoded path of the project."    <>
@@ -244,10 +244,10 @@ options:
     --with_custom_attributes                "Include custom attributes in response. (administrator only)"
 '
  param:run
-   ___x_cmd_gitlab_http get "/projects/$id"| ___x_cmd_gitlab_repo_info_status_handler
+   ___x_cmd_gl_http get "/projects/$id"| ___x_cmd_gl_repo_info_status_handler
 }
 
-___x_cmd_gitlab_repo_info_status_handler() {
+___x_cmd_gl_repo_info_status_handler() {
     if [ ! -t 1 ] || [ -n "$ENFORCE_JSON" ]; then
         cat
         return
@@ -265,15 +265,15 @@ ___x_cmd_gitlab_repo_info_status_handler() {
 
 # Section: del
 # shellcheck disable=SC2181,SC2154
-___x_cmd_gitlab_project_rm(){
-    param:scope     ___x_cmd_gitlab
+___x_cmd_gl_project_rm(){
+    param:scope     ___x_cmd_gl
     param:dsl       '
 options:
     #1|--id                                    "The ID or URL-encoded path of the project."   <>                                                                            <>
 '
  param:run
 
-    if ___x_cmd_gitlab_http delete "/projects/$1" >/dev/null; then
+    if ___x_cmd_gl_http delete "/projects/$1" >/dev/null; then
         ___x_cmd_ui_tf true  "Deleting repo $1 successfully"
     else
         ___x_cmd_ui_tf false "Deleting repo failure: $1. Probably because it desn't exists."
@@ -283,8 +283,8 @@ options:
 # EndSection
 
 # Section: project issue ls
-___x_cmd_gitlab_project_issue(){
-    param:scope     ___x_cmd_gitlab
+___x_cmd_gl_project_issue(){
+    param:scope     ___x_cmd_gl
     param:dsl       '
 options:
    --assignee_id                           "Return issues assigned to the given user id."                                                                               <>:Number=""
@@ -317,7 +317,7 @@ options:
 '
  param:run
 
-  ___gitlab_ui_mutual  ___x_cmd_gitlab_get_multi  "/projects/$id/issues" sort order_by search state  <<A
+  ___gl_ui_mutual  ___x_cmd_gl_get_multi  "/projects/$id/issues" sort order_by search state  <<A
         ___ui_table_json Id=.id iid=.iid project_id=.project_id title=.title state=.state web_url=.web_url -- \$@
 A
 }
diff --git a/mod/gl/lib/utils b/mod/gl/lib/utils
--- a/mod/gl/lib/utils
+++ b/mod/gl/lib/utils
@@ -4,33 +4,33 @@
 ############################
 # Section 2: Wrapping std/http module with object naming changing
 ############################
-___x_cmd_gitlab_resp_header(){
-    O="${O:-___X_BASH_HTTP____x_cmd_gitlab_GITLAB_DEFAULT}" ___x_cmd_http_resp header "$@"
+___x_cmd_gl_resp_header(){
+    O="${O:-___X_BASH_HTTP____x_cmd_gl_gl_DEFAULT}" ___x_cmd_http_resp header "$@"
 }
 
 # TODO: Not supported yet
-___x_cmd_gitlab_resp_body(){
-    O="${O:-___X_BASH_HTTP____x_cmd_gitlab_GITLAB_DEFAULT}" ___x_cmd_http_resp body "$@"
+___x_cmd_gl_resp_body(){
+    O="${O:-___X_BASH_HTTP____x_cmd_gl_gl_DEFAULT}" ___x_cmd_http_resp body "$@"
 }
 
-___x_cmd_gitlab_get_multi() {
+___x_cmd_gl_get_multi() {
     if [ -n "$page" ] || [ -n "$per_page" ]; then
-        ___x_cmd_gitlab_http get "$@" page per_page
+        ___x_cmd_gl_http get "$@" page per_page
         return
     fi
     local tmp
     tmp=$(mktemp)
-    ___x_cmd_gitlab_http get "$@" page=1 per_page=100 >> "$tmp"
+    ___x_cmd_gl_http get "$@" page=1 per_page=100 >> "$tmp"
     local next_url
-    _____x_cmd_gitlab_next_url
+    _____x_cmd_gl_next_url
     if [ -z "$next_url" ];then
         cat "$tmp"
         rm "$tmp"
         return
     fi
     while [ -n "$next_url" ]; do
-        ___x_cmd_gitlab_http get "$next_url" >> "$tmp"
-        _____x_cmd_gitlab_next_url
+        ___x_cmd_gl_http get "$next_url" >> "$tmp"
+        _____x_cmd_gl_next_url
     done
     x ja 'BEGIN{print "["} END{print "]"}O[1]{
     if ((V == "}") || (V == "]") || (K ~ "^[0-9]+$")) print V
@@ -39,8 +39,8 @@ ___x_cmd_gitlab_get_multi() {
     rm "$tmp"
 }
 
-_____x_cmd_gitlab_next_url(){
-    next_url="$(___x_cmd_gitlab_resp_header "link")"
+_____x_cmd_gl_next_url(){
+    next_url="$(___x_cmd_gl_resp_header "link")"
     next_url="${next_url#*'rel="prev", <'}"
     local tmp_url="${next_url%%'>; rel="next"'*}"
     if [ "$next_url" != "$tmp_url" ];then
@@ -50,23 +50,23 @@ _____x_cmd_gitlab_next_url(){
     fi
 }
 
-___x_cmd_gitlab_http(){
-    if ! O="${O:-___x_cmd_gitlab_GITLAB_DEFAULT}" ___x_cmd_http header get Content-Type 1>/dev/null 2>&1; then
-         O="${O:-___x_cmd_gitlab_GITLAB_DEFAULT}" ___x_cmd_http header put Content-Type application/json
+___x_cmd_gl_http(){
+    if ! O="${O:-___x_cmd_gl_gl_DEFAULT}" ___x_cmd_http header get Content-Type 1>/dev/null 2>&1; then
+         O="${O:-___x_cmd_gl_gl_DEFAULT}" ___x_cmd_http header put Content-Type application/json
     fi
-    O="${O:-___x_cmd_gitlab_GITLAB_DEFAULT}" ___x_cmd_http "$@"
+    O="${O:-___x_cmd_gl_gl_DEFAULT}" ___x_cmd_http "$@"
 }
 
 ############################
 # Section 3: Parameter Utilities
 ############################
 
-alias ___x_cmd_gitlab_param_init_owner_project='
+alias ___x_cmd_gl_param_init_owner_project='
     local owner_project
-    ___x_cmd_gitlab_param_normalize_repo  || return
+    ___x_cmd_gl_param_normalize_repo  || return
 '
 
-___x_cmd_gitlab_param_normalize_repo(){
+___x_cmd_gl_param_normalize_repo(){
     local op="$repo"
     [ -z "$op" ] && op="$1"
     case "$op" in
@@ -77,11 +77,11 @@ ___x_cmd_gitlab_param_normalize_repo(){
         owner_project="$(_____x_cmd_git_repo)"
         ;;
     *)
-        ___x_cmd_gitlab_current_owner 1>/dev/null
-        if [ -z "$___X_CMD_GITLAB_DEFAULT_OWNER" ]; then
+        ___x_cmd_gl_current_owner 1>/dev/null
+        if [ -z "$___x_cmd_gl_DEFAULT_OWNER" ]; then
             printf "No owner provided. Default owner not set.\n" >&2
         fi
-        owner_project="$(printf "%s" "$___X_CMD_GITLAB_DEFAULT_OWNER/$op")"
+        owner_project="$(printf "%s" "$___x_cmd_gl_DEFAULT_OWNER/$op")"
         ;;
     esac
     printf "%s" "$owner_project" | sed s:'/':'%2F':g
@@ -89,10 +89,10 @@ ___x_cmd_gitlab_param_normalize_repo(){
 
 ### Repo #1
 
-___x_cmd_gitlab_parse_owner_repo(){
-    local O="${O:-___x_cmd_gitlab_GITLAB_DEFAULT}"
+___x_cmd_gl_parse_owner_repo(){
+    local O="${O:-___x_cmd_gl_gl_DEFAULT}"
     if [ -z "$repo" ]; then
-        repo="$(___x_cmd_gitlab_current_repo)"
+        repo="$(___x_cmd_gl_current_repo)"
     fi
     # if [[ "$repo" = */* ]]; then
     if str_regex "$repo" "/"; then
@@ -100,11 +100,11 @@ ___x_cmd_gitlab_parse_owner_repo(){
         repo=${repo##*/}
     fi
     if [ -z "$owner" ]; then
-        owner="$(___x_cmd_gitlab_current_owner)"
+        owner="$(___x_cmd_gl_current_owner)"
     fi
 }
 
-___x_cmd_gitlab_default(){
+___x_cmd_gl_default(){
     param_default "$@" 2>/dev/null || return 1
 }
 
@@ -116,7 +116,7 @@ _____x_cmd_git_repo(){
     repo="${repo%.*}"
     printf "%s" "$repo"
 }
-___gitlab_ui_mutual(){
+___gl_ui_mutual(){
     if [ ! -t 1 ] || [ -n "$ENFORCE_JSON" ] ; then
         "$@"
     else
@@ -124,7 +124,7 @@ ___gitlab_ui_mutual(){
         eval "$(cat)"
     fi
 
-    local ___gitlab_exit_code="$?"
-    [ "$___gitlab_exit_code" -eq 0 ] || gitlab_log error "${___gitlab_error_msg:-"Couldn't find any data"}"
-    return "$___gitlab_exit_code"
+    local ___gl_exit_code="$?"
+    [ "$___gl_exit_code" -eq 0 ] || gl_log error "${___gl_error_msg:-"Couldn't find any data"}"
+    return "$___gl_exit_code"
 }
diff --git a/mod/yanfa/lib/pkg b/mod/yanfa/lib/pkg
--- a/mod/yanfa/lib/pkg
+++ b/mod/yanfa/lib/pkg
@@ -1,124 +1,225 @@
 # shellcheck shell=sh disable=SC3043
 
-# Section: module add pull update
-___x_cmd_yanfa_pkg_add(){
-    local name="${1:?Provide module name}"
-    local position="${2:-"git@$(___x_cmd_yanfa_git_domain):x-bash/$name.git"}"
-    # local position="${2:-"https://$(___x_cmd_yanfa_git_domain)/x-bash/$name.git"}"
-    local branch="${3:-main}"
-    git subtree add --prefix="mod/$name" "$position" "$branch" --squash
-}
-
-___x_cmd_yanfa_pkg_pull(){
-    param:void
-    local name="${1:?Provide module name}"
-    local position="${2:-"git@$(___x_cmd_yanfa_git_domain):x-bash/$name.git"}"
-    # local position="${2:-"https://$(___x_cmd_yanfa_git_domain)/x-bash/$name.git"}"
-    local branch="${3:-main}"
-    git subtree pull --prefix="mod/$name" "$position" "$branch" --squash
-}
-
-___x_cmd_yanfa_pkg_update_main0(){
-    local mod="$1"
-    if [ -e "mod/$mod" ]; then
-        ___x_cmd_yanfa_pkg_pull "$mod"
-    else
-        ___x_cmd_yanfa_pkg_add "$mod"
+# Section: main
+___x_cmd_yanfa_pkg(){
+    if [ -f "$(x wsroot)/.x-cmd/$1" ]; then
+        x _ws "$@"
+        return
     fi
+
+    x:trace yanfa/relesae "$@"
+
+    param:subcmd    ___x_cmd_yanfa                  \
+        init        "init"
+    param:subcmd:try
+
+    param:subcmd    ___x_cmd_yanfa_ws               \
+        pull        "pull"                          \
+        push        "push"                          \
+        name        "get workspace name from git config"
+    param:subcmd:try
+
+    param:subcmd    ___x_cmd_yanfa_pkg          \
+        update          "update or add module"      \
+        pub             "publish the package"       \
+        lsmod           "ls module"                 \
+        lsfile          "ls file"                   \
+        wc              "count"                     \
+        tgz             "compress modules of core/all/<special-release> into <name>.tgz"    \
+        7z              "compress modules of 7z"
+    param:subcmd:try
+
+    param:run
+    ___x_cmd_yanfa_pkg help
 }
+# EndSection
 
-___x_cmd_yanfa_pkg_update0(){
-    param:void
-    local IFS
-    local mod
-    git prune
+___x_cmd_run_or_fail(){
+    local start_msg="${1:?Provide start msg}"
+    local fail_msg="${2:?Provide failure msg}"
+    shift 2
 
-    ___x_cmd_yanfa_pkg_lsmod "$@" | \
-    while read -r mod; do
-        ___x_cmd_yanfa_pkg_update_main0 "$mod"
-    done
-}
-
-___x_cmd_yanfa_pkg_update_main(){
-    local mod="$1"
-    if [ -e "mod/$mod" ]; then
-        printf "%s\n" "Pull: $mod"
-        ___x_cmd_yanfa_pkg_pull "$mod"
+    yanfa:debug "$start_msg"
+    "$@"
+    local code=$?
+    if [ "$code" -eq 0 ]; then
+        yanfa:debug "Exit=$code. Success"
     else
-        printf "%s\n" "Add: $mod"
-        ___x_cmd_yanfa_pkg_add "$mod"
-    fi 1>"$TMPDIR/$mod.out" 2>&1
-    printf "Write: %s\n" "$TMPDIR/$mod.out"
+        yanfa:debug "Exit=$code: $fail_msg"
+    fi
+    return "$code"
 }
+
+# Section: pub
+___x_cmd_yanfa_pkg_pub()(
+    param:void
+    x:trace yanfa/relesae/pub
+    # set -o errexit
+    if  ___x_cmd_run_or_fail "Start update"             "Update fail."              ___x_cmd_yanfa_pkg_update   "${CONCURRENCY:-7}" && \
+        ___x_cmd_run_or_fail "Start CPFILE"             "CPFILE fail."              ___x_cmd_yanfa_pkg_cpfile   "${CONCURRENCY:-7}" && \
+        ___x_cmd_run_or_fail "Start Generate Meta"      "Generate Meta fail."       ___x_cmd_yanfa_pkg_meta     "${CONCURRENCY:-7}" && \
+        ___x_cmd_run_or_fail "Start tgz"                "tgz fail."                 ___x_cmd_yanfa_pkg_tgz                          && \
+        ___x_cmd_yanfa_upload ;
+    then
+        yanfa:info "OK"
+    else
+        yanfa:error "Fail"
+        return 1
+    fi
+)
+# EndSection
+
+# Section: module add pull update
+
+___X_CMD_YANFA_PKG_TMP="${TMPDIR%/}/release/mod"
+
+___x_cmd_yanfa_pkg_add()(
+    x:trace yanfa/relesae/add "[name=$1]" "[position=$2]" "[branch=$branch]"
+    local name="${1:?Provide module name}"
+    local position="${2:-"git@$(___x_cmd_yanfa_git_domain):x-bash/$name.git"}"
+    # local position="${2:-"https://$(___x_cmd_yanfa_git_domain)/x-bash/$name.git"}"
+    local branch="${3:-main}"
+
+    cd "$___X_CMD_YANFA_PKG_TMP" || exit 1
+
+    local i=1
+    while [ "$i" -le "${RETRY:-3}" ]; do
+        if git clone --quiet --depth=1 "$position" -b "$branch"; then
+            yanfa:info "[$mod/$branch] Cloning success from $position"
+            exit 0
+        fi
+        yanfa:info "[$mod/$branch] Fail to git clone. Retry it after 5 seconds."
+        if ! sleep 5; then
+            yanfa:warn "Sleep interrupted."
+        fi
+        i=$((i+1))
+    done
+    yanfa:error "[$mod/$branch] Fail to git clone after 3 attemps. Mission abort."
+    exit 1
+)
 
 ___x_cmd_yanfa_pkg_update(){
     param:void
-    local IFS
-    local mod
-    git prune
 
-    ___x_cmd_yanfa_pkg_lsmod "$@" | {
-        while read -r mod; do
-            # OUT=/dev/null
-            x job put 7 ___x_cmd_yanfa_pkg_update_main "$mod"
-            printf "%s\n" "Update: $mod" >&2
+    x:trace yanfa/relesae/update
+
+    local ___X_CMD_YANFA_CONCURRENCY="${1:-$___X_CMD_YANFA_CONCURRENCY}"
+    local IFS=" "; yanfa:info "[concurrency=$___X_CMD_YANFA_CONCURRENCY]: $*"
+
+    x rmrf "$___X_CMD_YANFA_PKG_TMP"
+    x mkdirp "$___X_CMD_YANFA_PKG_TMP"
+
+    local ___X_CMD_JOB_WRAPPER=log # report
+    ___x_cmd_yanfa_pkg_lsmod | {
+        local mod; while read -r mod; do
+            x job put "${1:-7}" ___x_cmd_yanfa_pkg_add "$mod"
         done
-
-        x job wait
-    } | while read -r line; do
-        printf "%s\n" "$line"
-        case "$line" in
-            Write*)
-                printf "%s\n" "---------------"
-                cat "${line#Write: }"
-                printf "%s\n" "---------------"
-        esac
-    done
+    } | cat # x job report
 }
 
 # EndSection
 
 # Section: information
 
+# shellcheck disable=SC2120
 ___x_cmd_yanfa_pkg_lsmod(){
     param:void
+    x:trace yanfa/relesae/lsmod "$@"
     ___x_cmd_yanfa_mod_ls "$@"
+    local code=$?
+    yanfa:debug "___x_cmd_yanfa_pkg_lsmod: $code"
+    return $code
 }
 
 ___x_cmd_yanfa_pkg_lsfile()(
     param:void
-    cd "$(x wsroot)/mod" || return
+    x:trace yanfa/relesae/lsfile
+    [ -d "$___X_CMD_YANFA_PKG_TMP" ] || return 1
 
-    ___x_cmd_yanfa_pkg_lsmod "$@" | (
-        cd "$(x wsroot)/mod" && \
+    ___x_cmd_yanfa_pkg_lsmod | (
+        cd "$___X_CMD_YANFA_PKG_TMP" && \
         while read -r line; do
-            ( cd "$line" && ___x_cmd_yanfa_mod_lsfile | x arg1 'printf "%s/%s\n" "$line" "$1"' )
+            (
+                if ! cd "$line"; then
+                    yanfa:error "___x_cmd_yanfa_pkg_lsfile while-loop: fail to cd - $line"
+                    exit 1
+                fi
+                ___x_cmd_yanfa_mod_lsfile | x arg1 'printf "%s/%s\n" "$line" "$1"'
+            )
         done
     )
+
+    local code=$?
+    yanfa:info "___x_cmd_yanfa_pkg_lsfile"
+    return $code
 )
 
-___x_cmd_yanfa_pkg_install()(
-    param:void
-    cd "$(x wsroot)/mod" || return
+___x_cmd_yanfa_pkg_cpfile_inner(){
+    # x:trace yanfa/relesae/cpfile/inner        # Use debug
+    if [ -d "$2" ]; then
+        local p="$2/$1"
+        if ! x cp "$1" "$p"; then
+            yanfa:info "fail to cp [src=$1] to [dst=$p]"
+        fi
+    else
+        if ! x cp "$1" "$2"; then
+            yanfa:info "fail to cp [src=$1] to [dst=$2]"
+        fi
+    fi
+}
 
-    ___x_cmd_yanfa_pkg_lsmod "$@" | (
-        cd "$(x wsroot)/mod" && \
+___x_cmd_yanfa_pkg_cpfile(){
+    x:trace yanfa/relesae/cpfile
+    local tgt
+    tgt="$(x wsroot)/mod"
+    yanfa:debug "Staring cpfile: tgt=$tgt"
+
+    x rmrf "$tgt"; x mkdirp "$tgt"
+
+    ___x_cmd_yanfa_pkg_lsfile | (
+        cd "$___X_CMD_YANFA_PKG_TMP"
         while read -r line; do
-            ( cd "$line" && ___x_cmd_yanfa_mod_install )
+            ___x_cmd_yanfa_pkg_cpfile_inner "$line" "${tgt}"
+            local code=$?; yanfa:debug "<release_cpfile> $line => $tgt: $code"
         done
     )
-)
+    # TODO: In Github Action, it return 1. Resulting in breaking. cpfile_inner is OK. The bug might be in while pipe.
+    yanfa:debug "exit: $?"
+}
+
+___x_cmd_yanfa_pkg_meta(){
+    local tgt
+    tgt="$(x wsroot)/mod"
+
+    local mod
+    ___x_cmd_yanfa_pkg_lsmod | while read -r mod; do
+        (
+            x cd "$___X_CMD_YANFA_PKG_TMP/$mod" || exit 1
+            local id; id=$(x git meta id)
+            local branch; branch=$(x git meta branch);  branch="${branch:-NULL}"
+            local tag; tag=$(x git meta tag);           tag="${tag:-NULL}"
+
+            printf "%s %s %s %s\n" "$id" "$mod" "$branch" "$tag"
+        )
+    done >"$tgt/mod.txt"
+
+    {
+        printf "md5:%s\n" "$(x md5 "$tgt/repo.txt")"
+        printf "sha256:%s\n" "$(x sha256 "$tgt/repo.txt")"
+        printf "sha512:%s\n" "$(x sha512 "$tgt/repo.txt")"
+    } >"$tgt/hashsum.txt"
+}
 
 ___x_cmd_yanfa_pkg_wc(){
     param:void
+    x:trace yanfa/relesae/wc
     cd "$(x wsroot)/mod" &&
         ___x_cmd_yanfa_pkg_lsfile "$@" | xargs wc | sort -n -r | less
 }
 
 # EndSection
 
-# Section: tgz tar 7z
-
+# Section: tgz
 ___x_cmd_yanfa_pkg_tgz()(
     param:void
     case "${1:-all}" in
@@ -127,91 +228,42 @@ ___x_cmd_yanfa_pkg_tgz()(
         *)          return 1 ;;
     esac
 
+    local WSROOT
     WSROOT="$(x wsroot)"
 
-    cd "$WSROOT/mod" &&
-    mkdir -p "$WSROOT/dist" &&
-        eval "tar czvf $scope.tgz $(___x_cmd_yanfa_pkg_lsfile "$scope" | sort | uniq | tr '\n' ' ')" &&
-        mv $scope.tgz "$WSROOT/dist/$scope.tgz" &&
-        ls -alh "$WSROOT/dist/$scope.tgz"
-)
-
-___x_cmd_yanfa_pkg_tar()(
-    param:void
-    case "${1:-all}" in
-        core)       scope=core ;;
-        all)        scope=all ;;
-        *)          return 1 ;;
-    esac
-
-    WSROOT="$(x wsroot)"
-
-    cd "$WSROOT/mod" &&
-    mkdir -p "$WSROOT/dist" &&
-        eval "tar cvf $scope.tar $(___x_cmd_yanfa_pkg_lsfile "$scope" | sort | uniq | tr '\n' ' ')" &&
-        mv $scope.tar "$WSROOT/dist/$scope.tar" &&
-        ls -alh "$WSROOT/dist/$scope.tar"
-)
-
-___x_cmd_yanfa_pkg_7z()(
-    param:void
-    case "${1:-all}" in
-        core)       scope=core ;;
-        all)        scope=all ;;
-        *)          return 1 ;;
-    esac
-
-    WSROOT="$(x wsroot)"
-
-    cd "$WSROOT/mod" &&
-    mkdir -p "$WSROOT/dist" &&
-        eval "7z a $WSROOT/dist/all.7z $(___x_cmd_yanfa_pkg_lsfile "$scope" | sort | uniq | tr '\n' ' ')" &&
-        mv $scope.7z "$WSROOT/dist/$scope.7z" &&
-        ls -alh "$WSROOT/dist/$scope.7z"
-)
-
-# EndSection
-
-___x_cmd_yanfa_pkg_pub0(){
-    param:void
-    ___x_cmd_yanfa_pkg_update0 "$@" && ___x_cmd_yanfa_pkg_tgz "$@" && git add . && git commit -m ...
-    ___x_cmd_yanfa_ws_push
-}
-
-___x_cmd_yanfa_pkg_pub(){
-    param:void
-    ___x_cmd_yanfa_pkg_update "$@" && ___x_cmd_yanfa_pkg_tgz "$@" && git add . && git commit -m ...
-    ___x_cmd_yanfa_ws_push
-}
-
-___x_cmd_yanfa_pkg(){
-    if [ -f "$(x wsroot)/.x-cmd/$1" ]; then
-        x ws execfile "$@"
-        return
+    x rmrf "$scope.tgz"
+    local code=$?
+    if [ "$code" = 0 ]; then        yanfa:debug "Cleaning up success[Exit=$code]: $scope.tgz"
+    else                            yanfa:warn  "Cleaning up Fail[Exit=$code]: $scope.tgz"
     fi
 
-    param:subcmd ___x_cmd_yanfa                                 \
-        init            "init"
-    param:subcmd:try
+    cd "$WSROOT/mod" &&
+        x z "$scope.tgz" . 2>/dev/null &&
+        x mv "$scope.tgz" "$WSROOT/dist/$scope.tgz"
 
-    param:subcmd ___x_cmd_yanfa_ws                              \
-        pull            "pull"                                  \
-        push            "push"                                  \
-        name            "get workspace name from git config"
-    param:subcmd:try
+    local code="$?"
+    if [ "$code" = 0 ]; then
+        ls -alh "$WSROOT/dist/$scope.tgz"
+    else
+        yanfa:error "Failure at yanfa zip and mv"
+        return "$code"
+    fi
+)
+# EndSection
 
-    param:subcmd ___x_cmd_yanfa_pkg                             \
-        install         "install all modules"                   \
-        update          "update or add module"                  \
-        pub0            "publish the package"                   \
-        pub             "publish the package"                   \
-        lsmod           "ls module"                             \
-        lsfile          "lsfile"                                \
-        wc              "count"                                 \
-        tgz             "compress modules of core/all/<special-release> into <name>.tgz" \
-        tar             "compress modules"                      \
-        7z              "compress modules of 7z"
-    param:subcmd:try
+___x_cmd_yanfa_upload(){
+    local id=2
+    x ui select id "Do you want to commit and push?" "Yes" "No"
 
-    param:run
+    if [ "$id" = 2 ]; then
+        yanfa:info "No Upload. Skip Add && Commit && Push"
+    else
+        yanfa:info "Add && Commit && Push"
+        git add . && git commit -m ... && ___x_cmd_yanfa_ws_push;
+        local code=$?
+        if [ "$code" = 0 ]; then            yanfa:info "Success"
+        else                                yanfa:error "Add && Commit && Push exit: $code"
+        fi
+        return "$code"
+    fi
 }
