Squashed 'mod/hub/' changes from d492891..daa27c4
daa27c4 refactor(main): update official site register
09dafd0 refactor(main): update
dfbe1a2 refactor(main): update official site login
f48ed27 refactor(main): use ___x_cmd_httpget log
407fc79 refactor(main): format code
c807596 feat(wechat): update Interaction
2996613 feat(main): ___x_cmd_hub_login_weixin_qr and ___x_cmd_hub_login_user
222615b fix(register): add ___x_cmd_hub_token "${TOKEN_TO_ACTIVATE}"

git-subtree-dir: mod/hub
git-subtree-split: daa27c42511e3f2d02c56b4e8e88d9a8a9ff7e29

diff --git a/lib/account b/lib/account
--- a/lib/account
+++ b/lib/account
@@ -2,7 +2,7 @@
 
 xrc http
 
-# Section: utils
+# Section(utils): ___x_cmd_hub_token_generate, ___x_cmd_hub_get_and_save_userinfo_by_token
 
 if command -v md5sum; then
     ___x_cmd_hub_token_md5(){
@@ -32,7 +32,27 @@ ___x_cmd_hub_token_generate(){
 
 # EndSection
 
-# Section: env
+# Section: qrcode
+
+___x_cmd_hub_print_qrcode(){
+    x qr enc -s 1 -m 3 -t ANSIUTF8 "$1"
+    hub_log debug "QR Code url: $1"
+}
+
+___x_cmd_hub_wechat_register_url(){
+    local token_to_activate="${1:?provide token_to_activate}"
+    local username="${2:?provide username}"
+    printf "%s" "${___X_CMD_HUB_WECHAT_AUTHORIZE_URL_PREFIX}r%3Fu%3D${username}&response_type=code&scope=snsapi_userinfo&state=${token_to_activate}#wechat_redire"
+}
+
+___x_cmd_hub_wechat_login_url(){
+    local token_to_activate="${1:?provide token_to_activate}"
+    printf "%s" "${___X_CMD_HUB_WECHAT_AUTHORIZE_URL_PREFIX}l&response_type=code&scope=snsapi_userinfo&state=${token_to_activate}#wechat_redire"
+}
+
+# EndSection
+
+# Section(env): ___x_cmd_hub_login_user, ___x_cmd_hub_token, ___x_cmd_hub_get_and_save_userinfo_by_token
 
 ___x_cmd_hub_login_user(){
     cat "$___X_CMD_HUB_ENV/.me" 2>/dev/null
@@ -47,21 +67,41 @@ ___x_cmd_hub_token(){
         return
     fi
 
-    if [ "$1" = "${1#*/}" ]; then
-        printf "%s" "${1%/*}" > "$___X_CMD_HUB_ENV/.me"
-        printf "%s" "${1#*/}" > "$___X_CMD_HUB_ENV/.token"
+    if [ "$1" != "${1#*/}" ]; then
+        hub_log debug "userid: ${1%/*}, token: ${1##*/}"
+        printf "%s" "${1%/*}"  > "$___X_CMD_HUB_ENV/.me"
+        printf "%s" "${1##*/}" > "$___X_CMD_HUB_ENV/.token"
         return
     fi
 
-    local res
-    if res=$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/token/info/email?token=$(___x_cmd_hub_token)"); then
-        printf "%s" "$res" > "$___X_CMD_HUB_ENV/.me"
-        printf "%s" "$1" > "$___X_CMD_HUB_ENV/.token"
-    fi
+    # TODO
+    # local res
+    # if res=$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/token/info/email?token=$(___x_cmd_hub_token)"); then
+    #     printf "%s" "$res" > "$___X_CMD_HUB_ENV/.me"
+    #     printf "%s" "$1" > "$___X_CMD_HUB_ENV/.token"
+    # fi
 }
 
+___x_cmd_hub_get_and_save_userinfo_by_token(){
+    local token="${1:?Please provide token}"
+
+    local res
+    if ! res="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/account/user?token=${token}")" ; then
+        hub_log error "Failed to get userinfo by token: $res"
+        return 1
+    fi
+    hub_log debug "response: ${res}"
+
+    local userid
+    local username
+    userid="$(printf "%s" "$res" | x jq -r '.id')"
+    username="$(printf "%s" "$res" | x jq -r '.username')"
+    ___x_cmd_hub_token "${userid}/${token}"
+    printf "%s\n" "${username} ${userid}"
+}
 
 # EndSection
-. "$___X_CMD_ROOT/ui/lib/select"
-. "$___X_CMD_ROOT/hub/lib/account_login"
-. "$___X_CMD_ROOT/hub/lib/account_registration"
+
+
+___x_cmd_source_inner_lib ui select
+___x_cmd_source_inner_lib hub account_login account_registration
diff --git a/lib/account_login b/lib/account_login
--- a/lib/account_login
+++ b/lib/account_login
@@ -10,26 +10,27 @@ ___x_cmd_hub_login(){
         "")
                 ___x_cmd_ui_select "_SELECT" \
                     "Login Methods:" \
+                        "Open Browser to x-cmd.com" \
                         "Login With Weixin QR" \
                         "Login With Email Verification"
-                        # "Open Browser to x-cmd.com" \    # To set the first case
                         # "Login With Telegram QR" \
                         # "Login With OneTime Password"    # SMS, Telegram, Email, Weixin
 
+                # TODO: Should move official site login to the first of the list
                 case "$_SELECT" in
-                    # 1)          ___x_cmd_hub_login_official_site "$@" ;;
                     # 2)          ___x_cmd_hub_login_telegram_qr "$@" ;;
-                    1)          ___x_cmd_hub_login_weixin_qr "$@" ;;
-                    2)          ___x_cmd_hub_login_email "$@" ;;
+                    1)          ___x_cmd_hub_login_official_site "$@" ;;
+                    2)          ___x_cmd_hub_login_weixin_qr     "$@" ;;
+                    3)          ___x_cmd_hub_login_email         "$@" ;;
                     *)          ;;
                 esac
                 ;;
         *)
-                ___x_cmd_hub_login_official_site ;;
+                ___x_cmd_hub_login_official_site "$@" ;;
     esac
 }
 
-# Section: telegram weixin
+# Section: telegram, weixin, official_site
 
 ___x_cmd_hub_login_telegram_qr(){
     local TOKEN_TO_ACTIVATE
@@ -40,33 +41,42 @@ ___x_cmd_hub_login_telegram_qr(){
 }
 
 ___x_cmd_hub_login_weixin_qr(){
-    local TOKEN_TO_ACTIVATE
-    TOKEN_TO_ACTIVATE="$(___x_cmd_hub_token_generate)"
-    ___x_cmd_hub_token "${TOKEN_TO_ACTIVATE}"
+    local token_to_activate
+    token_to_activate="$(___x_cmd_hub_token_generate)"
 
-    ___x_cmd_hub_qrcode "$(___x_cmd_hub_wechat_login_url "$(___x_cmd_hub_token_generate)")"
+    ___x_cmd_hub_print_qrcode "$(___x_cmd_hub_wechat_login_url "${token_to_activate}")"
+    printf "Please scan the QR code above, then press [Enter] to continue: "
+    read -r _
 
-    local ok
-    if [ -z "$ok" ]; then
-        printf "%s" "Are you ok? [Y]: "
-        read -r ok
+    local userinfo
+    if userinfo="$(___x_cmd_hub_get_and_save_userinfo_by_token "${token_to_activate}")" ; then
+        hub_log info "Login Successfully, ${userinfo})"
+    else
+        hub_log error "Login Failed"
     fi
-
-    # echo x qrencode -t ANSI "https://....${TOKEN_TO_ACTIVATE}"
 }
 
 ___x_cmd_hub_login_official_site(){
-    if [ -n "$(___x_cmd_hub_token)" ]; then
-        # TODO: ask
-        printf "Detect token in this folder. Erase the token in the disk?" >&2
-        ___x_cmd_hub_token ""
+    # if [ -n "$(___x_cmd_hub_token)" ]; then
+    #     # TODO: ask
+    #     printf "Detect token in this folder. Erase the token in the disk?\n" >&2
+    #     ___x_cmd_hub_token ""
+    # fi
+
+    local token_to_activate
+    token_to_activate="$(___x_cmd_hub_token_generate)"
+
+    # TODO: to change xlogin to login
+    ___x_cmd_http_browse "$___X_CMD_HUB_SERVICE_URL/xlogin?token_to_activate=${token_to_activate}"
+    printf "Please login to hub.x-cmd.com, then press [Enter] to continue: "
+    read -r _
+
+    local userinfo
+    if userinfo="$(___x_cmd_hub_get_and_save_userinfo_by_token "${token_to_activate}")" ; then
+        hub_log info "Login Successfully, ${userinfo})"
+    else
+        hub_log error "Login Failed"
     fi
-
-    local TOKEN_TO_ACTIVATE
-    TOKEN_TO_ACTIVATE="$(___x_cmd_hub_token_generate)"
-    ___x_cmd_hub_token "$TOKEN_TO_ACTIVATE"
-
-    echo ___x_cmd_http_browse "$___X_CMD_HUB_SERVICE_URL/login?token_to_activate=${TOKEN_TO_ACTIVATE}"
 }
 
 # EndSection
@@ -76,8 +86,7 @@ ___x_cmd_hub_login_email_witharg(){
     local email="${1:?Provide email}"
 
     local result
-    result="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/account/login/$email" 2>/dev/null)"
-    # printf "Result: %s\n" "$result" >&2
+    result="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/account/login/$email")"
     if [ "${result#ERR=}" = "$result" ]; then
         printf "%s\n" "Please check your email to approve this visit: $email" >/dev/stderr
     else
@@ -105,7 +114,7 @@ ___x_cmd_hub_verify(){
     printf "%s" "Code: "
     read -r code
 
-    result="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/account/verify/$email/$code" 2>/dev/null)"
+    result="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/account/verify/$email/$code")"
 
     local token="${result#TOKEN=}"
     if [ "$token" != "$result" ]; then
diff --git a/lib/account_registration b/lib/account_registration
--- a/lib/account_registration
+++ b/lib/account_registration
@@ -9,26 +9,54 @@ ___x_cmd_hub_register(){
         "")
                 ___x_cmd_ui_select "_SELECT" \
                     "Register Methods:" \
+                        "Open Browser to x-cmd.com" \
                         "Weixin QR" \
-                        # "Open Browser to x-cmd.com" \
+                        "Email Verification"
                         # "Telegram Bot"
 
+                # TODO: Should move official site login to the first of the list
                 case "$_SELECT" in
-                    # 1)          ___x_cmd_hub_register_official_site "$@" ;;
-                    1)          ___x_cmd_hub_register_weixin "$@" ;;
-                  # 3)          ___x_cmd_hub_register_telegram "$@" ;;
+                    1)          ___x_cmd_hub_register_official_site "$@" ;;
+                    2)          ___x_cmd_hub_register_weixin        "$@" ;;
+                    3)          ___x_cmd_hub_register_email         "$@" ;;
+                    4)          ___x_cmd_hub_register_telegram      "$@" ;;
                     *)          ;;
                 esac
                 ;;
         *)
-                ___x_cmd_hub_register_official_site ;;
+                ___x_cmd_hub_register_official_site "$@" ;;
     esac
 }
 
 # Section: Registration
 
 ___x_cmd_hub_register_official_site(){
-    ___x_cmd_http_browse "$___X_CMD_HUB_SERVICE_URL/register"
+
+    local username="${1}"
+    if [ -z "$username" ]; then
+        printf "%s" "Username: "
+        read -r username
+    fi
+
+    if [ -n "$(___x_cmd_hub_token)" ]; then
+        # TODO: ask
+        printf "Detect token in this folder. Erase the token in the disk?" >&2
+        ___x_cmd_hub_token ""
+    fi
+
+    local token_to_activate
+    token_to_activate="$(___x_cmd_hub_token_generate)"
+
+    ___x_cmd_http_browse "$___X_CMD_HUB_SERVICE_URL/xlogin?token_to_activate=${token_to_activate}&username=${username}"
+    printf "Please register to hub.x-cmd.com, then press [Enter] to continue: "
+    read -r _
+
+    local userinfo
+    if userinfo="$(___x_cmd_hub_get_and_save_userinfo_by_token "${token_to_activate}")" ; then
+        hub_log info "Register Successfully, ${userinfo})"
+    else
+        hub_log error "Register Failed"
+    fi
 }
 
 ___x_cmd_hub_register_weixin(){
@@ -38,13 +66,17 @@ ___x_cmd_hub_register_weixin(){
         read -r username
     fi
 
-    ___x_cmd_hub_qrcode "$(___x_cmd_hub_wechat_register_url "$(___x_cmd_hub_token_generate)" "$username")"
+    local token_to_activate
+    token_to_activate="$(___x_cmd_hub_token_generate)"
+    ___x_cmd_hub_print_qrcode "$(___x_cmd_hub_wechat_register_url "${token_to_activate}" "$username")"
+    printf "%s" "Please scan the QR code above, then press [Enter] to continue: "
+    read -r _
 
-    # ___x_cmd_httpget_gitx x-cmd x-cmd main "lib/resource/qrcode/weixin" "" -
-    local ok
-    if [ -z "$ok" ]; then
-        printf "%s" "Are you ok? [Y]: "
-        read -r ok
+    local userinfo
+    if userinfo="$(___x_cmd_hub_get_and_save_userinfo_by_token "${token_to_activate}")" ; then
+        hub_log info "Register Successfully, ${userinfo}"
+    else
+        hub_log error "Register Failed"
     fi
 }
 
@@ -60,7 +92,7 @@ ___x_cmd_hub_register_email(){
     fi
 
     local result
-    result="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/account/register/$email" 2>/dev/null)"
+    result="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/account/register/$email")"
     local msg="${result#ERR=}"
 
     if [ "$msg" = "$result" ]; then
