Squashed 'mod/gt/' changes from 3631dc77..ec9d630b
ec9d630b style: update types UpperCase
4db1e69d feat(issue): done issue import ui
ec03b8b5 feat(config): update config setup of yml awk
c48eb00b feat(command): add command printf log to repo repo_member
20568284 feat(select): replace select to form for confirm del and clear repo

git-subtree-dir: mod/gt
git-subtree-split: ec9d630b3b5747936b835d9b394efd24327047c8

diff --git a/lib/config b/lib/config
--- a/lib/config
+++ b/lib/config
@@ -5,8 +5,8 @@ ___x_cmd_gt_config(){
     param:dsl       '
 subcmd:
     which       "Show current config path"
-    save        "Save the config in memory into file"
-    load        "Load the config from config path"
+    get         "Print the value of a given configuration key"
+    set         "Update configuration with a value for the given key"
 '
     param:run
     if [ -z "$PARAM_SUBCMD" ]; then
@@ -24,25 +24,35 @@ ___x_cmd_gt_config_which() {
     printf "%s" "$HOME/.x-cmd/.config/x-bash/app.gitee.config/$O"
 }
 
-# TODO:config
-___x_cmd_gt_config_save() {
-    param:void
+___x_cmd_gt_config_get() {
+    param:scope     "gitee/$O"
+    param:dsl       '
+type:
+    ConfigName  =   oauth_token user git_protocol
+options:
+    --host        "host name"                               <>="gitee.com"
+    #1            "The name of the configuration to get"    <>:ConfigName
+'
+    param:run
     local O="${O:-GITEE_DEFAULT}"
-    local ___gitee_path="${1:-$HOME/.x-cmd/.config/x-bash/app.gitee.config/$O}"
-    [ ! -e "$___gitee_path" ] && mkdir -p "$___gitee_path##*/"
-    ___x_cmd_gt_default dump "gitee_$O">"$___gitee_path" && ___x_cmd_ui tf "true" \
-    "$(ui bold "Config $O saved in path:") $(ui yellow underline "$___gitee_path")" && return 0
-    gt_log error "gt config save Fail"
+    [ -e  "$HOME/.x-cmd/.config/x-bash/app.gitee.config/$O" ] || return 1
+    ___x_cmd_git_config_get "$HOME/.x-cmd/.config/x-bash/app.gitee.config/$O" "$host" "$1"
 }
 
-# shellcheck disable=SC2120
-___x_cmd_gt_config_load() {
-    param:void
+___x_cmd_gt_config_set() {
+    param:scope     "gitee/$O"
+    param:dsl       '
+type:
+    ConfigName  =   oauth_token user git_protocol
+options:
+    --host    "host name"                             <>="gitee.com"
+    #1        "Please provide configuration key"      <>:ConfigName
+    #2        "Please provide configuration val"      <>
+'
+    param:run
     local O="${O:-GITEE_DEFAULT}"
-    local ___gitee_path="${1:-$HOME/.x-cmd/.config/x-bash/app.gitee.config/$O}"
-    [ ! -f "$___gitee_path" ] && gt_log warn "There is no history config" && return
-    ___x_cmd_gt_default load "gitee_$O" "$___gitee_path"
-    local token
-    token="$(___x_cmd_gt_default get "gitee_$O" token)"
-    http "@___x_cmd_gt_${O:-GITEE_DEFAULT}" header put Authorization "token $token"
+    local ___gitee_path="$HOME/.x-cmd/.config/x-bash/app.gitee.config/$O"
+    [ -e  "$___gitee_path" ] || mkdir -p "$___gitee_path##*/"
+    ___x_cmd_git_config_set "$___gitee_path" "$host" "$1" "$2" && ___x_cmd_ui_tf "true" "set config successfully" && return 0
+    gh_log error "gh config set Fail"
 }
diff --git a/lib/issue b/lib/issue
--- a/lib/issue
+++ b/lib/issue
@@ -26,14 +26,15 @@ subcmd:
 }
 
 
+# shellcheck disable=SC2154
 ___x_cmd_gt_issue_create() {
     param:scope     "gitee/$O"
     param:dsl      '
 options:
     --owner         "owner"                         <>
     --title         "title"                         <>
-    --body          "issue describe"                <>=""
     --repo          "repo path"                     <>
+    --body          "issue describe"                <>=""
     --type          "issue type"                    <>=""
     --assignee      "assignee space address"        <>=""
     --collaborators "collaborators space address"   <>=""
@@ -44,19 +45,27 @@ options:
 '
     security=${security:-false}
     param:run
-    ______x_cmd_gt_post_json "/v5/repos/${owner##*/}/issues" repo=$repo title issue_type=$type body assignee \
-        collaborators milestone labels program security_hole=$security
+    
+    local data
+    data="$(______x_cmd_gt_post_json "/v5/repos/${owner##*/}/issues" repo="$repo" title issue_type="$type" body assignee \
+        collaborators milestone labels program security_hole="$security" || return 1)"
+    ___x_cmd_gt_json_query_rename "$data" id=.number title=.title html_url=.html_url
+    [ -n "$id" ] && ___x_cmd_ui tf "true" "Success" "id: $id" "title: $title" "url: $html_url" && return 0
+                    gt_log        "error" "Create issue failure"                               && return 1
 }
 
+# shellcheck disable=SC2154
 ___x_cmd_gt_issue_update() {
     param:scope     "gitee/$O"
     param:dsl       '
+type:
+    State = open progressing closed
 options:
     --owner         "owner"                         <>
+    --repo          "repo path"                     <>
     --number        "issue number"                  <>
-    --repo          "repo path"                     <>=""
     --title         "title"                         <>=""
-    --state         "issue state"                   <>=""
+    --state         "issue state "                  <>:State
     --body          "issue describe"                <>=""
     --assignee      "assignee space address"        <>=""
     --collaborators "collaborators space address"   <>=""
@@ -67,8 +76,13 @@ options:
 '
     param:run
     security=${security:-false}
-    ______x_cmd_gt_patch_json "/v5/repos/${owner##*/}/issues/${number}" repo title state body assignee \
-        collaborators milestone labels program security_hole=$security
+    
+    local data
+    data="$(______x_cmd_gt_patch_json "/v5/repos/${owner##*/}/issues/${number}" repo title state body assignee \
+        collaborators milestone labels program security_hole="$security" || return 1)"
+    ___x_cmd_gt_json_query_rename "$data" id=.number state=.state html_url=.html_url
+    [ -n "$id" ] && ___x_cmd_ui tf "true" "Success" "id: $id" "state: $state" "url: $html_url" && return 0
+                    gt_log        "error" "Update issue failure"                               && return 1
 }
 
 ___x_cmd_gt_issue_logs(){
@@ -81,21 +95,21 @@ options:
     --sort          "sort(asc、desc)"       <>="desc"
 '
     param:run
-    ______x_cmd_gt_get "/v5/repos/${owner##*/}/issues/${number}/operate_logs" repo sort
+    ___ui_table_json "$(printf "%s" "O=$O ______x_cmd_gt_get \"/v5/repos/${owner##*/}/issues/${number}/operate_logs\" repo sort || return 1" )" \
+            time=.created_at user=.user.login type=.action_type content=.content  && return 0
 }
 
 # shellcheck shell=sh
 # shellcheck disable=SC2039,3043,SC2154
 
-# schedule、deadline、created_at、finished_at 用UI来处理
 ___x_cmd_gt_repo_issue() {
     param:scope     "gitee/$O"
     param:dsl       '
 type:
-    state = open progressing closed rejected all
+    State = open progressing closed rejected all
 options:
     --repo          "Repo name"                 <>
-    --state         "issue state"               <>:state=all
+    --state         "issue state"               <>:State=all
     --labels        "labels"                    <>=""
     --milestone     "milestone"                 <>=""
     --assignee      "assignee"                  <>=""
@@ -175,11 +189,12 @@ subcmd:
     ls              "list all comment"
     create          "create a comment"
     update          "update a comment"
-    delete          "delete a comment"
+    del             "delete a comment"
 '
     param:run
     if [ -z "$PARAM_SUBCMD" ]; then
         gt_log warn "subcmd not found. show help." >&2
+        ___x_cmd_gt_issue _param_help_doc
         return 1
     fi
     "___x_cmd_gt_issue_comment_$PARAM_SUBCMD" "$@"
@@ -199,9 +214,10 @@ options:
 '
     param:run
     ___ui_table_json "$(printf "%s" "______x_cmd_gt_get_multi \"/v5/repos/${owner##*/}/${repo##*/}/issues/$number/comments\" since page per_page order || return 1" )" \
-        IssueNumber=.target.issue.number Title=.target.issue.title User=.user.login body=.body && return 0
+        CommitId=.id IssueNumber=.target.issue.number Title=.target.issue.title User=.user.login body=.body && return 0
 }
 
+# shellcheck disable=SC2086,SC2154
 ___x_cmd_gt_issue_comment_create(){
     param:scope     "gitee/$O"
     param:dsl       '
@@ -209,35 +225,48 @@ options:
     --owner         "owner"                             <>
     --repo          "repo path"                         <>
     --number        "issue number"                      <>
-    --body          "The contents of the comment."      <>
+    --body          "The contents of the comment"       <>
 '
     param:run
-    ______x_cmd_gt_post_json "/v5/repos/${owner##*/}/${repo##*/}/issues/$number/comments"  body
+
+    local data
+    data="$(______x_cmd_gt_post_json "/v5/repos/${owner##*/}/${repo##*/}/issues/$number/comments" body || return 1)"
+    ___x_cmd_gt_json_query_rename "$data" id=.target.issue.number title=.target.issue.title body=.body
+    [ -n "$id" ] && ___x_cmd_ui tf "true" "Success" "id: $id" "title: $title" "comment_body: $body" && return 0
+                    gt_log        "error" "Create Comment failure"                                  && return 1
 }
 
 ___x_cmd_gt_issue_comment_update(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    --owner         "owner"                            <>
-    --repo          "repo path"                        <>
+    --owner         "owner"                             <>
+    --repo          "repo path"                         <>
     --id            "comments id"                       <>
-    --body          "The contents of the comment."      <>
+    --body          "The contents of the comment"       <>
 '
     param:run
-    ______x_cmd_gt_patch_json "/v5/repos/${owner##*/}/${repo##*/}/issues/comments/${id}"  body
+
+    local data
+    data="$(______x_cmd_gt_patch_json "/v5/repos/${owner##*/}/${repo##*/}/issues/comments/${id}" body || return 1)"
+    ___x_cmd_gt_json_query_rename "$data" id=.target.issue.number title=.target.issue.title body=.body
+    [ -n "$id" ] && ___x_cmd_ui tf "true" "Success" "id: $id" "title: $title" "comment_body: $body" && return 0
+                    gt_log        "error" "Update Comment failure"                                  && return 1
 }
 
-___x_cmd_gt_issue_comment_delete(){
+# shellcheck disable=SC2181
+___x_cmd_gt_issue_comment_del(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    --owner         "owner"                            <>
-    --repo          "repo path"                        <>
+    --owner         "owner"                             <>
+    --repo          "repo path"                         <>
     --id            "comments id"                       <>
 '
     param:run
-    ______x_cmd_gt_delete "/v5/repos/${owner##*/}/${repo##*/}/issues/comments/${id}"
+    ______x_cmd_gt_delete "/v5/repos/${owner##*/}/${repo##*/}/issues/comments/${id}" 1>/dev/null 2>&1
+    [ $? -eq 0 ] && ___x_cmd_ui tf "true" "Deleted comment successfully"                      && return 0
+                    gt_log error "Deleting comment failure by ${owner##*/} ${repo##*/} $id."  && return 1
 }
 
 # EndSection
diff --git a/lib/repo/main b/lib/repo/main
--- a/lib/repo/main
+++ b/lib/repo/main
@@ -7,12 +7,12 @@ ___x_cmd_gt_repo(){
 subcmd:
     create          "create repo"
     ls              "list repo of owner"
-    info            "Show detailed information of repo"
-    del             "Remove repo"
+    info            "show detailed information of repo"
+    del             "remove repo"
     clear           "clear repo"
     issue           "get repo issue"
+    review          "setup review repo configure"
 '
-    # TODO: add release: release  review: "review repo"
     param:run
     if [ -z "$PARAM_SUBCMD" ]; then
         gt_log warn "Subcmd Not Found."
@@ -45,9 +45,9 @@ ___x_cmd_gt_repo_create() {
     param:scope     "gitee/$O"
     param:dsl       '
 type:
-    access  =   private public
+    Access  =   private public
 option:
-    --access                "private,public"                <>:access=private
+    --access                "private,public"                <>:Access=private
     --description           "description"                   <>=""
     --homepage              "homepage"                      <>=""
     --no_issues             "Provide issue"
@@ -76,6 +76,7 @@ option:
     [ -n "$no_wiki" ] && has_wiki=false
     [ -n "$no_comment" ] && can_comment=false
     [ -n "$no_auto_init" ] && auto_init=false
+    # TODO: ___x_cmd_gt_printf_command_log
 
     [ $# -eq 0 ] && gt_log info "repo create name is null" && return
     local name
@@ -106,11 +107,11 @@ ___x_cmd_gt_org_repo_create() {
     param:scope     "gitee/$O"
     param:dsl       '
 type:
-    access  =   private public innerSource
+    Access  =   private public innerSource
 option:
     --org                   "organization create repo"      <>:name
     --description           "description"                   <>=""
-    --access                "private,public,innerSource"    <>:access=private
+    --access                "private,public,innerSource"    <>:Access=private
     --homepage              "homepage"                      <>:url_type=""
     --no_issues             "Provide issue"
     --no_wiki               "Provide wiki"
@@ -164,10 +165,10 @@ ___x_cmd_gt_enterprise_repo_create() {
     param:scope     "gitee/$O"
     param:dsl       '
 type:
-    access  =   private public innerSource
+    Access  =   private public innerSource
 option:
     --enterprise            "enterprise space address"          <>
-    --access                "private,public,innerSource"        <>:access=private
+    --Access                "private,public,innerSource"        <>:Access=private
     --description           "description"                       <>=""
     --homepage              "homepage"                          <>:url_type=""
     --paths                 "repo path"                         <>:url_type=""
@@ -246,22 +247,23 @@ ___x_cmd_gt_repo_info() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    #1|--repo          "Repo name"         <>:repo
+    #1|--repo          "Repo or Path(owner/repo)"         <>:repo
 '
     param:run
 
-    # TODO: FIX form not data. wait param debug
     # get owner_repo by repo
     ___x_cmd_gt_param_init_owner_repo
+    ___x_cmd_gt_printf_command_log "gt repo info -r $repo"
+
     local data
     data=$(______x_cmd_gt_get "/v5/repos/${owner_repo}" || return 1)
         ___x_cmd_gt_json_query_rename "$data" id=.id name=.name html_url=.html_url
     [ -n "$name" ] && ___x_cmd_ui tf "true" "Success" "id: $id" "name: $name" "url: $html_url" && return 0
-                      gt_log "error" "Fail. Couldn't find any repo: $repo"                     && return 1
+                      gt_log         "error" "Fail. Couldn't find any repo: $repo"             && return 1
 }
 
 # https://gitee.com/api/v5/swagger#/deleteV5ReposOwnerRepo
-# shellcheck disable=SC2181
+# shellcheck disable=SC2181,SC2154
 ___x_cmd_gt_repo_del() {
     # TODO: -y force del
     param:scope     "gitee/$O"
@@ -270,21 +272,22 @@ options:
     #n      "Provide repo list"    <>
 '
     param:run
-    # TODO: wait fix | input all name then can do it
-    ___x_cmd_ui_select nohelp "Are you sure you want to $(ui bold red delete repo) $(ui bold "$*")" "yes" "no" "---" "---"
-    [ "$___X_CMD_UI_SELECT_CURRENT_ITEM" != "yes" ] && gt_log info "Delete repo has been canceled" &&  return 0
+    xrc ui/lib/form
+    ___x_cmd_gt_printf_command_log "gt repo del " "$@"
+
+    local ___X_CMD_UI_FORM_EXIT_STRATEGY="execute|exit"
+    ___x_cmd_ui_form "Are you sure you want to $(___x_cmd_ui bold red delete "repo:") $(___x_cmd_ui bold "$*")" tf 1 = "yes" "no"
+    [ "$tf" != "yes" ] && gt_log info "Delete repo has been canceled" &&  return 0
     local i
     for i in "$@"; do
         ______x_cmd_gt_param_normalize_repo "$i"
         ______x_cmd_gt_delete "/v5/repos/$owner_repo" 1>/dev/null 2>&1
-        if [ $? -eq 0 ]; then
-            ui tf "true" "Deleted repo $i successfully"
-        else
-            gt_log error "Deleting repo failure: $i. Probably because it desn't exists."
-        fi
+        [ $? -eq 0 ] && ui tf "true" "Deleted repo $i successfully"                                  && return 0
+                        gt_log error "Deleting repo failure: $i. Probably because it desn't exists." && return 1
     done
 }
 
+# shellcheck disable=SC2181
 ___x_cmd_gt_repo_clear() {
     param:scope     "gitee/$O"
     param:dsl       '
@@ -294,25 +297,34 @@ options:
     param:run
 
     ___x_cmd_gt_param_init_owner_repo
-    # TODO: wait fix | input all name then can do it
-    ___x_cmd_ui_select nohelp "Are you sure you want to $(ui bold red clear repo) $(ui bold "${owner_repo}")" "yes" "no" "---" "---"
-    [ "$___X_CMD_UI_SELECT_CURRENT_ITEM" != "yes" ] && gt_log info "Clear repo has been canceled" &&  return 0
+    ___x_cmd_gt_printf_command_log "gt repo clear -r " "$@"
 
-    ______x_cmd_gt_put_json "/v5/repos/${owner_repo}/clear" && ___x_cmd_ui tf "true" "Successfully clear ${owner_repo}" && return 0
-                                                               gt_log error "Clearing repo failure: $owner_repo"        && return 1
+    local ___X_CMD_UI_FORM_EXIT_STRATEGY="execute|exit"
+    ___x_cmd_ui_form "Are you sure you want to $(ui bold red clear repo) $(ui bold "${owner_repo}")" tf 1 = "yes" "no"
+    [ "$tf" != "yes" ] && gt_log info "Clear repo has been canceled" &&  return 0
+
+    ______x_cmd_gt_put_json "/v5/repos/${owner_repo}/clear" 1>/dev/null 2>&1
+    [ $? -eq 0 ] && ___x_cmd_ui tf "true" "Successfully clear ${owner_repo}" && return 0
+                    gt_log error "Clearing repo failure: $owner_repo"        && return 1
 }
 
+# shellcheck disable=SC2154,SC2181
 ___x_cmd_gt_repo_review(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
     #1|--repo             "Repo name"                   <>:repo
-    --assignees           "assignees username"          <>:name
-    --testers             "testers usrename"            <>:name
-    --assignees_number    "number of reviewers"         <>:number="1"
-    --testers_number      "number of people tested"     <>:number="1"
+    --assignees           "assignees username"          <>:assignees
+    --testers             "testers usrename"            <>:testers
+    --assignees_number    "number of reviewers"         <>:assignees_number="1"
+    --testers_number      "number of people tested"     <>:testers_number="1"
 '
     param:run
     ___x_cmd_gt_param_init_owner_repo
-    ______x_cmd_gt_put_json "/v5/repos/${owner_repo}/reviewer" assignees testers assignees_number testers_number
+    ___x_cmd_gt_printf_command_log "gt repo review " \
+    "--repo $repo --assignees $assignees --testers $testers --assignees_number $assignees_number --testers_number $testers_number"
+
+    ______x_cmd_gt_put_json "/v5/repos/${owner_repo}/reviewer" assignees testers assignees_number testers_number 1>/dev/null 2>&1
+    [ $? -eq 0 ] && ___x_cmd_ui tf "true" "Successfully setup ${owner_repo} review configure" && return 0
+                    gt_log error "Setup repo review configure failure: $owner_repo"           && return 1
 }
diff --git a/lib/repo/member b/lib/repo/member
--- a/lib/repo/member
+++ b/lib/repo/member
@@ -7,6 +7,7 @@
 # gt repo member add user-b
 
 # gt repo member +el:admin -user-a +user-b
+# shellcheck disable=SC2154,SC2086
 ___x_cmd_gt_repo_member(){
     param:dsl       '
 subcmd:
@@ -32,16 +33,18 @@ options:
 '
     param:run
     ___x_cmd_gt_param_init_owner_repo
+    ___x_cmd_gt_printf_command_log "gt repo ls -r $repo"
+
     ___ui_table_json "$(printf "%s" "______x_cmd_gt_get_multi "/v5/repos/${owner_repo}/collaborators" page per_page || return 1" )" \
         NameSpace=.login Name=.name Admin=.permissions.admin PushPermissions=.permissions.push && return 0
 }
 
-# shellcheck disable=SC2181
+# shellcheck disable=SC2181,SC2154
 ___x_cmd_gt_repo_member_add() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    --repo|-r           "Repo name"                              <>:repo
+    --repo|-r           "Repo name or Path(owner/repo)"          <>:repo
     --permission|-p     "permission"                             <>:permission="push"
     #n                  "Username list"                          <>
 '
@@ -50,16 +53,17 @@ options:
     # param Design permission:key
     ___x_cmd_gt_param_init_owner_repo
     if [ -z "$1" ];then
-        gt_log error "At least one user’s spatial address is needed"
+        gt_log error "At least one user’s spatial address is needed, gt member add <user>"
         return 1
     fi
+    ___x_cmd_gt_printf_command_log "gt member add -r $repo -p $permission " "$@"
+
     local username
     for username in "$@"; do
         {
             ______x_cmd_gt_put_json "/v5/repos/$owner_repo/collaborators/${username##*/}" permission 1>/dev/null 2>&1
-
-            [ $? -ne 0 ] && gt_log error "add user failure: $username"               && return 1
-                            gt_log info  "add $username to $owner_repo successfully" && return 0
+            [ $? -ne 0 ] && gt_log error "add user failure: $username to $owner_repo" && return 1
+                            gt_log info  "add $username to $owner_repo successfully"  && return 0
         }
     done
 }
@@ -70,13 +74,15 @@ ___x_cmd_gt_repo_member_del() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    --repo|-r       "Repo name"            <>:repo
+    --repo|-r       "Repo name or Path(owner/repo)"     <>:repo
     #n              "Username list"
 '
     param:run
     [ -z "$1" ] && gt_log error "At least one user’s spatial address is needed" && return 1
 
     ___x_cmd_gt_param_init_owner_repo
+    ___x_cmd_gt_printf_command_log "gt member del -r $repo " "$@"
+
     local username
     for username in "$@"; do
         ______x_cmd_gt_delete "/v5/repos/$owner_repo/collaborators/${username##*/}"
