Squashed 'mod/gh/' changes from cb2ceff0..35560f40
35560f40 update config
b5eca27c config awk

git-subtree-dir: mod/gh
git-subtree-split: 35560f408d16a525c44e06730e5da49ef7345dfb

diff --git a/lib/config b/lib/config
--- a/lib/config
+++ b/lib/config
@@ -4,9 +4,9 @@
 ___x_cmd_gh_config(){
     param:dsl       '
 subcmd:
-    which       "Show current config path"
-    save        "Save the config in memory into file"
-    load        "Load the config from config path"
+    which      "Show current config path"
+    get        "Print the value of a given configuration key"
+    set        "Update configuration with a value for the given key"
 '
     param:run
 
@@ -25,25 +25,35 @@ ___x_cmd_gh_config_which() {
     printf "%s\n" "$HOME/.x-cmd/.config/x-bash/app.github.config/$O"
 }
 
-# TODO:config
-___x_cmd_gh_config_save() {
-    param:void
+___x_cmd_gh_config_get() {
+    param:scope     "github/$O"
+    param:dsl       '
+type:
+    ConfigName  =   oauth_token user git_protocol
+options:
+    --host        "host name"                               <>="github.com"
+    #1            "The name of the configuration to get"    <>:ConfigName
+'
+    param:run
     local O="${O:-GITHUB_DEFAULT}"
-    local ___github_path="${1:-$HOME/.x-cmd/.config/x-bash/app.github.config/$O}"
-    [ ! -e "$___github_path" ] && mkdir -p "$___github_path##*/"
-    ___x_cmd_gh_default dump "github_$O">"$___github_path" && return 0
-    gh_log error "gh config save Fail"
+    [ -e  "$HOME/.x-cmd/.config/x-bash/app.github.config/$O" ] || return 1
+    ___x_cmd_git_config_get "$HOME/.x-cmd/.config/x-bash/app.github.config/$O" "$host" "$1"
 }
 
-# shellcheck disable=SC2120
-___x_cmd_gh_config_load() {
-    param:void
+___x_cmd_gh_config_set() {
+    param:scope     "github/$O"
+    param:dsl       '
+type:
+    ConfigName  =   oauth_token user git_protocol
+options:
+    --host      "host name"                           <>="github.com"
+    #1        "Please provide configuration key"      <>:ConfigName
+    #2        "Please provide configuration val"      <>
+'
+    param:run
     local O="${O:-GITHUB_DEFAULT}"
-    local ___github_path="${1:-$HOME/.x-cmd/.config/x-bash/app.github.config/$O}"
-    [ ! -f "$___github_path" ] && gh_log info "info:There is no history config" && return
-    ___x_cmd_gh_default load "github_$O" "$___github_path"
-    local token
-    token="$(___x_cmd_gh_default get "github_$O" token)"
-    http "@___x_cmd_gh_${O:-GITHUB_DEFAULT}" header put Authorization "token $token"
+    local ___github_path="$HOME/.x-cmd/.config/x-bash/app.github.config/$O"
+    [ -e  "$___github_path" ] || mkdir -p "$___github_path##*/"
+    ___x_cmd_git_config_set "$___github_path" "$host" "$1" "$2" && ___x_cmd_ui_tf "true" "set config successfully" && return 0
+    gh_log error "gh config set Fail"
 }
-# EndSection
