Squashed 'mod/hub/' changes from 635bfe5..78fddfb
78fddfb fix(share): set file share
d6396db feat(user): only save token use no user id
38de3b5 feat(user): only save token use no user id
583034a feat(user): only save token
3dd862c feat(user): only save token
2d295f9 feat(user): use .me to save usernaem
cb2330e feat(user): use .me to save usernaem

git-subtree-dir: mod/hub
git-subtree-split: 78fddfbb28dfe14fadfb693ef96175eb4f5ef2ce

diff --git a/lib/file b/lib/file
--- a/lib/file
+++ b/lib/file
@@ -37,35 +37,31 @@ ___x_cmd_hub_file_which(){
     local respath="${1:?Provide respath}"
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
 
-    local CACHE="${___X_CMD_ROOT%/}/${respath#/}"
-    mkdir -p "${CACHE%/*}"
-    if ___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/cat?token=$(___x_cmd_hub_token)&res=${respath}" >"$CACHE"; then
-        printf "%s\n" "$CACHE"
+    local cache_path="${___X_CMD_HUB_ENV}/.cache/${respath#/}"
+    local cache_expiration=1
+    mkdir -p "${cache_path%/*}"
+    if ___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/cat?token=$(___x_cmd_hub_token)&res=${respath}" "$cache_path" "$cache_expiration"; then
+        hub_log debug "Downloaded ${respath} to ${cache_path}"
+        printf "%s\n" "$cache_path"
     else
-        hub_log error "Failed: $CACHE, res = $(cat "$CACHE")"
+        hub_log error "Failed: ___x_cmd_httpget return $?, you can use 'x log +x' to open the debug log"
         return 1
     fi
 }
 
+# TODO: Should be review. @el
 ___x_cmd_hub_file_normalize_respath(){
     local respath="${1}"
     case "$respath" in
         @me/*|@i/*|@/*)
-            local user
-            user=$(___x_cmd_hub_login_user)
-            if [ -z "$user" ]; then
-                hub_log error "Cannot not find out login user for resource: %s" "$respath"
-                return 1
-            fi
-            printf "%s" "$user/${respath#@*/}"
             ___X_CMD_WHICH_ONE_RESOURCE_TYPE=me@hub
-            ;;
+            printf "%s" "$respath" ;;
         *@*)
             ___X_CMD_WHICH_ONE_RESOURCE_TYPE=hub
             printf "%s" "$respath" ;;
         *)
             ___X_CMD_WHICH_ONE_RESOURCE_TYPE=hub
-            printf "%s" "$(___x_cmd_hub_login_user)/${respath#/}" ;;
+            printf "%s" "@me/${respath#/}" ;;
     esac
 }
 
@@ -91,8 +87,12 @@ ___x_cmd_hub_file_share(){
     local respath="${1:?Please provide path}"
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
 
-    curl "$___X_CMD_HUB_SERVICE_URL/api/v0/file/share/true?token=$(___x_cmd_hub_token)&res=${respath}" 2>/dev/null
-    printf "\n"
+    if ! res="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/share/true?token=$(___x_cmd_hub_token)&res=${respath}")" ; then
+        hub_log error "Failed to share file: $res"
+        return 1
+    fi
+
+    hub_log info "File shared successfully: $res"
 }
 
 ___x_cmd_hub_file_private(){
@@ -100,6 +100,10 @@ ___x_cmd_hub_file_private(){
     local respath="${1:?Please provide path}"
     respath="$(___x_cmd_hub_file_normalize_respath "$respath")"
 
-    curl "$___X_CMD_HUB_SERVICE_URL/api/v0/file/share/false?token=$(___x_cmd_hub_token)&res=${respath}" 2>/dev/null
-    printf "\n"
+    if ! res="$(___x_cmd_httpget "$___X_CMD_HUB_SERVICE_URL/api/v0/file/share/false?token=$(___x_cmd_hub_token)&res=${respath}")" ; then
+        hub_log error "Failed to private file: $res"
+        return 1
+    fi
+
+    hub_log info "File private successfully: $res"
 }
