Squashed 'mod/xrc/' changes from a60d5db5..6d247b6c
6d247b6c ...
abe5d598 ...
c9a68a68 ...
39e5ce86 Merge branch 'main' of gitee.com:x-bash/xrc
08b419bd ...

git-subtree-dir: mod/xrc
git-subtree-split: 6d247b6c6be0f64d9282f1821cc07eaa214bd0d0

diff --git a/lib/httpget b/lib/httpget
--- a/lib/httpget
+++ b/lib/httpget
@@ -1,3 +1,4 @@
+# shellcheck    shell=sh        disable=SC2039,SC1090,SC3043,SC2263
 
 ___x_cmd_httpget_handle_resp_header(){
     local url="${1:?Provide url}"
@@ -18,8 +19,26 @@ ___x_cmd_httpget_handle_resp_header(){
     esac
 }
 
+___x_cmd_fileage(){
+    if stat -c "%Y" /bin/sh 2>/dev/null 1>&2; then
+        ___x_cmd_httpget_fileage(){
+            ___X_CMD_FILEAGE="$(( $(date +%s) - $(stat -c "%Y" "$1") ))"
+        }
+    elif stat -f "%m" /bin/sh 2>/dev/null 1>&2; then
+        ___x_cmd_httpget_fileage(){
+            ___X_CMD_FILEAGE="$(( $(date +%s) - $(stat -f "%m" "$1") ))"
+        }
+    else
+        return 1
+    fi
+
+    ___x_cmd_httpget_fileage "$@"
+}
+
 # TODO: rename to ___x_cmd_httpget_with_cache
 ___x_cmd_httpget() {
+    ___X_CMD_HTTPGET_AGE=-1
+
     local url="${1:?Provide url}"
     local cache="$2"
     local cache_expiration="$3"
@@ -35,8 +54,15 @@ ___x_cmd_httpget() {
                     ;;
                 -)  # force update
                     ;;
-                *)  # days
-                    if [ -n "$(find "$cache" -mtime "-$cache_expiration" 2>/dev/null)" ]; then
+                *)
+                    # days
+                    # if [ -n "$(find "$cache" -mtime "-$cache_expiration" 2>/dev/null)" ]; then
+                    if ! ___x_cmd_fileage "$cache"; then
+                        x:error "Fail to get file age: $cache"
+                        return 1
+                    fi
+
+                    if [ "$___X_CMD_FILEAGE" -lt "$cache_expiration" ]; then
                         x:debug "Function ___x_cmd_httpget() terminated. Because local cache existed within days: $cache_expiration"
                         return 0
                     fi
@@ -55,6 +81,7 @@ ___x_cmd_httpget() {
         if [ -n "$cache" ]; then
             x:debug "Copy the temp file to CACHE file: $cache"
             mv "$redirect_path" "$cache"
+            ___X_CMD_HTTPGET_AGE=0
         fi
     else
         code=$?
