Squashed 'mod/gitee/' changes from 12dada79..bfb9b272
bfb9b272 ...
38e7e079 ...
3028f4a6 ...
394268e1 ...
e5569b58 ...
23d57537 ...
d56e87a1 Merge branch 'main' of gitee.com:x-bash/gt
a9243073 ...
18693290 style(gt): update format
efb96a21 style(gt): update format and del useless type
89008846 echo to printf or gt_log
964fbe5f fix error code
e3724b74 update error code
d6c4128b repo member
2275a6f2 update http make
fa623913 fix(enterprise): fix enterprise output msg
fee4b4a9 fix(org): fix organization bug and printf msg

git-subtree-dir: mod/gitee
git-subtree-split: bfb9b2722ea6ff88093ffd56c36354cc8affd515

diff --git a/lib/issue b/lib/issue
--- a/lib/issue
+++ b/lib/issue
@@ -170,8 +170,8 @@ subcmd:
 '
     param:run
     if [ -z "$PARAM_SUBCMD" ]; then
-        echo "subcmd not found. show help." >&2
-        return 0
+        gt_log warn "subcmd not found. show help." >&2
+        return 1
     fi
     "___x_cmd_gt_issue_comment_$PARAM_SUBCMD" "$@"
 }
diff --git a/lib/repo/member b/lib/repo/member
--- a/lib/repo/member
+++ b/lib/repo/member
@@ -16,9 +16,9 @@ subcmd:
 '
     param:run
     if [ -z "$PARAM_SUBCMD" ]; then
-        gt_log warn "Subcmd Not Found."
+        gt_log warn "Subcmd Not Found."  
         ___x_cmd_gt_repo_member _param_help_doc
-        return 0
+        return 1
     fi
     
     "___x_cmd_gt_repo_member_$PARAM_SUBCMD" "$@"
@@ -32,8 +32,9 @@ options:
 '
     param:run
     ___x_cmd_gt_param_init_owner_repo
-    ui table func ______x_cmd_gt_table "\"\$(O=$O ______x_cmd_gt_get_multi \"/v5/repos/${owner_repo}/collaborators\" page per_page)\"" \
-        . id login name push=permissions.push admin=permissions.admin
+    ______x_cmd_gt_get_multi "/v5/repos/${owner_repo}/collaborators" page per_page
+    # ui table func ______x_cmd_gt_table "\"\$(O=$O ______x_cmd_gt_get_multi \"/v5/repos/${owner_repo}/collaborators\" page per_page)\"" \
+    #     . id login name push=permissions.push admin=permissions.admin
 }
 
 ___x_cmd_gt_repo_member_add() {
@@ -48,19 +49,23 @@ options:
 
     ___x_cmd_gt_param_init_owner_repo
     if [ -z "$1" ];then
-        echo "At least one user’s spatial address is needed"
+        gt_log error "At least one user’s spatial address is needed"
         return 1
     fi
     local username
     for username in "$@"; do
         {
             ______x_cmd_gt_put_json "/v5/repos/$owner_repo/collaborators/${username##*/}" permission 1>/dev/null
-            local code=$?
-            if [ $code -ne 0 ]; then
-                gt_log error "add user failure: $username. Code is $code. "
-            else
-                ui tf "true" "add $username to $owner_repo successfully"
-            fi
+            
+            [ $? -ne 0 ] && gt_log error "add user failure: $username" && return 1
+            
+            ui tf "true" "add $username to $owner_repo successfully"
+
+        # if [ $? -ne 0 ];then
+        #     gt_log error "add user failure: $username"
+        # else
+        #     ui tf "true" "add $username to $owner_repo successfully"
+        # fi
         }  
     done
 }
@@ -80,10 +85,9 @@ options:
     local username
     for username in "$@"; do
         ______x_cmd_gt_delete "/v5/repos/$owner_repo/collaborators/${username##*/}"
-        if [ $? -ne 0 ];then
-            gt_log error "delete user failure: $username."
-        else
-            ui tf "true" "successfully deleted $username in $owner_repo"
-        fi
+        
+        [ $? -ne 0 ] && gt_log error "delete user failure: $username." && return 1
+            
+        ui tf "true" "successfully deleted $username in $owner_repo"
     done
 }
