Squashed 'mod/gitee/' changes from b6553c45..ce8d3cb7
ce8d3cb7 ...
7d798987 ...
788cd425 ...
aa5926c8 ...
9f9660fc ...
72c54ca7 ...
bf2a7842 ...
b97fe3fe ...

git-subtree-dir: mod/gitee
git-subtree-split: ce8d3cb7ed25dec2c27376e10e43eca83eb6cdea

diff --git a/lib/issue b/lib/issue
--- a/lib/issue
+++ b/lib/issue
@@ -7,9 +7,9 @@
 # gt repo issue add user-b
 
 # gt repo issue +el:admin -user-a +user-b
-gt_issue(){
+___x_cmd_gt_issue(){
     param:dsl       '
-subcommands:
+subcmd:
     create          "create issue"
     update          "update issue"
     info            "get issue info"
@@ -20,14 +20,14 @@ subcommands:
     param:run
 
     if [ -z "$PARAM_SUBCMD" ]; then
-        echo "subcommand not found. show help." >&2
+        echo "subcmd not found. show help." >&2
         return 0
     fi
-    "gt_issue_$PARAM_SUBCMD" "$@"
+    "___x_cmd_gt_issue_$PARAM_SUBCMD" "$@"
 }
 
 
-gt_issue_create() {
+___x_cmd_gt_issue_create() {
     param:scope     "gitee/$O"
     param:dsl      '
 options:
@@ -45,11 +45,11 @@ options:
 '
     security=${security:-false}
     param:run
-    ___gt_post_json "/v5/repos/${owner##*/}/issues" repo title issue_type=$type body assignee \
+    ______x_cmd_gt_post_json "/v5/repos/${owner##*/}/issues" repo title issue_type=$type body assignee \
         collaborators milestone labels program security_hole=$security  
 }
 
-gt_issue_update() {
+___x_cmd_gt_issue_update() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -68,11 +68,11 @@ options:
 '
     param:run
     security=${security:-false}
-    ___gt_patch_json "/v5/repos/${owner##*/}/issues/${number}" repo title state body assignee \
+    ______x_cmd_gt_patch_json "/v5/repos/${owner##*/}/issues/${number}" repo title state body assignee \
         collaborators milestone labels program security_hole=$security  
 }
 
-gt_issue_logs(){
+___x_cmd_gt_issue_logs(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -82,7 +82,7 @@ options:
     --sort          "sort(asc、desc)"       <>="desc"
 '
     param:run
-    ___gt_get "/v5/repos/${owner##*/}/issues/${number}/operate_logs" repo sort  
+    ______x_cmd_gt_get "/v5/repos/${owner##*/}/issues/${number}/operate_logs" repo sort  
 }
 
 
@@ -91,7 +91,7 @@ options:
 # shellcheck disable=SC2039,3043
 
 # schedule、deadline、created_at、finished_at 用UI来处理
-gt_repo_issue() {
+___x_cmd_gt_repo_issue() {
     param:scope     "gitee/$O"
     param:dsl       '
 type:
@@ -109,17 +109,17 @@ options:
     --number        "repo issue number"         <>=""
 '
     param:run
-    gt_param_init_owner_repo
+    ___x_cmd_gt_param_init_owner_repo
     if [ -z $number ]; then
-        ___gt_get_multi "/v5/repos/${owner_repo}/issues" state labels sort direction \
+        ______x_cmd_gt_get_multi "/v5/repos/${owner_repo}/issues" state labels sort direction \
             milestone assignee creator program  
     else
-        ___gt_get "/v5/repos/${owner_repo}/issues/${number}"  
+        ______x_cmd_gt_get "/v5/repos/${owner_repo}/issues/${number}"  
     fi
     return
 }
 
-gt_org_issue(){
+___x_cmd_gt_org_issue(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -131,11 +131,11 @@ options:
     --org           "organization path"                            <>
 '
     param:run
-    ___gt_get "/v5/orgs/${org##*/}/issues" filter state labels sort direction since page per_page \
+    ______x_cmd_gt_get "/v5/orgs/${org##*/}/issues" filter state labels sort direction since page per_page \
         schedule deadline created_at finished_at  
 }
 
-gt_enterprise_issue(){
+___x_cmd_gt_enterprise_issue(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -151,17 +151,17 @@ options:
     --program       "program"                                      <>=""
 '
     param:run
-    ___gt_get "/v5/enterprises/${enterprise##*/}/issues" \
+    ______x_cmd_gt_get "/v5/enterprises/${enterprise##*/}/issues" \
         filter state labels sort direction since page per_page \
         schedule deadline created_at finished_at milestone assignee creator program      
 }
 
 # Section : comment
 
-gt_issue_comment(){
+___x_cmd_gt_issue_comment(){
     param:scope     "gitee/$O"
     param:dsl       '
-subcommands:
+subcmd:
     ls              "list all comment"
     create          "create a comment"
     update          "update a comment"
@@ -169,13 +169,13 @@ subcommands:
 '
     param:run
     if [ -z "$PARAM_SUBCMD" ]; then
-        echo "subcommand not found. show help." >&2
+        echo "subcmd not found. show help." >&2
         return 0
     fi
-    "gt_issue_comment_$PARAM_SUBCMD" "$@"
+    "___x_cmd_gt_issue_comment_$PARAM_SUBCMD" "$@"
 }
 
-gt_issue_comment_ls(){
+___x_cmd_gt_issue_comment_ls(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -188,10 +188,10 @@ options:
     --order         "order(asc、desc)"      <>="asc"
 '
     param:run
-    ___gt_get_multi "/v5/repos/${owner##*/}/${repo##*/}/issues/$number/comments"  since page per_page order  
+    ______x_cmd_gt_get_multi "/v5/repos/${owner##*/}/${repo##*/}/issues/$number/comments"  since page per_page order  
 }
 
-gt_issue_comment_create(){
+___x_cmd_gt_issue_comment_create(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -201,10 +201,10 @@ options:
     --body          "The contents of the comment."      <>
 '
     param:run
-    ___gt_post_json "/v5/repos/${owner##*/}/${repo##*/}/issues/$number/comments"  body  
+    ______x_cmd_gt_post_json "/v5/repos/${owner##*/}/${repo##*/}/issues/$number/comments"  body  
 }
 
-gt_issue_comment_update(){
+___x_cmd_gt_issue_comment_update(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -214,10 +214,10 @@ options:
     --body          "The contents of the comment."      <>
 '
     param:run
-    ___gt_patch_json "/v5/repos/${owner##*/}/${repo##*/}/issues/comments/${id}"  body  
+    ______x_cmd_gt_patch_json "/v5/repos/${owner##*/}/${repo##*/}/issues/comments/${id}"  body  
 }
 
-gt_issue_comment_delete(){
+___x_cmd_gt_issue_comment_delete(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -226,7 +226,7 @@ options:
     --id            "comments id"                       <>
 '
     param:run
-    ___gt_delete "/v5/repos/${owner##*/}/${repo##*/}/issues/comments/${id}"  
+    ______x_cmd_gt_delete "/v5/repos/${owner##*/}/${repo##*/}/issues/comments/${id}"  
 }
 
 # EndSection
diff --git a/lib/org b/lib/org
--- a/lib/org
+++ b/lib/org
@@ -1,10 +1,10 @@
 # shellcheck shell=sh
 # shellcheck disable=SC2039,3043
 
-gt_org(){
+___x_cmd_gt_org(){
     param:scope     "gitee/$O"
     param:dsl       '
-subcommands:
+subcmd:
     new                     "new organization client"
     info                    "Show information"
     create                  "create org"
@@ -16,28 +16,28 @@ subcommands:
     param:run
 
     if [ -z "$PARAM_SUBCMD" ]; then
-        gt_log error "Command Not Found. Show help."
+        ___x_cmd_gt_log error "Command Not Found. Show help."
         return 0
     fi
       
-    "gt_org_${PARAM_SUBCMD}" "$@"
+    "___x_cmd_gt_org_${PARAM_SUBCMD}" "$@"
 }
 
-_gt_org()(
-    gt_current_owner "${1:?organziation name}" "org"
+____x_cmd_gt_org()(
+    ___x_cmd_gt_current_owner "${1:?organziation name}" "org"
     shift 1
-    gt_org ${1:+"$@"}
+    ___x_cmd_gt_org ${1:+"$@"}
 )
 
-gt_org_new() {
+___x_cmd_gt_org_new() {
     param:void
     local orgname="${1:?Provide orgname name}"
     local aliasname="${2:-$reponame}"
     # shellcheck disable=SC2139
-    alias "$aliasname=\"O=$O _gt_org $orgname\""
+    alias "$aliasname=\"O=$O ____x_cmd_gt_org $orgname\""
 }
 
-gt_org_info() {
+___x_cmd_gt_org_info() {
     param:scope     "gitee/$O"
     param:dsl       '
 type: 
@@ -48,17 +48,17 @@ options:
 
     admin=${admin:-false}
     if [ $# -eq 0 ]; then
-        ___gt_get_multi "/v5/user/orgs" admin page per_page
+        ______x_cmd_gt_get_multi "/v5/user/orgs" admin page per_page
         [ $? -eq 1 ] && return 1
     else
-        ___gt_get "/v5/orgs/${1:?Provide organization}"
+        ______x_cmd_gt_get "/v5/orgs/${1:?Provide organization}"
         [ $? -eq 1 ] && return 1
     fi
     return 0
 }
 
 # It is very rare TODO:batch?
-gt_org_create() {
+___x_cmd_gt_org_create() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -68,36 +68,36 @@ options:
 '
     param:run
     org=${org:-$1}
-    ___gt_post_json "/v5/users/organization" name="$1" org description  
+    ______x_cmd_gt_post_json "/v5/users/organization" name="$1" org description  
 }
 
-gt_org_repo(){
+___x_cmd_gt_org_repo(){
     param:dsl       '
-subcommands:
+subcmd:
     ls          "list repo"
     create      "org repo create"
 '
     param:run
     if [ -z "$PARAM_SUBCMD" ]; then
-        gt_log error "Command Not Found. Show help."
+        ___x_cmd_gt_log error "Command Not Found. Show help."
         return 0
     fi
-    "gt_org_repo_${PARAM_SUBCMD}" "$@"
+    "___x_cmd_gt_org_repo_${PARAM_SUBCMD}" "$@"
 }
 
 # https://gitee.com/api/v5/swagger#/getV5OrgsOrgRepos
-gt_org_repo_ls() {
+___x_cmd_gt_org_repo_ls() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
     --type     "type"     <>="all"    = all private public
 '
     param:run
-    ui table func ___gt_table "\"\$(O=$O ___gt_get_multi \"/v5/orgs/${1:?Provide organization}/repos\" type)\"" \
+    ui table func ______x_cmd_gt_table "\"\$(O=$O ______x_cmd_gt_get_multi \"/v5/orgs/${1:?Provide organization}/repos\" type)\"" \
         . id full_name ownerName=owner.name updatedTime="updated_at"
 }
 
-gt_org_quit() {
+___x_cmd_gt_org_quit() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -110,7 +110,7 @@ options:
     fi
         for org in "$@"; do
         {
-            ___gt_delete "/v5/user/memberships/orgs/${org##*/}"
+            ______x_cmd_gt_delete "/v5/user/memberships/orgs/${org##*/}"
         code=$?
             if [ $code -ne 0 ]; then
                 echo "Creating repo failure: $name. Code is $code. " >&2
@@ -131,9 +131,9 @@ options:
 # gt repo member add user-b
 
 # gt repo member +el:admin -user-a +user-b
-gt_org_member(){
+___x_cmd_gt_org_member(){
     param:dsl       '
-subcommands:
+subcmd:
     ls            "list member"
     user            "get org member user info"
     add             "add member"
@@ -142,14 +142,14 @@ subcommands:
     param:run
 
     if [ -z "$PARAM_SUBCMD" ]; then
-        echo "subcommand not found. show help." >&2
+        echo "subcmd not found. show help." >&2
         return 0
     fi
     
-    "gt_org_member_$PARAM_SUBCMD" "$@"
+    "___x_cmd_gt_org_member_$PARAM_SUBCMD" "$@"
 }
 
-gt_org_member_ls() {
+___x_cmd_gt_org_member_ls() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -157,10 +157,10 @@ options:
     --role          "Repo name"            <>="all"         = admin member all
 '
     param:run
-    ___gt_get_multi "/v5/orgs/${org##*/}/members" role page per_page  
+    ______x_cmd_gt_get_multi "/v5/orgs/${org##*/}/members" role page per_page  
 }
 
-gt_org_member_user() {
+___x_cmd_gt_org_member_user() {
     param:scope     "gitee/$O"
     param:dsl      '
 options:
@@ -169,10 +169,10 @@ options:
 '
     param:run
 
-    ___gt_get "/v5/orgs/${org##*/}/memberships/${username##*/}"  
+    ______x_cmd_gt_get "/v5/orgs/${org##*/}/memberships/${username##*/}"  
 }
 
-gt_org_member_add() {
+___x_cmd_gt_org_member_add() {
     param:scope     "gitee/$O"
     param:dsl       '
 type: 
@@ -184,7 +184,7 @@ options:
 '
     param:run
 
-    # repo="$(___gt_param_normalize_repo "$repo")" || return 1
+    # repo="$(______x_cmd_gt_param_normalize_repo "$repo")" || return 1
     if [ -z "$1" ];then
         echo "At least one user’s spatial address is needed"
         return 1
@@ -192,7 +192,7 @@ options:
 
         for username in "$@"; do
         {
-            ___gt_put_json "/v5/orgs/${org##*/}/memberships/${username##*/}" role
+            ______x_cmd_gt_put_json "/v5/orgs/${org##*/}/memberships/${username##*/}" role
             local code=$?
             if [ $code -ne 0 ]; then
                 echo "Creating repo failure: $username. Code is $code. " >&2
@@ -202,7 +202,7 @@ options:
     done
 }
 
-gt_org_member_del() {
+___x_cmd_gt_org_member_del() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -219,7 +219,7 @@ options:
     local username
     for username in "$@"; do
         {
-            ___gt_delete "/v5/orgs/${org##*/}/memberships/${username##*/}"
+            ______x_cmd_gt_delete "/v5/orgs/${org##*/}/memberships/${username##*/}"
             code=$?
             if [ $code -ne 0 ]; then
                 echo "Creating repo failure: $name. Code is $code. " >&2
diff --git a/lib/repo b/lib/repo
--- a/lib/repo
+++ b/lib/repo
@@ -1,10 +1,10 @@
 # shellcheck shell=sh
 # shellcheck disable=SC2039,3043
 
-gt_repo(){
+___x_cmd_gt_repo(){
     param:scope     "gitee/$O"
     param:dsl       '
-subcommands:
+subcmd:
     new             "new repo client"
     create          "create repo"
     ls              "list repo of owner"
@@ -18,29 +18,29 @@ subcommands:
     param:run
 
     if [ -z "$PARAM_SUBCMD" ]; then
-        gt_log error "Command Not Found. Show help."
+        ___x_cmd_gt_log error "Command Not Found. Show help."
         return 0
     fi
     
-    "gt_repo_${PARAM_SUBCMD}" "$@" 
+    "___x_cmd_gt_repo_${PARAM_SUBCMD}" "$@" 
 }
 
-_gt_repo()(
-    gt_current_repo "${1:-repo}"
+____x_cmd_gt_repo()(
+    ___x_cmd_gt_current_repo "${1:-repo}"
     shift
-    gt_repo ${1:+"$@"}
+    ___x_cmd_gt_repo ${1:+"$@"}
 )
 
-gt_repo_new() {
+___x_cmd_gt_repo_new() {
     param:void
     local reponame="${1:?Provide object name}"
     local aliasname="${2:-$reponame}"
     # shellcheck disable=SC2139
-    alias "$aliasname=\"O=$O _gt_repo $reponame\""
+    alias "$aliasname=\"O=$O ____x_cmd_gt_repo $reponame\""
 }
 
 # arguments NAME
-gt_repo_create() {
+___x_cmd_gt_repo_create() {
     local O="${O:-GITEE_DEFAULT}"
 
     param:scope     "gitee/$O"
@@ -78,12 +78,12 @@ option:
     [ -n "$no_comment" ] && can_comment=false
     [ -n "$no_auto_init" ] && auto_init=false
 
-    [ $# -eq 0 ] && gt_log info "repo create name is null" && return
+    [ $# -eq 0 ] && ___x_cmd_gt_log info "repo create name is null" && return
     local name
     for name in "$@"; do
         {
             local data repo_id url repo_owner
-            data=$(___gt_post_json "/v5/user/repos" name="${name##*/}" description homepage has_issues has_wiki can_comment \
+            data=$(______x_cmd_gt_post_json "/v5/user/repos" name="${name##*/}" description homepage has_issues has_wiki can_comment \
             auto_init gitignore_template license_template path="$paths" private 2>/dev/null)
             ___json_awk_get repo_id=.id url=.html_url repo_owner=.owner.login <<A
             $data
@@ -91,7 +91,7 @@ A
             if [ -n "$repo_id" ];then
                 ui tf "true" "Creating repo $name success" "repo_id:$repo_id" "url:$url" "repo_owner:$repo_owner" 
             else
-                gt_log error "Creating repo failure: $name. Code is $code. " 
+                ___x_cmd_gt_log error "Creating repo failure: $name. Code is $code. " 
             fi
         }
     done
@@ -101,7 +101,7 @@ A
 # shellcheck disable=SC2154,SC2034
 
 # https://gitee.com/api/v5/swagger#/postV5OrgsOrgRepos
-gt_org_repo_create() {
+___x_cmd_gt_org_repo_create() {
     # TODO: I don't know what does path means for an organization repo
     # path is null default repo name as path
     param:scope     "gitee/$O"
@@ -142,17 +142,17 @@ option:
     # TODO:owner may be personal
     local name
     for name in "$@"; do
-        # name="$(___gt_param_normalize_repo "$name")"
+        # name="$(______x_cmd_gt_param_normalize_repo "$name")"
         # owner="$(echo "$name" | cut -d / -f 1)"
         # name="$(echo "$name" | cut -d / -f 2)"
         local resp
         {
-            ___gt_post_json "/v5/orgs/$org/repos" name description homepage has_issues has_wiki can_comment auto_init \
+            ______x_cmd_gt_post_json "/v5/orgs/$org/repos" name description homepage has_issues has_wiki can_comment auto_init \
              gitignore_template license_template path="$paths" public
             code=$?
             if [ $code -ne 0 ]; then
-                gt_log error "Creating repo failure: $name. Code is $code. "
-                # ___gt_resp_header "" >&2
+                ___x_cmd_gt_log error "Creating repo failure: $name. Code is $code. "
+                # ______x_cmd_gt_resp_header "" >&2
                 return $code
             fi
         } 
@@ -161,7 +161,7 @@ option:
 
 # https://gitee.com/api/v5/swagger#/postV5EnterprisesEnterpriseRepos
 # shellcheck disable=SC2154
-gt_enterprise_repo_create() {
+___x_cmd_gt_enterprise_repo_create() {
     param:scope     "gitee/$O"
     param:dsl       '
 type:
@@ -204,12 +204,12 @@ option:
     local name
     for name in "$@"; do
     {
-        ___gt_post_json "/v5/enterprises/${enterprise##*/}/repos" \
+        ______x_cmd_gt_post_json "/v5/enterprises/${enterprise##*/}/repos" \
             name description homepage has_issues can_comment auto_init \
             gitignore_template license_template path="$paths" private enterprise outsourced project_creator members
             code=$?
             if [ $code -ne 0 ]; then
-                gt_log error "Creating repo failure: $name. Code is $code. "
+                ___x_cmd_gt_log error "Creating repo failure: $name. Code is $code. "
                 return $code
             fi
         } | json_color
@@ -224,24 +224,24 @@ option:
 
 # gt repo list --access inner-source <owner>
 # gt enterprise repo list
-gt_repo_ls() {
+___x_cmd_gt_repo_ls() {
     param:void
     local owner
     owner="$1"
 
     if [ -z "$owner" ]; then
-        gt_user_repo "$@"
+        ___x_cmd_gt_user_repo "$@"
         return
     fi
 
     local owner_type
-    owner_type="$(___gt_owner_type_query "$owner")"
+    owner_type="$(______x_cmd_gt_owner_type_query "$owner")"
     if [ -n "$owner_type" ] && [ -n "$owner" ]; then
-        "gt_${owner_type}_repo" ls "$@"
+        "___x_cmd_gt_${owner_type}_repo" ls "$@"
         return
     fi
 
-    gt_log error "Please provide owner and owner_type\n"
+    ___x_cmd_gt_log error "Please provide owner and owner_type\n"
     return 1
     # param_help.show
 }
@@ -249,7 +249,7 @@ gt_repo_ls() {
 ############################
 # Section 7: Repo - Deletion & Info & Creation
 ############################
-gt_repo_info() {
+___x_cmd_gt_repo_info() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -257,13 +257,13 @@ options:
 '
     param:run
 
-    gt_param_init_owner_repo
-    ___gt_get "/v5/repos/${owner_repo}"
-    # ___gt_get "/v5/repos/${owner}/${repo}"
+    ___x_cmd_gt_param_init_owner_repo
+    ______x_cmd_gt_get "/v5/repos/${owner_repo}"
+    # ______x_cmd_gt_get "/v5/repos/${owner}/${repo}"
 }
 
 # https://gitee.com/api/v5/swagger#/deleteV5ReposOwnerRepo
-gt_repo_del() {
+___x_cmd_gt_repo_del() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -275,17 +275,17 @@ options:
     [ "$confirm" = "no" ] && return
     local i
     for i in "$@"; do
-        ___gt_param_normalize_repo "$i"
-        ___gt_delete "/v5/repos/$owner_repo" >/dev/null 
+        ______x_cmd_gt_param_normalize_repo "$i"
+        ______x_cmd_gt_delete "/v5/repos/$owner_repo" >/dev/null 
         if [ $? -eq 0 ]; then
             ui tf "true" "deleted repo $i"
         else
-            gt_log error "Code is $?. Deleting repo failure: $i. Probably because it desn't exists."
+            ___x_cmd_gt_log error "Code is $?. Deleting repo failure: $i. Probably because it desn't exists."
         fi
     done
 }
 
-gt_repo_clear() {
+___x_cmd_gt_repo_clear() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -293,15 +293,15 @@ options:
 '
     param:run
 
-    gt_param_init_owner_repo
+    ___x_cmd_gt_param_init_owner_repo
     local confirm
     confirm=$(ui select "text" "Are you sure you want to clear repo ${owner_repo}" "yes" "no")
     [ "$confirm" = "no" ] && return
-    ___gt_put_json "/v5/repos/${owner_repo}/clear" && ui tf "true" "Successfully clear ${owner_repo}" && return
-    gt_log error "clear repo failure: $owner_repo"
+    ______x_cmd_gt_put_json "/v5/repos/${owner_repo}/clear" && ui tf "true" "Successfully clear ${owner_repo}" && return
+    ___x_cmd_gt_log error "clear repo failure: $owner_repo"
 }
 
-gt_repo_review(){
+___x_cmd_gt_repo_review(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
@@ -312,6 +312,6 @@ options:
     --testers_number      "number of people tested"     <>:number="1"
 '
     param:run
-    gt_param_init_owner_repo
-    ___gt_put_json "/v5/repos/${owner_repo}/reviewer" assignees testers assignees_number testers_number
+    ___x_cmd_gt_param_init_owner_repo
+    ______x_cmd_gt_put_json "/v5/repos/${owner_repo}/reviewer" assignees testers assignees_number testers_number
 }
diff --git a/lib/repo_release b/lib/repo_release
--- a/lib/repo_release
+++ b/lib/repo_release
@@ -1,9 +1,9 @@
 # shellcheck shell=sh
 # shellcheck disable=SC2039,3043
 
-gt_repo_release(){
+___x_cmd_gt_repo_release(){
     param:dsl    <<A
-subcommands:
+subcmd:
     ls              "list repo's release"
     create          "create repo release"
     update          "update release information"
@@ -15,18 +15,18 @@ A
     param:run
 
     if [ -z "$PARAM_SUBCMD" ]; then
-        gt_log error "Command Not Found. Show help."
+        ___x_cmd_gt_log error "Command Not Found. Show help."
         return 0
     fi
     
-    "gt_repo_release_${PARAM_SUBCMD}" "$@"
+    "___x_cmd_gt_repo_release_${PARAM_SUBCMD}" "$@"
 }
 
 ############################
 # Section 10: Release
 ############################
 # https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoReleases
-gt_repo_release_ls() {
+___x_cmd_gt_repo_release_ls() {
     param:scope     "gitee/$O"
     param:dsl    '
 type:
@@ -37,12 +37,12 @@ options:
 '
     param:run
 
-    gt_param_init_owner_repo
+    ___x_cmd_gt_param_init_owner_repo
 
-    ___gt_get "/v5/repos/${owner_repo}/releases" page per_page direction  
+    ______x_cmd_gt_get "/v5/repos/${owner_repo}/releases" page per_page direction  
 }
 
-gt_repo_get_release_by_tag() {
+___x_cmd_gt_repo_get_release_by_tag() {
     param:scope     "gitee/$O"
     param:dsl    '
 options:
@@ -50,13 +50,13 @@ options:
     #2|--tag           "tag name"              <>
 '
     param:run
-    gt_param_init_owner_repo
+    ___x_cmd_gt_param_init_owner_repo
 
-    ___gt_get "/v5/repos/${owner_repo}/releases/tags/${tag}"  
+    ______x_cmd_gt_get "/v5/repos/${owner_repo}/releases/tags/${tag}"  
 }
 
 # https://gitee.com/api/v5/swagger#/postV5ReposOwnerRepoReleases
-gt_repo_release_create() {
+___x_cmd_gt_repo_release_create() {
     local O="${O:-GITEE_DEFAULT}"
 
     param:scope  "gitee/$O"
@@ -71,30 +71,30 @@ options:
 '
     param:run
 
-    gt_param_init_owner_repo
+    ___x_cmd_gt_param_init_owner_repo
 
-    ___gt_post_json "/v5/repos/${owner_repo}/releases" \
+    ______x_cmd_gt_post_json "/v5/repos/${owner_repo}/releases" \
         tag_name="$tag" name body prerelease target_commitish  
 }
 
 
 # Assume pr and owner_repo are environments
-___gt_repo_release_init_owner_repo_and_release_main(){
+______x_cmd_gt_repo_release_init_owner_repo_and_release_main(){
     local release_id=${release##*/}
     owner_repo=${release%$release_id}
 
-    owner_repo="$(___gt_param_normalize_repo "$owner_repo")"
+    owner_repo="$(______x_cmd_gt_param_normalize_repo "$owner_repo")"
     release="${release_id}"
 }
 
-alias ___gt_repo_release_init_owner_repo_and_release="
+alias ______x_cmd_gt_repo_release_init_owner_repo_and_release="
     local owner_repo
-    ___gt_repo_release_init_owner_repo_and_release_main || return
+    ______x_cmd_gt_repo_release_init_owner_repo_and_release_main || return
 "
 
 
 # https://gitee.com/api/v5/swagger#/patchV5ReposOwnerRepoReleasesId
-gt_repo_release_update() {
+___x_cmd_gt_repo_release_update() {
     local O="${O:-GITEE_DEFAULT}"
     param:scope  "gitee/$O"
     param:dsl    '
@@ -107,12 +107,12 @@ options:
 '
     param:run
 
-    ___gt_repo_release_init_owner_repo_and_release
-    ___gt_patch_json "/v5/repos/${owner_repo}/releases/${release}" \
+    ______x_cmd_gt_repo_release_init_owner_repo_and_release
+    ______x_cmd_gt_patch_json "/v5/repos/${owner_repo}/releases/${release}" \
         tag_name="$tag" name body prerelease  
 }
 
-gt_repo_release_delete() {
+___x_cmd_gt_repo_release_delete() {
     local O="${O:-GITEE_DEFAULT}"
     param:scope  "gitee/$O"
     param:dsl    '
@@ -121,11 +121,11 @@ options:
 '
     param:run
 
-    ___gt_repo_release_init_owner_repo_and_release
-    ___gt_delete "/v5/repos/${owner_repo}/releases/$release"
+    ______x_cmd_gt_repo_release_init_owner_repo_and_release
+    ______x_cmd_gt_delete "/v5/repos/${owner_repo}/releases/$release"
 }
 
-gt_repo_release_latest() {
+___x_cmd_gt_repo_release_latest() {
     local O="${O:-GITEE_DEFAULT}"
     param:scope     "gitee/$O"
     param:dsl    '
@@ -134,11 +134,11 @@ options:
 '
     param:run
 
-    gt_param_init_owner_repo
-    ___gt_get "/v5/repos/${owner_repo}/releases/latest"  
+    ___x_cmd_gt_param_init_owner_repo
+    ______x_cmd_gt_get "/v5/repos/${owner_repo}/releases/latest"  
 }
 
-gt_repo_release_info() {
+___x_cmd_gt_repo_release_info() {
     local O="${O:-GITEE_DEFAULT}"
     param:scope     "gitee/$O"
     param:dsl    '
@@ -147,30 +147,30 @@ options:
 '
     param:run
 
-    ___gt_repo_release_init_owner_repo_and_release
-    ___gt_get "/v5/repos/${owner_repo}/releases/${release}"  
+    ______x_cmd_gt_repo_release_init_owner_repo_and_release
+    ______x_cmd_gt_get "/v5/repos/${owner_repo}/releases/${release}"  
 }
 
 
 # Section : attachment
 
-gt_repo_release_attachment(){
+___x_cmd_gt_repo_release_attachment(){
     param:dsl    <<A
-subcommands:
+subcmd:
     ls              "list release's attachment"
     add             "upload attachment"
     rm              "delete attachment"
 A
 
     if [ -n "$PARAM_SUBCMD" ]; then
-        gt_log error "Command Not Found. Show help."
+        ___x_cmd_gt_log error "Command Not Found. Show help."
         return 0
     fi
 
-    "gt_repo_release_attachment_${PARAM_SUBCMD}" "$@"
+    "___x_cmd_gt_repo_release_attachment_${PARAM_SUBCMD}" "$@"
 }
 
-gt_repo_release_attachment_ls() {
+___x_cmd_gt_repo_release_attachment_ls() {
 
     local O="${O:-GITEE_DEFAULT}"
 
@@ -181,11 +181,11 @@ options:
 '
     param:run
 
-    ___gt_repo_release_init_owner_repo_and_release
+    ______x_cmd_gt_repo_release_init_owner_repo_and_release
 }
 
 # Provide multiple files
-gt_repo_release_attachment_add() {
+___x_cmd_gt_repo_release_attachment_add() {
 
     local O="${O:-GITEE_DEFAULT}"
     param:scope     "gitee/$O"
@@ -195,11 +195,11 @@ options:
 '
     param:run
 
-    ___gt_repo_release_init_owner_repo_and_release
+    ______x_cmd_gt_repo_release_init_owner_repo_and_release
 }
 
 # Delete the file in attachment list
-gt_repo_release_attachment_del() {
+___x_cmd_gt_repo_release_attachment_del() {
 
     local O="${O:-GITEE_DEFAULT}"
 
@@ -210,7 +210,7 @@ options:
 '
     param:run
 
-    ___gt_repo_release_init_owner_repo_and_release
+    ______x_cmd_gt_repo_release_init_owner_repo_and_release
 }
 
 # EndSection
