Squashed 'mod/gh/' changes from 1d3ecccb..cb2ceff0
cb2ceff0 config token update
20a47b5f add gh token Set up multiple questions
7727b89a param fix
fc633108 token update

git-subtree-dir: mod/gh
git-subtree-split: cb2ceff03312148af745009163fa6109d6dfa299

diff --git a/lib/token b/lib/token
--- a/lib/token
+++ b/lib/token
@@ -4,24 +4,36 @@
 # Synchronized token in the x-bash user profile.
 
 # shellcheck disable=SC2120
-___x_cmd_gh_token() {
+
+___x_cmd_gh_token(){
     param:void
     local O="${O:-GITHUB_DEFAULT}"
     if [ $# -eq 0 ]; then
-        ___x_cmd_gh_default get "github_$O" "token" 2>/dev/null || return 1
-    else
-        if [ "$1" = "false" ];then
-            shift
-            ___x_cmd_gh_default put "github_$O" "token" "$@"
-          else
-            ___x_cmd_gh_default put "github_$O" "token" "$@"
-            ___x_cmd_gh_config_save
+        ___x_cmd_gh_default get "github_$O" "token"  || return 1
+        return 0
+      else
+        [ $# -gt 1 ] && gh_log warn "Multiple tokens cannot be set at the same time,Set only the first token"
+        local tmp_token
+        tmp_token="$(___x_cmd_gh_default get "github_$O" "token")"
+
+        if [ "$1" = "$tmp_token" ]; then
+            gh_log info "Consistent with the original token"
+            return 0
         fi
+
+        http "@___x_cmd_gh_$O" header put Authorization "token $1"
+        local user
+        user="$(___x_cmd_gh_current_owner)"
+        if [ -z "$user" ]; then
+            http "@___x_cmd_gh_$O" header put Authorization "token $tmp_token"
+            gh_log error "set default token $1 fail,Please check if it is a valid token"
+            return 1
+        fi
+        ___x_cmd_gh_default put "github_$O" "token" "$1"
+        ___x_cmd_gh_default put "github_$O" "owner" "$user"
+        ___x_cmd_ui_tf "true" "set default token successfully,The default user is $user"
+        ___x_cmd_gh_config_save
+        return 0
     fi
 
-    if [ -n "$1" ]; then
-        # setter
-        local token="$1"
-        http "@___x_cmd_gh_${O:-GITHUB_DEFAULT}" header put Authorization "token $token"
-    fi
 }
