Squashed 'mod/gh/' changes from 9cc05dd0..855e546d
855e546d ...
ac09e3c1 token

git-subtree-dir: mod/gh
git-subtree-split: 855e546d98bfd39660d776c4763150b8236c648f

diff --git a/lib/token b/lib/token
--- a/lib/token
+++ b/lib/token
@@ -38,3 +38,52 @@ ___x_cmd_gh_token(){
     fi
 
 }
+
+____x_cmd_gh_auth(){
+    param:dsl       '
+subcommand:
+    login:      "Authenticate with a GitHub host"
+    logout:     "Log out of a GitHub host"
+    refresh:    "Refresh stored authentication credentials"
+    setup-git:  "Configure git to use GitHub CLI as a credential helper"
+    status:     "View authentication status"
+'
+    param:run
+
+    if [ -z "${PARAM_SUBCMD}" ]; then
+        gh_log warn "Subcmd Not Found."
+        ____x_cmd_gh_auth _param_help_doc
+        return 1
+    fi
+    "____x_cmd_gh_auth_${PARAM_SUBCMD}" "$@"
+}
+
+____x_cmd_gh_auth_log(){
+    param:void
+    local client_id=3d0f25caedcc0e18c985
+    local scope
+    local grant_type="urn:ietf:params:oauth:grant-type:device_code"
+    # TODO:table scope
+    [ "$scope" = "all" ] && scope="repo workflow write:packages delete:packages admin:org admin:public_key admin:repo_hook admin:org_hook gist notifications user delete_repo write:discussion admin:enterprise admin:gpg_key"
+
+    http "@____x_cmd_log_GITHUB" header put "Accept" "application/json"
+    local codeData
+    local device_code
+    local user_code
+    local verification_uri
+    export all_proxy=socks5://192.168.31.117:1086
+    codeData="$(http "@____x_cmd_log_GITHUB" post json "https://github.com/login/device/code" client_id="$client_id" scope="$scope")"
+    ___x_cmd_gh_json_query_rename "$codeData" device_code=.device_code user_code=.user_code verification_uri=.verification_uri
+
+    gh_log info "$user_code"
+    http browse "$verification_uri"
+    local gh_status="authorization_pending"
+    local data
+    while [ "$gh_status" = "authorization_pending" ];do
+        data="$(http "@____x_cmd_log_GITHUB" post json https://github.com/login/oauth/access_token client_id="$client_id" grant_type="$grant_type" device_code="$device_code")"
+        echo "$data">>a.json
+        ___x_cmd_gh_json_query_rename "$data" gh_status=.error
+        sleep 10
+    done
+    # ___x_cmd_gh_token "$(___x_cmd_gh_json_query "$data" .access_token || return 1)"
+}
