Squashed 'mod/gt/' changes from 418d48ce..3631dc77
3631dc77 feat(token): add token replace

git-subtree-dir: mod/gt
git-subtree-split: 3631dc7762d70be66564677dcad1f5eb44310c51

diff --git a/lib/token b/lib/token
--- a/lib/token
+++ b/lib/token
@@ -8,21 +8,30 @@ ___x_cmd_gt_token() {
     param:void
     local O="${O:-GITEE_DEFAULT}"
     if [ $# -eq 0 ]; then
-        param_default get "gitee_$O" "token" 2>/dev/null || return 1
+        ___x_cmd_gt_default get "gitee_$O" "token" 2>/dev/null || return 1
+        return 0
     else
-        if [ "$1" = "false" ];then
-            shift
-            param_default put "gitee_$O" "token" "$@"
-          else
-            param_default put "gitee_$O" "token" "$@"
-            ___x_cmd_gt_config_save
-        fi
-    fi
+        [ $# -gt 1 ] && gt_log warn "Multiple tokens cannot be set at the same time,Set only the first token"
+        local tmp_token
+        tmp_token="$(___x_cmd_gt_default get "gitee_$O" "token")"
 
-    if [ -n "$1" ]; then
-        # setter
-        local token="$1"
-        http "@___x_cmd_gt_${O:-GITEE_DEFAULT}" body    put access_token "$token"
-        http "@___x_cmd_gt_${O:-GITEE_DEFAULT}" qs      put access_token "$token"
+        if [ "$1" = "$tmp_token" ];then
+            gt_log info "Consistent with the original token"
+            return 0
+        fi
+
+        http "@___x_cmd_gt_$O" header put Authorization "token $1"
+        local user
+        user="$(___x_cmd_gt_current_owner)"
+        if [ -z "$user" ];then
+            http "@___x_cmd_gh_$O" header put Authorization "token $tmp_token"
+            gt_log error "set default token $1 fail,Please check if it is a valid token"
+            return 1
+        fi
+        ___x_cmd_gt_default put "gitee_$O"  "token" "$1"
+        ___x_cmd_gt_default put "gitee_$O"  "owner" "$user"
+        ___x_cmd_ui_tf "true" "set default token successfully,The default user is $user"
+        ___x_cmd_gt_config_save
+        return 0
     fi
 }
