...

diff --git a/mod/pkg/lib/main b/mod/pkg/lib/main
--- a/mod/pkg/lib/main
+++ b/mod/pkg/lib/main
@@ -1,23 +1,29 @@
 
 
-___x_cmd_pkg_update(){
-    ___x_cmd_pkg___which_p7zip -  # Force Update
-}
+# # Rely on ll or ls
+# # Control the lsversion awk for better showing
+# ___x_cmd_pkg_version(){
+#     ___x_cmd_pkg___all_info "$@" | awk \
+#         -f "$___X_CMD_ROOT_MOD/awk/lib/default.awk" \
+#         -f "$___X_CMD_ROOT_MOD/awk/lib/jqparse.awk" \
+#         -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/util.awk" \
+#         -f "$___X_CMD_ROOT_MOD/awk/pkg.lsversion.awk"
+# }
 
 # Rely on ll or ls
 # Control the lsversion awk for better showing
-___x_cmd_pkg_version(){
-    ___x_cmd_pkg___all_info "$@" | awk \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/default.awk" \
-        -f "$___X_CMD_ROOT_MOD/awk/lib/jqparse.awk" \
-        -f "$___X_CMD_ROOT_MOD/pkg/lib/awk/util.awk" \
-        -f "$___X_CMD_ROOT_MOD/awk/pkg.lsversion.awk"
-}
+# ___x_cmd_pkg_version(){
+#     local pkg_name="${1:?Provide pkg name}"
+#     local osarch="${2:?osarch as filter}"
+#     ___x_cmd_pkg___all_info "${pkg_name}" | awk \
+#         -f "$___X_CMD_ROOT_MOD/awk/lib/default.awk" \
+#         -f "$___X_CMD_ROOT_MOD/awk/lib/jqparse.awk" \
+#         -f "awk/util.awk" \
+#         -f "awk/pkg.lsversion.awk"
+# }
 
-xrc p7zip
-
-___x_cmd_pkg___which_p7zip(){
-    ___x_cmd_ensuredir "$___X_CMD_PKG_RAWPATH"
+___x_cmd_pkg___which_p7zip()(
+    ___x_cmd_mkdirp "$___X_CMD_PKG_RAWPATH"
 
     local p7zip="$___X_CMD_ROOT_TMP/pkg/all.7z"
     if ! ___x_cmd_httpget_gitx x-cmd pkg main "dist/all.7z" "$p7zip" "${1:-3600}"; then # 1-day
@@ -27,11 +33,18 @@ ___x_cmd_pkg___which_p7zip(){
         fi
     fi
 
-    [ "$___X_CMD_HTTPGET_AGE" != 0 ] || (
+    if [ "$___X_CMD_HTTPGET_AGE" = 0 ]; then
         pkg:info "Deflate the all.7z"
         x rmrf "$___X_CMD_PKG_RAWPATH"
-        ___x_cmd_ensuredir "$___X_CMD_PKG_RAWPATH"
-        cd "${p7zip%/*}" && cp all.7z raw/all.7z && cd raw && p7zd x all.7z 1>/dev/null && rm all.7z
-    )
-}
+        ___x_cmd_mkdirp "$___X_CMD_PKG_RAWPATH"
+        if ! cd "${p7zip%/*}" && cp all.7z raw/all.7z && cd raw && x uz all.7z 1>/dev/null && x rmrf all.7z; then
+            x:error "Deflation failure."
+            x rmrf "$p7zip"
+        fi
+    fi
+)
 
+
+___x_cmd_pkg_update(){
+    ___x_cmd_pkg___which_p7zip - || return # Force Update
+}
diff --git a/mod/pkg/lib/mutate/download b/mod/pkg/lib/mutate/download
--- a/mod/pkg/lib/mutate/download
+++ b/mod/pkg/lib/mutate/download
@@ -1,3 +1,4 @@
+# shellcheck    shell=sh            disable=SC2016,SC3043      # xrc
 
 # TODO: Multiple thread
 # TODO: Download Manager and more strategy
@@ -21,10 +22,10 @@ ___x_cmd_pkg_download(){
 
     local url_list
     url_list="$(___x_cmd_pkg___list "$pkg_name" "$version" "$osarch" "url.${___X_CMD_WHICHNET:-_}" )"
-    [ -n "$url_list" ] || {
+    if [ -z "$url_list" ]; then
         pkg:error "Not found url."
         return 1
-    }
+    fi
 
     local file_suffix
     ___x_cmd_pkg___attr "$pkg_name" "$version" "$osarch" file_suffix
@@ -50,10 +51,10 @@ ___x_cmd_pkg_download(){
         # ___x_cmd_httpget "$url" "$ball" || {
         pkg:info "Download $pkg_name $version from $url to $ball"
         # TODO: x curl
-        curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball" || {
+        if ! curl --progress-bar --location --retry-max-time 10 --retry 0 "$url" --output "$ball"; then
             pkg:warn "Fail to download from $url"
             continue
-        }
+        fi
 
         ! ___x_cmd_pkg_download___check_hashsum "$ball" "$md5" "$sha1" "$sha256" "$sha512" || return 0
 
@@ -75,25 +76,20 @@ ___x_cmd_pkg_download_file___from_static_build_and_deflate(){
     pkg:debug "Download static-build. repo: $repo app: $app"
 
     local target="$___X_CMD_PKG_INSTALL_PATH/$repo/$version"
-    x ensuredir "$target" || return 1
+    x mkdirp "$target" || return 1
 
     local osarch
     osarch="${___X_CMD_PKG_OSARCH:-$(___x_cmd_pkg_osarch)}"
     local arch="${osarch#*/}"
     local osname="${osarch%/*}"
 
-    local exe
-    case "$osname" in
-        win)        exe=$app.${osname}.${arch}.exe          ;;
-        *)          exe=$app.${osname}.${arch}              ;;
-    esac
+    local exe="$app.${osname}.${arch}";  [ "$osname" != win ] || exe="${exe}.exe"
 
     # Rely
     if [ ! -f "$target/$exe" ]; then
         pkg:info "Downloading: $repo/$app/$version/$exe.7z to $target"
         if ! ___x_cmd_curl_gitx static-build "${repo}" main "$app/$version/$exe.7z" "$target/$exe.7z"; then
-            pkg:warn "Download failure: $repo/main $app/$version/$exe.7z"
-            pkg:warn "File Not Found. Perhaps the platform is NOT supported: $exe"
+            pkg:warn "Download failure: $repo/main $app/$version/$exe.7z. Perhaps platform unsupported."
             return 1
         fi
 
@@ -124,7 +120,7 @@ ___x_cmd_pkg_download_file___from_static_build_and_deflate(){
                     done
 
                     pkg:info "Using p7zd to decompress: $target/$exe.7z.001"
-                    cat $target/$exe.7z.0* > $exe.7z
+                    cat "$target/$exe".7z.0* > "$exe.7z"
                     p7zd x "$exe.7z" 1>/dev/null 2>/dev/null
                 fi && chmod +x "$exe" \
                     && pkg:info "Finish file decompress and chmod."
