...

diff --git a/mod/gitlab/lib/issue b/mod/gitlab/lib/issue
--- a/mod/gitlab/lib/issue
+++ b/mod/gitlab/lib/issue
@@ -2,13 +2,13 @@
 # shellcheck disable=SC2039,3043
 
 # Should be like this.
-# gt repo issue add el:admin
-# gt repo issue remove user-a
-# gt repo issue add user-b
+# gitlab repo issue add el:admin
+# gitlab repo issue remove user-a
+# gitlab repo issue add user-b
 
-# gt repo issue +el:admin -user-a +user-b
+# gitlab repo issue +el:admin -user-a +user-b
 ___x_cmd_gitlab_issue(){
-    param:scope         ___x_cmd_gt
+    param:scope         ___x_cmd_gitlab
     param:subcmd ___x_cmd_gitlab_issue                  \
         create          "create issue"              \
         update          "update issue"              \
@@ -18,15 +18,15 @@ ___x_cmd_gitlab_issue(){
     param:run
 
     ___x_cmd_gitlab_issue _param_help_doc
-    gt_log warn "Subcmd Not Found."
+    gitlab_log warn "Subcmd Not Found."
     return 1
 }
 
 
 # shellcheck disable=SC2154,SC2034
-# https://gitee.com/api/v5/swagger#/postV5ReposOwnerIssues
+# https://gitee.com/api/swagger#/postV5ReposOwnerIssues
 ___x_cmd_gitlab_issue_create(){
-    param:scope         ___x_cmd_gt
+    param:scope         ___x_cmd_gitlab
     param:dsl      '
 options:
     --title         "title"                                                              <>
@@ -43,10 +43,10 @@ options:
     param:run
 
     local security="${security:-false}"
-    local gen_gt_json
-    gen_gt_json="$(param:option2json security_hole=^^security issue_type=type -security -type)"
+    local gen_gitlab_json
+    gen_gitlab_json="$(param:option2json security_hole=^^security issue_type=type -security -type)"
 
-    ___x_cmd_gitlab_http post "/v5/repos/${repo##*/}/issues" "$gen_gt_json" | \
+    ___x_cmd_gitlab_http post "/repos/${repo##*/}/issues" "$gen_gitlab_json" | \
     {
         ___x_cmd_git_json_query_rename id=.number title=.title html_url=.html_url
         if [ -n "$id" ]; then
@@ -60,9 +60,9 @@ options:
 }
 
 # shellcheck disable=SC2154,SC2034
-# https://gitee.com/api/v5/swagger#/patchV5ReposOwnerIssuesNumber
+# https://gitee.com/api/swagger#/patchV5ReposOwnerIssuesNumber
 ___x_cmd_gitlab_issue_update(){
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 type:
     State = open progressing closed
@@ -82,10 +82,10 @@ options:
     param:run
 
     local security="${security:-false}"
-    local gen_gt_json
-    gen_gt_json="$(param:option2json issue_type=type security_hole=^^security -security -type)"
+    local gen_gitlab_json
+    gen_gitlab_json="$(param:option2json issue_type=type security_hole=^^security -security -type)"
 
-    ___x_cmd_gitlab_http patch "/v5/repos/${owner##*/}/issues/${number}" "$gen_gt_json" | \
+    ___x_cmd_gitlab_http patch "/repos/${owner##*/}/issues/${number}" "$gen_gitlab_json" | \
     {
         ___x_cmd_git_json_query_rename id=.number state=.state html_url=.html_url
         if [ -n "$id" ]; then
@@ -99,9 +99,9 @@ options:
 }
 
 # shellcheck disable=SC2154
-# https://gitee.com/api/v5/swagger#/getV5ReposOwnerIssuesNumberOperateLogs
+# https://gitee.com/api/swagger#/getV5ReposOwnerIssuesNumberOperateLogs
 ___x_cmd_gitlab_issue_logs(){
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 options:
     --repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
@@ -111,17 +111,17 @@ options:
     param:run
     ___x_cmd_gitlab_param_init_owner_repo
 
-    local ___gt_error_msg="Couldn't find any data by: $repo $number"
-    ___gt_ui_mutual ___x_cmd_gitlab_http get "/v5/repos/${owner_repo##*/}/issues/${number}/operate_logs" repo sort <<A
+    local ___gitlab_error_msg="Couldn't find any data by: $repo $number"
+    ___gitlab_ui_mutual ___x_cmd_gitlab_http get "/repos/${owner_repo##*/}/issues/${number}/operate_logs" repo sort <<A
         ___ui_table_json Time=.created_at User=.user.login Type=.action_type Content=.content -- \$@
 A
 }
 
 # shellcheck shell=sh
 # shellcheck disable=SC2039,3043,SC2154
-# https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoIssuesComments
+# https://gitee.com/api/swagger#/getV5ReposOwnerRepoIssuesComments
 ___x_cmd_gitlab_repo_issue(){
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 type:
     State = open progressing closed rejected all
@@ -142,16 +142,16 @@ options:
     param:run
     ___x_cmd_gitlab_param_init_owner_repo
 
-    local gen_gt_json
-    gen_gt_json="$(param:option2json -repo -page -per_page)"
+    local gen_gitlab_json
+    gen_gitlab_json="$(param:option2json -repo -page -per_page)"
 
     if [ -z "$number" ]; then
-        ___gt_ui_mutual ___x_cmd_gitlab_get_multi "/v5/repos/${owner_repo}/issues" state labels milestone \
+        ___gitlab_ui_mutual ___x_cmd_gitlab_get_multi "/repos/${owner_repo}/issues" state labels milestone \
             assignee creator program sort direction number <<A
         IssueNumber=.number Title=.title State=.issue_state Assigner=.assignee.name Body=.body -- \$@
 A
     else
-        ___x_cmd_gitlab_http get "/v5/repos/${owner_repo}/issues/${number}" | \
+        ___x_cmd_gitlab_http get "/repos/${owner_repo}/issues/${number}" | \
         {
             ___x_cmd_gitlab_json_query_rename "$data" id=.number title=.title state=.state assignee=.assignee.name
             if [ -n "$id" ]; then
@@ -167,9 +167,9 @@ A
 }
 
 # shellcheck disable=SC2154
-# https://gitee.com/api/v5/swagger#/getV5OrgsOrgIssues
+# https://gitee.com/api/swagger#/getV5OrgsOrgIssues
 ___x_cmd_gitlab_org_issue(){
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 options:
     --org           "organization path"                            <>
@@ -183,11 +183,11 @@ options:
 '
     param:run
 
-    local gen_gt_json
-    gen_gt_json="$(param:option2json -org -page -per_page)"
+    local gen_gitlab_json
+    gen_gitlab_json="$(param:option2json -org -page -per_page)"
 
-    local ___gt_error_msg="Couldn't find any data by: ${org}"
-    ___gt_ui_mutual ___x_cmd_gitlab_get_multi "/v5/orgs/${org##*/}/issues" filter state labels \
+    local ___gitlab_error_msg="Couldn't find any data by: ${org}"
+    ___gitlab_ui_mutual ___x_cmd_gitlab_get_multi "/orgs/${org##*/}/issues" filter state labels \
         sort direction since page per_page <<A
         ___ui_table_json IssueNumber=.number State=.issue_state Assigner=.assignee.name \
             Repository=.repository.full_name Type=.issue_type Title=.title Url=.html_url -- \$@
@@ -195,9 +195,9 @@ A
 }
 
 # shellcheck disable=SC2154
-# https://gitee.com/api/v5/swagger#/getV5EnterprisesEnterpriseIssues
+# https://gitee.com/api/swagger#/getV5EnterprisesEnterpriseIssues
 ___x_cmd_gitlab_enterprise_issue(){
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 options:
     --enterprise    "enterprise path"                              <>
@@ -215,8 +215,8 @@ options:
 '
     param:run
 
-    local ___gt_error_msg="Couldn't find any data by: ${enterprise}"
-    ___gt_ui_mutual ___x_cmd_gitlab_get_multi "/v5/enterprises/${enterprise##*/}/issues" filter state labels sort direction \
+    local ___gitlab_error_msg="Couldn't find any data by: ${enterprise}"
+    ___gitlab_ui_mutual ___x_cmd_gitlab_get_multi "/enterprises/${enterprise##*/}/issues" filter state labels sort direction \
         milestone assignee creator program <<A
         ___ui_table_json IssueNumber=.number State=.issue_state Assigner=.assignee.name AssignerMarkName=.assignee.remark \
             Repository=.repository.full_name Type=.issue_type Title=.title Url=.html_url -- \$@
@@ -226,7 +226,7 @@ A
 # Section : comment
 
 ___x_cmd_gitlab_issue_comment(){
-    param:scope         ___x_cmd_gt
+    param:scope         ___x_cmd_gitlab
     param:subcmd ___x_cmd_gitlab_issue_comment          \
         ls              "list all comment"          \
         create          "create a comment"          \
@@ -236,15 +236,15 @@ ___x_cmd_gitlab_issue_comment(){
     param:run
     if [ -z "$PARAM_SUBCMD" ]; then
         ___x_cmd_gitlab_issue _param_help_doc
-        gt_log warn "subcmd not found. show help." >&2
+        gitlab_log warn "subcmd not found. show help." >&2
         return 1
     fi
     "___x_cmd_gitlab_issue_comment_$PARAM_SUBCMD" "$@"
 }
 
-# https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoIssuesNumberComments
+# https://gitee.com/api/swagger#/getV5ReposOwnerRepoIssuesNumberComments
 ___x_cmd_gitlab_issue_comment_ls(){
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 options:
     --number        "issue number"                                                       <>
@@ -257,16 +257,16 @@ options:
     param:run
     ___x_cmd_gitlab_param_init_owner_repo
 
-    local ___gt_error_msg="Couldn't find any data by: ${owner_repo}"
-    ___gt_ui_mutual ___x_cmd_gitlab_get_multi "/v5/repos/${owner_repo}/issues/$number/comments" since order <<A
+    local ___gitlab_error_msg="Couldn't find any data by: ${owner_repo}"
+    ___gitlab_ui_mutual ___x_cmd_gitlab_get_multi "/repos/${owner_repo}/issues/$number/comments" since order <<A
         ___ui_table_json CommitId=.id IssueNumber=.target.issue.number Title=.target.issue.title User=.user.login Body=.body -- \$@
 A
 }
 
 # shellcheck disable=SC2086,SC2154
-# https://gitee.com/api/v5/swagger#/postV5ReposOwnerRepoIssuesNumberComments
+# https://gitee.com/api/swagger#/postV5ReposOwnerRepoIssuesNumberComments
 ___x_cmd_gitlab_issue_comment_create(){
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 options:
     --repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
@@ -275,10 +275,10 @@ options:
 '
     param:run
 
-    local gen_gt_json
-    gen_gt_json="$(param:option2json -repo -number)"
+    local gen_gitlab_json
+    gen_gitlab_json="$(param:option2json -repo -number)"
 
-    ___x_cmd_gitlab_http post "/v5/repos/${owner##*/}/${repo##*/}/issues/$number/comments" "$gen_gt_json" | \
+    ___x_cmd_gitlab_http post "/repos/${owner##*/}/${repo##*/}/issues/$number/comments" "$gen_gitlab_json" | \
     {
         ___x_cmd_git_json_query_rename "$data" id=.target.issue.number title=.target.issue.title body=.body
         if [ -n "$id" ]; then
@@ -291,9 +291,9 @@ options:
     }
 }
 
-# https://gitee.com/api/v5/swagger#/patchV5ReposOwnerRepoIssuesCommentsId
+# https://gitee.com/api/swagger#/patchV5ReposOwnerRepoIssuesCommentsId
 ___x_cmd_gitlab_issue_comment_update(){
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 options:
     --repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
@@ -301,10 +301,10 @@ options:
     --body          "The contents of the comment"                                        <>
 '
     param:run
-    local gen_gt_json
-    gen_gt_json="$(param:option2json -repo -id)"
+    local gen_gitlab_json
+    gen_gitlab_json="$(param:option2json -repo -id)"
 
-    ___x_cmd_gitlab_http patch "/v5/repos/${owner##*/}/${repo##*/}/issues/comments/${id}" "$(param:option2json)" | \
+    ___x_cmd_gitlab_http patch "/repos/${owner##*/}/${repo##*/}/issues/comments/${id}" "$(param:option2json)" | \
     {
         ___x_cmd_git_json_query_rename "$data" id=.target.issue.number title=.target.issue.title body=.body
         if [ -n "$id" ]; then
@@ -318,9 +318,9 @@ options:
 }
 
 # shellcheck disable=SC2181
-# https://gitee.com/api/v5/swagger#/deleteV5ReposOwnerRepoIssuesCommentsId
+# https://gitee.com/api/swagger#/deleteV5ReposOwnerRepoIssuesCommentsId
 ___x_cmd_gitlab_issue_comment_del(){
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 options:
     --repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
@@ -329,7 +329,7 @@ options:
     param:run
     ___x_cmd_gitlab_param_init_owner_repo
     # TODO:http handle，delete repo return data is null.Status: 204 No Content
-    if ___x_cmd_gitlab_http delete "/v5/repos/${owner_repo}/issues/comments/${id}" >/dev/null; then
+    if ___x_cmd_gitlab_http delete "/repos/${owner_repo}/issues/comments/${id}" >/dev/null; then
         ___x_cmd_ui_tf true  "Deleted comment successfully"
     else
         ___x_cmd_ui_tf false "Deleting comment failure by ${owner_repo} $id."
diff --git a/mod/gitlab/lib/repo/main b/mod/gitlab/lib/repo/main
--- a/mod/gitlab/lib/repo/main
+++ b/mod/gitlab/lib/repo/main
@@ -2,7 +2,7 @@
 # shellcheck disable=SC2039,3043
 
 ___x_cmd_gitlab_repo(){
-    param:scope         ___x_cmd_gt
+    param:scope         ___x_cmd_gitlab
     param:subcmd ___x_cmd_gitlab_repo                                       \
         create          "Create repo"                                   \
         ls              "List repo of owner"                            \
@@ -17,15 +17,15 @@ ___x_cmd_gitlab_repo(){
     param:run
 
     ___x_cmd_gitlab_repo _param_help_doc
-    gt_log warn "Subcmd Not Found."
+    gitlab_log warn "Subcmd Not Found."
     return 1
 }
 
 # Section: create
 # shellcheck disable=SC2154
-# https://gitee.com/api/v5/swagger#/postV5UserRepos
+# https://gitee.com/api/swagger#/postV5UserRepos
 ___x_cmd_gitlab_repo_create(){
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 option:
     #n                      "repo names"                    <>:RepoName
@@ -42,7 +42,7 @@ option:
     --no_auto_init          "Not auto init README"
 '
     param:run
-    [ $# -ne 0 ] || { gt_log error "Please provide repo name"; return 1; }
+    [ $# -ne 0 ] || { gitlab_log error "Please provide repo name"; return 1; }
 
     local private
     case "$access" in
@@ -50,15 +50,15 @@ option:
         private)    private=true    ;;
     esac
     local name="%%name%%"
-    local gen_gt_json
-    gen_gt_json="$(
+    local gen_gitlab_json
+    gen_gitlab_json="$(
         param:option2json +name +private -access \
             has_issues=^no_issue        has_wiki=^no_wiki \
             can_comment=^no_comment     auto_init=^^no_auto_init)"
 
     for name in "$@"; do
-        printf "%s" "${gen_gt_json}" | sed s/%%name%%/"${name##%/}"/g | \
-            ___x_cmd_gitlab_http post "/v5/user/repos" - | \
+        printf "%s" "${gen_gitlab_json}" | sed s/%%name%%/"${name##%/}"/g | \
+            ___x_cmd_gitlab_http post "/user/repos" - | \
             ___x_cmd_gitlab_repo_create_status_handler
     done
 }
@@ -81,11 +81,11 @@ ___x_cmd_gitlab_repo_create_status_handler(){
 
 # ORGANIZATION NAME
 # shellcheck disable=SC2154,SC2034
-# https://gitee.com/api/v5/swagger#/postV5OrgsOrgRepos
+# https://gitee.com/api/swagger#/postV5OrgsOrgRepos
 ___x_cmd_gitlab_org_repo_create(){
     # TODO: I don't know what does path means for an organization repo
     # path is null default repo name as path
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 option:
     #n                      "repo names"
@@ -111,16 +111,16 @@ option:
     esac
 
     local name="%%name%%"
-    local gen_gt_json
-    gen_gt_json="$(
+    local gen_gitlab_json
+    gen_gitlab_json="$(
         param:option2json +name +private -access \
             has_issues=^no_issue            has_wiki=^no_wiki \
             can_comment=^no_comment         auto_init=^^no_auto_init )"
 
     # TODO: owner may be personal
     for name in "$@"; do
-        printf "%s" "${gen_gt_json}" | sed s/%%name%%/"${name##%/}"/g | \
-            ___x_cmd_gitlab_http post "/v5/orgs/$org/repos" - | \
+        printf "%s" "${gen_gitlab_json}" | sed s/%%name%%/"${name##%/}"/g | \
+            ___x_cmd_gitlab_http post "/orgs/$org/repos" - | \
             ___x_cmd_gitlab_org_repo_create_status_handler
     done
 }
@@ -140,10 +140,10 @@ ___x_cmd_gitlab_org_repo_create_status_handler(){
     fi
 }
 
-# https://gitee.com/api/v5/swagger#/postV5EnterprisesEnterpriseRepos
+# https://gitee.com/api/swagger#/postV5EnterprisesEnterpriseRepos
 # shellcheck disable=SC2154,SC2034
 ___x_cmd_gitlab_enterprise_repo_create(){
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 type:
     Access  =   private public innerSource
@@ -174,15 +174,15 @@ option:
     esac
     local name="%%name%%"
     local outsourced="${outsourced:-false}"
-    local gen_gt_json
-    gen_gt_json="$(
+    local gen_gitlab_json
+    gen_gitlab_json="$(
         param:option2json +name +private -access \
         has_issues=^no_issue            has_wiki=^no_wiki              outsourced=^^outsourced \
         can_comment=^no_comment         auto_init=^^no_auto_init)"
 
     for name in "$@"; do
-        printf "%s" "${gen_gt_json}" | sed s/%%name%%/"${name##%/}"/g | \
-            ___x_cmd_gitlab_http post "/v5/enterprises/${enterprise##*/}/repos" - | \
+        printf "%s" "${gen_gitlab_json}" | sed s/%%name%%/"${name##%/}"/g | \
+            ___x_cmd_gitlab_http post "/enterprises/${enterprise##*/}/repos" - | \
             ___x_cmd_gitlab_enterprise_repo_create_status_handler
     done
     return 0
@@ -222,9 +222,9 @@ ___x_cmd_gitlab_repo_ls(){
 # Section: update
 
 # shellcheck disable=SC2154,SC2034
-# TODO: https://gitee.com/api/v5/swagger#/patchV5ReposOwnerRepo need to design
+# TODO: https://gitee.com/api/swagger#/patchV5ReposOwnerRepo need to design
 ___x_cmd_gitlab_repo_update(){
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 type:
     Access  =   public private ""
@@ -246,7 +246,7 @@ options:
     --no_lightweight_pr     "Provide lightweight pr"
 '
     param:run
-    [ $# -eq 0 ] && gt_log error "Repo name is empty" && return 1
+    [ $# -eq 0 ] && gitlab_log error "Repo name is empty" && return 1
 
     local private
     case "$access" in
@@ -254,8 +254,8 @@ options:
         private)    private=true ;;
     esac
     [ -z "$name" ] && local name="${repo##*/}"
-    local gen_gt_json
-    gen_gt_json="$(
+    local gen_gitlab_json
+    gen_gitlab_json="$(
         param:option2json +repo +private -access \
             has_issues=^no_issue                        has_wiki=^no_wiki \
             can_comment=^no_comment                     security_hole_enabled=^no_security_hole \
@@ -263,7 +263,7 @@ options:
             no_online_edit=^no_online_edit)"
 
     ___x_cmd_gitlab_param_init_owner_repo
-    printf "%s" "${gen_gt_json}" | ___x_cmd_gitlab_http patch "/v5/repos/${owner_repo}" - | \
+    printf "%s" "${gen_gitlab_json}" | ___x_cmd_gitlab_http patch "/repos/${owner_repo}" - | \
         ___x_cmd_gitlab_repo_update_status_handler
 }
 
@@ -285,9 +285,9 @@ ___x_cmd_gitlab_repo_update_status_handler(){
 
 # Section: info
 # shellcheck disable=SC2154
-# https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepo
+# https://gitee.com/api/swagger#/getV5ReposOwnerRepo
 ___x_cmd_gitlab_repo_info(){
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 options:
     #1|--repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
@@ -296,7 +296,7 @@ options:
 
     ___x_cmd_gitlab_param_init_owner_repo
 
-    ___x_cmd_gitlab_http get "/v5/repos/${owner_repo}" | ___x_cmd_gitlab_repo_info_status_handler
+    ___x_cmd_gitlab_http get "/repos/${owner_repo}" | ___x_cmd_gitlab_repo_info_status_handler
 }
 
 # shellcheck disable=SC2154
@@ -317,11 +317,11 @@ ___x_cmd_gitlab_repo_info_status_handler() {
 # EndSection
 
 # Section: del & clear
-# https://gitee.com/api/v5/swagger#/deleteV5ReposOwnerRepo
+# https://gitee.com/api/swagger#/deleteV5ReposOwnerRepo
 # shellcheck disable=SC2181,SC2154
 ___x_cmd_gitlab_repo_rm(){
     # TODO: -y force del
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 options:
     #n      "Provide repo path list"    <>
@@ -332,7 +332,7 @@ options:
     for i in "$@"; do
         ___x_cmd_gitlab_param_normalize_repo "$i"
         # TODO:http handle，delete repo return data is null.Status: 204 No Content
-        if ___x_cmd_gitlab_http delete "/v5/repos/$owner_repo" >/dev/null; then
+        if ___x_cmd_gitlab_http delete "/repos/$owner_repo" >/dev/null; then
             ___x_cmd_ui_tf true  "Deleting repo $i successfully"
         else
             ___x_cmd_ui_tf false "Deleting repo failure: $i. Probably because it desn't exists."
@@ -342,9 +342,9 @@ options:
 }
 
 # shellcheck disable=SC2181
-# https://gitee.com/api/v5/swagger#/putV5ReposOwnerRepoClear
+# https://gitee.com/api/swagger#/putV5ReposOwnerRepoClear
 ___x_cmd_gitlab_repo_clear(){
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 options:
     #1|--repo          "Provide owner name and repo path.(default:the current user repo)"   <>:RepoName
@@ -354,7 +354,7 @@ options:
     ___x_cmd_gitlab_param_init_owner_repo
 
     # TODO:http handle，delete repo return data is null.Status: 204 No Content
-    if ___x_cmd_gitlab_http put "/v5/repos/${owner_repo}/clear" >/dev/null; then
+    if ___x_cmd_gitlab_http put "/repos/${owner_repo}/clear" >/dev/null; then
         ___x_cmd_ui_tf true   "Clearing repo ${owner_repo} successfully"
     else
         ___x_cmd_ui_tf false  "Clearing repo failure: ${owner_repo}"
@@ -366,9 +366,9 @@ options:
 # Section: pr review config
 
 # shellcheck disable=SC2154,SC2181
-# https://gitee.com/api/v5/swagger#/putV5ReposOwnerRepoReviewer
+# https://gitee.com/api/swagger#/putV5ReposOwnerRepoReviewer
 ___x_cmd_gitlab_repo_review(){
-    param:scope     ___x_cmd_gt
+    param:scope     ___x_cmd_gitlab
     param:dsl       '
 options:
     #1|--repo             "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
@@ -379,10 +379,10 @@ options:
 '
     param:run
     ___x_cmd_gitlab_param_init_owner_repo
-    local gen_gt_json
-    gen_gt_json="$(param:option2json)"
+    local gen_gitlab_json
+    gen_gitlab_json="$(param:option2json)"
 
-    ___x_cmd_gitlab_http put "/v5/repos/${owner_repo}/reviewer" "$gen_gt_json" | ___x_cmd_gitlab_repo_review_status_handler
+    ___x_cmd_gitlab_http put "/repos/${owner_repo}/reviewer" "$gen_gitlab_json" | ___x_cmd_gitlab_repo_review_status_handler
 }
 
 # shellcheck disable=SC2154
diff --git a/mod/gitlab/lib/token b/mod/gitlab/lib/token
--- a/mod/gitlab/lib/token
+++ b/mod/gitlab/lib/token
@@ -6,33 +6,30 @@
 # shellcheck disable=SC2120
 ___x_cmd_gitlab_token(){
     param:void
-    local O="${O:-___x_cmd_gitlab_GITEE_DEFAULT}"
+    local O="${O:-___x_cmd_gitlab_GITLAB_DEFAULT}"
     if [ $# -eq 0 ]; then
         ___x_cmd_gitlab_config_get "oauth_token"  || return 1
         return 0
     else
-        [ $# -gt 1 ] && gt_log warn "Multiple tokens cannot be set at the same time, Set only the first token"
+        [ $# -gt 1 ] && gitlab_log warn "Multiple tokens cannot be set at the same time, Set only the first token"
         local tmp_token
         tmp_token="$(___x_cmd_gitlab_config_get "oauth_token")"
 
         if [ "$1" = "$tmp_token" ];then
-            gt_log info "Consistent with the original token"
+            gitlab_log info "Consistent with the original token"
             return 0
         fi
 
-        ___x_cmd_http header put Authorization "token $1"
-        ___X_CMD_GITEE_DEFAULT_OWNER=
-        local user
-        user="$(___x_cmd_gitlab_current_owner)"
-        if [ -z "$user" ];then
-            ___x_cmd_http  header put Authorization "token $tmp_token"
-            gt_log error "set default token $1 fail, Please check if it is a valid token"
+        ___x_cmd_http header put "PRIVATE-TOKEN" "$1"
+        ___X_CMD_GITLAB_DEFAULT_OWNER=
+        if ! ___x_cmd_gitlab_current_owner;then
+            ___x_cmd_http  header put "PRIVATE-TOKEN" "$tmp_token"
+            gitlab_log error "set default token $1 fail, Please check if it is a valid token"
             return 1
         fi
-        ___X_CMD_GITEE_DEFAULT_OWNER=$user
-        ___x_cmd_gitlab_config_set "oauth_token" "$1"
-        ___x_cmd_gitlab_config_set "user" "$___X_CMD_GITEE_DEFAULT_OWNER"
-        ___x_cmd_ui_tf "true" "set default token successfully, The default user is $user"
+        ___x_cmd_gitlab_config_set "oauth_token" "$1" 1>/dev/null
+        ___x_cmd_gitlab_config_set "user" "$___X_CMD_GITLAB_DEFAULT_OWNER" 1>/dev/null
+        ___x_cmd_ui_tf "true" "set default token successfully, The default user is $___X_CMD_GITLAB_DEFAULT_OWNER"
         return 0
     fi
 }
diff --git a/mod/gitlab/lib/utils b/mod/gitlab/lib/utils
--- a/mod/gitlab/lib/utils
+++ b/mod/gitlab/lib/utils
@@ -5,12 +5,12 @@
 # Section 2: Wrapping std/http module with object naming changing
 ############################
 ___x_cmd_gitlab_resp_header(){
-    O="${O:-___x_cmd_gitlab_GITEE_DEFAULT}" ___x_cmd_http resp header "$@"
+    O="${O:-___x_cmd_gitlab_GITLAB_DEFAULT}" ___x_cmd_http resp header "$@"
 }
 
 # TODO: Not supported yet
 ___x_cmd_gitlab_resp_body(){
-    O="${O:-___x_cmd_gitlab_GITEE_DEFAULT}" ___x_cmd_http resp body "$@"
+    O="${O:-___x_cmd_gitlab_GITLAB_DEFAULT}" ___x_cmd_http resp body "$@"
 }
 
 ___x_cmd_gitlab_get_multi(){
@@ -30,10 +30,10 @@ ___x_cmd_gitlab_get_multi(){
 }
 
 ___x_cmd_gitlab_http(){
-    if ! O="${O:-___x_cmd_gitlab_GITEE_DEFAULT}" ___x_cmd_http header get Content-Type 1>/dev/null 2>&1; then
-         O="${O:-___x_cmd_gitlab_GITEE_DEFAULT}" ___x_cmd_http header put Content-Type application/json
+    if ! O="${O:-___x_cmd_gitlab_GITLAB_DEFAULT}" ___x_cmd_http header get Content-Type 1>/dev/null 2>&1; then
+         O="${O:-___x_cmd_gitlab_GITLAB_DEFAULT}" ___x_cmd_http header put Content-Type application/json
     fi
-    O="${O:-___x_cmd_gitlab_GITEE_DEFAULT}" ___x_cmd_http "$@"
+    O="${O:-___x_cmd_gitlab_GITLAB_DEFAULT}" ___x_cmd_http "$@"
 }
 
 ############################
@@ -83,7 +83,7 @@ ___x_cmd_gitlab_param_normalize_repo(){
 ### Repo #1
 
 ___x_cmd_gitlab_parse_owner_repo(){
-    local O="${O:-___x_cmd_gitlab_GITEE_DEFAULT}"
+    local O="${O:-___x_cmd_gitlab_GITLAB_DEFAULT}"
     if [ -z "$repo" ]; then
         repo="$(___x_cmd_gitlab_current_repo)"
     fi
@@ -101,7 +101,7 @@ ___x_cmd_gitlab_default(){
     param_default "$@" 2>/dev/null || return 1
 }
 
-___gt_ui_mutual(){
+___gitlab_ui_mutual(){
     if [ ! -t 1 ] || [ -n "$ENFORCE_JSON" ] ; then
         "$@"
     else
@@ -109,7 +109,7 @@ ___gt_ui_mutual(){
         eval "$(cat)"
     fi
 
-    local ___gt_exit_code="$?"
-    [ "$___gt_exit_code" -eq 0 ] || gt_log error "${___gt_error_msg:-"Couldn't find any data"}"
-    return "$___gt_exit_code"
+    local ___gitlab_exit_code="$?"
+    [ "$___gitlab_exit_code" -eq 0 ] || gitlab_log error "${___gitlab_error_msg:-"Couldn't find any data"}"
+    return "$___gitlab_exit_code"
 }
