Squashed 'mod/gt/' changes from b26ae58f..80fd1447
80fd1447 ...
00ec648a update
f0672913 style: update code format style
30706850 style: add local prevent global variable
b7431e4b fix: fix for in return code
7ea5088c update local
d9fa04c1 org member
de18600f org main
0aeab4e6 enterprises member update
8bbbbcaa enterprise main
cf9c147c feat(pr,tag,release): import ui style to output

git-subtree-dir: mod/gt
git-subtree-split: 80fd144767fda4f37da2b1bd14d106b963fc5cfc

diff --git a/lib/enterprise/main b/lib/enterprise/main
--- a/lib/enterprise/main
+++ b/lib/enterprise/main
@@ -7,7 +7,7 @@ ___x_cmd_gt_enterprise(){
     param:scope     "gitee/$O"
     param:dsl       '
 subcmd:
-    info            "Show information"
+    ls            "Show information"
     repo            "List all repos"
     issue           "List all issues"
     member          "enterprise member management"
@@ -19,17 +19,10 @@ subcmd:
         return 1
     fi
 
-    # list issues of user
     # list projects of user
 
     "___x_cmd_gt_enterprise_${PARAM_SUBCMD}" "$@"
 }
-
-____x_cmd_gt_enterprise()(
-    ___x_cmd_gt_current_owner "${1:?enterprise name}" "enterprise"
-    shift 1
-    ___x_cmd_gt_enterprise ${1:+"$@"}
-)
 
 ___x_cmd_gt_enterprise_repo(){
     param:dsl       '
@@ -47,9 +40,8 @@ subcmd:
     "___x_cmd_gt_enterprise_repo_${PARAM_SUBCMD}" "$@"
 }
 
-# TODO: rename ls?
 # shellcheck disable=SC2154
-___x_cmd_gt_enterprise_info() {
+___x_cmd_gt_enterprise_ls() {
     param:scope     "gitee/$O"
     param:dsl       '
 
@@ -59,16 +51,20 @@ options:
     param:run
     if [ "$#" -eq 0 ]; then
         ___ui_table_json "$(printf "%s" "______x_cmd_gt_get_multi \"/v5/user/enterprises\" admin || return 1" )" \
-                Id=.id Name=.name Path=.path && return 0
-        [ $? -eq 1 ] && return 1
-    else
-        local data
-        data="$(______x_cmd_gt_get "/v5/repos/${owner_repo}/issues/${number}")"
-        ___x_cmd_gt_json_query_rename "$data" id=.id name=.name path=.path
-        [ -n "$id" ] && ___x_cmd_ui tf "true" "Success" "id: $id" "name: $name" "path: $path" && return 0
-                        gt_log "err" "Getting organization info failure by $1"                && return 1
+            Id=.id Name=.name Path=.path || return 1
+        return 0
     fi
-    return 0
+
+    local data
+    data="$(______x_cmd_gt_get "/v5/repos/${owner_repo}/issues/${number}")"
+
+    local id
+    local name
+    local path
+    ___x_cmd_gt_json_query_rename "$data" id=.id name=.name path=.path
+    [ -z "$id" ] && gt_log "err" "Getting organization info failure by $1" && return 1
+
+    ___x_cmd_ui tf "true" "Success" "id: $id" "name: $name" "path: $path"
 }
 
 # https://gitee.com/api/v5/swagger#/getV5EnterprisesEnterpriseRepos
@@ -78,14 +74,12 @@ ___x_cmd_gt_enterprise_repo_ls() {
 type:
     Genre = all public internal private
 options:
-    --repo_type     "type"          <>:Genre="all"
-    --direct        "direct"        <>:bool="false"
+    --repo_type     "type"                              <>:Genre="all"
+    --direct        "direct"                            <>:bool="false"
+    #1              "Please provide enterprise path"    <>
 '
     param:run
-    if [ -z "$1" ]; then
-        gt_log error "Please provide enterprise path"
-        return 1
-    fi
-    ___ui_table_json "$(printf "%s" "O=$O ______x_cmd_gt_get_multi \"/v5/enterprises/${1:?Provide enterprise path}/repos\" repo_type direct page per_page || return 1" )" \
-            Id=.id Name=.name public=.public OwnerName=.owner.name DefaultBranch=".default_branch" OpenIssuesCount=.open_issues_count license=.license Url=.html_url && return 0
+    ___ui_table_json "$(printf "%s" "O=$O ______x_cmd_gt_get_multi \"/v5/enterprises/$1/repos\" repo_type direct page per_page" )" \
+        Id=".id" Name=".name" public=".public" OwnerName=".owner.name" DefaultBranch=".default_branch" \
+        OpenIssuesCount=".open_issues_count" license=".license" Url=".html_url" && return 0
 }
diff --git a/lib/org/main b/lib/org/main
--- a/lib/org/main
+++ b/lib/org/main
@@ -8,7 +8,7 @@ ___x_cmd_gt_org(){
     param:scope     "gitee/$O"
     param:dsl       '
 subcmd:
-    info                    "Show information"
+    ls                      "Show org information or List all org"
     create                  "create org"
     repo                    "List all repos"
     quit                    "quit org"
@@ -25,34 +25,32 @@ subcmd:
     "___x_cmd_gt_org_${PARAM_SUBCMD}" "$@"
 }
 
-# TODO: rename "ls"?
 # shellcheck disable=SC2154
-___x_cmd_gt_org_info() {
+___x_cmd_gt_org_ls() {
     param:scope     "gitee/$O"
     param:dsl       '
-type:
 options:
-    --admin      "admin"       <>:bool=false
+    --admin      "admin"       <>:Bool=false
 '
     param:run
 
     if [ $# -eq 0 ]; then
         ___ui_table_json "$(printf "%s" "______x_cmd_gt_get_multi \"/v5/user/orgs\" admin page per_page || return 1" )" \
             Id=.id Name=.name FollowCount=.follow_count Url=.repos_url && return 0
-        [ $? -eq 1 ] && return 1
-    else
-        local data
-        data="$(______x_cmd_gt_get "/v5/orgs/${1:?Provide organization}")"
-        ___x_cmd_gt_json_query_rename "$data" id=.id name=.name public=.public follow_count=.follow_count owner=.owner.name
-        if [ -n "$id" ];then
-            ___x_cmd_ui tf "true" "Success" "id: $id" "name: $name" "public: $public" "follow_count: $follow_count" "owner: $owner"
-            return 0
-        else
-            gt_log "err" "Getting organization info failure by $1"
-            return 1
-        fi
+        return 1
     fi
-    return 0
+
+    local data
+    local id
+    local name
+    local public
+    local follow_count
+    local owner
+    data="$(______x_cmd_gt_get "/v5/orgs/${1:?Provide organization}")"
+    [ -z "$data" ] && gt_log "err" "Getting organization info failure by $1" && return 1
+
+    ___x_cmd_gt_json_query_rename "$data" id=.id name=.name public=.public follow_count=.follow_count owner=.owner.name
+    ___x_cmd_ui tf "true" "Success" "id: $id" "name: $name" "public: $public" "follow_count: $follow_count" "owner: $owner"
 }
 
 # It is very rare TODO: batch?
@@ -61,9 +59,9 @@ ___x_cmd_gt_org_create() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    #1              "organization name"     <>:name
     --org           "organization path"     <>=""
     --description   "description"           <>=""
+    #1              "organization name"     <>
 '
     param:run
     org=${org:-$1}
@@ -94,17 +92,15 @@ ___x_cmd_gt_org_repo_ls() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    --type     "type"     <>="all"    = all private public
+    --type      "type"                          <>="all"    = all private public
+    #1|--org    "Please provide organization"   <>:Address
 '
     param:run
-    if [ -z "$1" ]; then
-        gt_log error "Please provide organization"
-        return 1
-    fi
-     ___ui_table_json "$(printf "%s" "O=$O ______x_cmd_gt_get_multi \"/v5/orgs/${1:?Provide organization}/repos\" type || return 1" )" \
+     ___ui_table_json "$(printf "%s" "O=$O ______x_cmd_gt_get_multi \"/v5/orgs/$1/repos\" type || return 1" )" \
             Id=.id Name=.name public=.public OwnerName=.owner.name DefaultBranch=".default_branch" OpenIssuesCount=.open_issues_count license=.license Url=.html_url && return 0
 }
 
+# shellcheck disable=SC2181
 ___x_cmd_gt_org_quit() {
     param:scope     "gitee/$O"
     param:dsl       '
@@ -112,17 +108,15 @@ options:
     #n      "orgs"
 '
     param:run
-    if [ -z "$1" ];then
-        gt_log error "At least one org spatial address is needed."
-        return 1
-    fi
+
+    [ $# -eq 0 ] && gt_log error "At least one org spatial address is needed." && return 1
 
     for org in "$@"; do
     {
         ______x_cmd_gt_delete "/v5/user/memberships/orgs/${org##*/}"
 
         [ $? -ne 0 ] && gt_log error "Quit $org organization failure"     &&   return 1
-                        gt_log info  "Quit $org organization successfully.";   return 0
+                        gt_log info  "Quit $org organization successfully."
     }
     done
 }
diff --git a/lib/repo/main b/lib/repo/main
--- a/lib/repo/main
+++ b/lib/repo/main
@@ -76,23 +76,22 @@ option:
     [ -n "$no_wiki" ] && has_wiki=false
     [ -n "$no_comment" ] && can_comment=false
     [ -n "$no_auto_init" ] && auto_init=false
-    # TODO: ___x_cmd_gt_printf_command_log
 
-    [ $# -eq 0 ] && gt_log info "repo create name is null" && return
+    [ $# -eq 0 ] && gt_log info "repo create name is null" && return 1
     local name
+    local data
+    local repo_id
+    local url
+    local repo_owner
     for name in "$@"; do
         {
-            local data
+
             data=$(______x_cmd_gt_post_json "/v5/user/repos" name="${name##*/}" description homepage has_issues has_wiki can_comment \
-            auto_init gitignore_template license_template path="$paths" private 2>/dev/null)
+                auto_init gitignore_template license_template path="$paths" private 2>/dev/null)
+            [ -z "$data" ] && gt_log error "Creating repo failure: $name." && return 1
+
             ___x_cmd_gt_json_query_rename "$data" repo_id=.id url=.html_url repo_owner=.owner.login
-            if [ -n "$repo_id" ];then
-                ___x_cmd_ui tf "true" "Creating repo $name success" "repo_id: $repo_id" "repo_owner: $repo_owner" "url: $url"
-                return 0
-            else
-                gt_log error "Creating repo failure: $name. Code is $code. "
-                return 1
-            fi
+            ___x_cmd_ui tf "true" "Creating repo $name success" "repo_id: $repo_id" "repo_owner: $repo_owner" "url: $url"
         }
     done
 }
@@ -119,7 +118,7 @@ option:
     --no_auto_init          "auto init README"
     --gitignore_template    "Git Ignore"                    <>:Ignore=""
     --license_template      "license"                       <>:license=""
-    --paths                  "repo path"                    <>:url_type=""
+    --paths                 "repo path"                     <>:url_type=""
     #n                      "repo names"
 '
     param:run
@@ -145,15 +144,16 @@ option:
     for name in "$@"; do
         local resp
         {
-            ______x_cmd_gt_post_json "/v5/orgs/$org/repos" name description homepage has_issues has_wiki can_comment auto_init \
-             gitignore_template license_template path="$paths" public 1>/dev/null
+            ______x_cmd_gt_post_json "/v5/orgs/$org/repos" name description homepage \
+                has_issues has_wiki can_comment auto_init \
+                gitignore_template license_template \
+                path="$paths" public 1>/dev/null
             code=$?
             if [ $code -ne 0 ]; then
                 gt_log error "Creating repo failure: $name. Code is $code. "
                 return $code
             else
                 gt_log info "Creating $name repo successfully."
-                return 0
             fi
         }
     done
@@ -247,19 +247,24 @@ ___x_cmd_gt_repo_info() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    #1|--repo          "Repo or Path(owner/repo)"         <>:repo
+    #1|--repo          "Repo or Path(owner/repo)"         <>:RepoName
 '
     param:run
 
     # get owner_repo by repo
     ___x_cmd_gt_param_init_owner_repo
-    ___x_cmd_gt_printf_command_log "gt repo info -r $repo"
 
     local data
+    local id
+    local name
+    local html_url
     data=$(______x_cmd_gt_get "/v5/repos/${owner_repo}" || return 1)
-        ___x_cmd_gt_json_query_rename "$data" id=.id name=.name html_url=.html_url
+    ___x_cmd_gt_json_query_rename "$data" id=.id name=.name html_url=.html_url
+
     [ -n "$name" ] && ___x_cmd_ui tf "true" "Success" "id: $id" "name: $name" "url: $html_url" && return 0
-                      gt_log         "error" "Fail. Couldn't find any repo: $repo"             && return 1
+
+    gt_log  "error" "Fail. Couldn't find any repo: $owner_repo"
+    return 1
 }
 
 # https://gitee.com/api/v5/swagger#/deleteV5ReposOwnerRepo
@@ -272,8 +277,6 @@ options:
     #n      "Provide repo list"    <>
 '
     param:run
-    xrc ui/lib/form
-    ___x_cmd_gt_printf_command_log "gt repo del " "$@"
 
     local ___X_CMD_UI_FORM_EXIT_STRATEGY="execute|exit"
     ___x_cmd_ui_form "Are you sure you want to $(___x_cmd_ui bold red delete "repo:") $(___x_cmd_ui bold "$*")" tf 1 = "yes" "no"
@@ -282,8 +285,9 @@ options:
     for i in "$@"; do
         ______x_cmd_gt_param_normalize_repo "$i"
         ______x_cmd_gt_delete "/v5/repos/$owner_repo" 1>/dev/null 2>&1
-        [ $? -eq 0 ] && ui tf "true" "Deleted repo $i successfully"                                  && return 0
-                        gt_log error "Deleting repo failure: $i. Probably because it desn't exists." && return 1
+        [  $? -ne 0 ] && gt_log error "Deleting repo failure: $i. Probably because it desn't exists." && return 1
+
+        ui tf "true" "Deleted repo $i successfully"
     done
 }
 
@@ -292,12 +296,11 @@ ___x_cmd_gt_repo_clear() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    #1|--repo          "Repo name"             <>:repo
+    #1|--repo          "Repo name"             <>:RepoName
 '
     param:run
 
     ___x_cmd_gt_param_init_owner_repo
-    ___x_cmd_gt_printf_command_log "gt repo clear -r " "$@"
 
     local ___X_CMD_UI_FORM_EXIT_STRATEGY="execute|exit"
     ___x_cmd_ui_form "Are you sure you want to $(ui bold red clear repo) $(ui bold "${owner_repo}")" tf 1 = "yes" "no"
@@ -305,7 +308,9 @@ options:
 
     ______x_cmd_gt_put_json "/v5/repos/${owner_repo}/clear" 1>/dev/null 2>&1
     [ $? -eq 0 ] && ___x_cmd_ui tf "true" "Successfully clear ${owner_repo}" && return 0
-                    gt_log error "Clearing repo failure: $owner_repo"        && return 1
+
+    gt_log error "Clearing repo failure: $owner_repo"
+    return 1
 }
 
 # shellcheck disable=SC2154,SC2181
@@ -313,7 +318,7 @@ ___x_cmd_gt_repo_review(){
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    #1|--repo             "Repo name"                   <>:repo
+    #1|--repo             "Repo name"                   <>:RepoName
     --assignees           "assignees username"          <>:assignees
     --testers             "testers usrename"            <>:testers
     --assignees_number    "number of reviewers"         <>:assignees_number="1"
@@ -321,10 +326,10 @@ options:
 '
     param:run
     ___x_cmd_gt_param_init_owner_repo
-    ___x_cmd_gt_printf_command_log "gt repo review " \
-    "--repo $repo --assignees $assignees --testers $testers --assignees_number $assignees_number --testers_number $testers_number"
 
     ______x_cmd_gt_put_json "/v5/repos/${owner_repo}/reviewer" assignees testers assignees_number testers_number 1>/dev/null 2>&1
     [ $? -eq 0 ] && ___x_cmd_ui tf "true" "Successfully setup ${owner_repo} review configure" && return 0
-                    gt_log error "Setup repo review configure failure: $owner_repo"           && return 1
+
+    gt_log error "Setup repo review configure failure: $owner_repo"
+    return 1
 }
diff --git a/lib/repo/pr/main b/lib/repo/pr/main
--- a/lib/repo/pr/main
+++ b/lib/repo/pr/main
@@ -51,8 +51,9 @@ options:
     param:run
 
     ___x_cmd_gt_param_init_owner_repo
-    ______x_cmd_gt_get "/v5/repos/$owner_repo/pulls" state head base sort since \
-        direction milestone_number labels page per_page
+    ___ui_table_json "$(printf "%s" "______x_cmd_gt_get \"/v5/repos/$owner_repo/pulls\" state head base sort since direction milestone_number labels page per_page  || return 1" )" \
+        Id=.id Title=.title Body=.body User=.user.login TargetBranch=.base.ref SourceBranch=.head.ref \
+        CreateTime=.created_at UpdateTime=.updated_at Url=.html_url
 }
 
 # Assume pr and owner_repo are environments
@@ -127,6 +128,7 @@ options:
 
 # Section: create update merge
 
+# shellcheck disable=SC2154,SC2181
 ___x_cmd_gt_repo_pr_create() {
     local O="${O:-GITEE_DEFAULT}"
     param:scope     "gitee/$O"
@@ -134,7 +136,7 @@ ___x_cmd_gt_repo_pr_create() {
 type:
     Bool = true false
 options:
-    --repo                  "Repo name"                                                     <>:repo
+    --repo                  "Repo name"                                                     <>:RepoName
     --title                 "pr title"                                                      <>
     --head                  "source branch. Format: [username:]<branch>"                    <>:name
     --base                  "target branch. Format: [username:]<branch>"                    <>:name
@@ -151,9 +153,21 @@ options:
     param:run
 
     ___x_cmd_gt_param_init_owner_repo
-
-    ______x_cmd_gt_post_json "/v5/repos/$owner_repo/pulls" title head base body milestone_number\
-        labels issue assignees testers assignees_number testers_number prune_source_branch
+    local data
+    local title
+    local state
+    local html_url
+    data="$(______x_cmd_gt_post_json "/v5/repos/$owner_repo/pulls" title head base body milestone_number \
+        labels issue assignees testers assignees_number testers_number prune_source_branch)"
+    ___x_cmd_gt_json_query_rename "$data" title=.title state=.state html_url=.html_url
+    if [ -n "$title" ];then
+        ___x_cmd_ui tf "true" "Success" "title: $title" "owner_repo: $owner_repo" "state: $state" \
+         "base: $base" "source branch: $head" "target branch: $base" "url: $html_url"
+        return 0
+    else
+        gt_log error "Create pull request failure: $title by $owner_repo $base"
+        return 1
+    fi
 }
 
 ___x_cmd_gt_repo_pr_update() {
diff --git a/lib/repo/release/main b/lib/repo/release/main
--- a/lib/repo/release/main
+++ b/lib/repo/release/main
@@ -7,10 +7,10 @@ subcmd:
     ls              "list repo's release"
     create          "create repo release"
     update          "update release information"
-    delete          "Remove repo release"
+    delete          "remove repo release"
     latest          "get latest release"
-    info            "Show detailed information of repo"
-    attachment      "Attachment management"
+    info            "show detailed information of repo"
+    attachment      "attachment management"
 A
     param:run
     if [ -z "$PARAM_SUBCMD" ]; then
@@ -22,29 +22,30 @@ A
     "___x_cmd_gt_repo_release_${PARAM_SUBCMD}" "$@"
 }
 
-# Section 10: Release
-# https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoReleases
+# shellcheck disable=SC2086,SC2154
 ___x_cmd_gt_repo_release_ls() {
     param:scope     "gitee/$O"
     param:dsl    '
 type:
     Direction = asc  desc
 options:
-    --repo          "Repo name"             <>:repo
+    --repo          "Repo name"             <>:RepoName
     --direction     "direction(asc,desc)"   <>:Direction="asc"
 '
     param:run
 
     ___x_cmd_gt_param_init_owner_repo
-
-    ______x_cmd_gt_get "/v5/repos/${owner_repo}/releases" page per_page direction
+    ___ui_table_json "$(printf "%s" "______x_cmd_gt_get \"/v5/repos/${owner_repo}/releases\" page per_page direction  || return 1" )" \
+        Id=.id ReleaseName=.name TagName=.tag_name Message=.body IsPreRelease=.prerelease User=.author.login Time=.created_at && return 0
 }
 
+# shellcheck disable=SC2086,SC2154
+# TODO:https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoReleasesTagsTag
 ___x_cmd_gt_repo_get_release_by_tag() {
     param:scope     "gitee/$O"
     param:dsl    '
 options:
-    #1|--repo          "Repo name"             <>:repo
+    #1|--repo          "Repo name"             <>:RepoName
     #2|--tag           "tag name"              <>
 '
     param:run
@@ -53,18 +54,18 @@ options:
     ______x_cmd_gt_get "/v5/repos/${owner_repo}/releases/tags/${tag}"
 }
 
-# https://gitee.com/api/v5/swagger#/postV5ReposOwnerRepoReleases
+# shellcheck disable=SC2154,SC2181
 ___x_cmd_gt_repo_release_create() {
     local O="${O:-GITEE_DEFAULT}"
 
     param:scope  "gitee/$O"
     param:dsl    '
 options:
-    #1|--repo           "Repo name"                 <>:repo
+    #1|--repo           "Repo name"                 <>:RepoName
     --tag               "Please provide tag name"   <>
     --name              "Release name"              <>
     --body              "Release Description"       <>
-    --prerelease        "Is release version"        <>:bool="false"
+    --prerelease        "Is pre-release version"    <>:bool="false"
     --target_commitish  "Default is master"         <>:name="master"
 '
     param:run
@@ -72,7 +73,9 @@ options:
     ___x_cmd_gt_param_init_owner_repo
 
     ______x_cmd_gt_post_json "/v5/repos/${owner_repo}/releases" \
-        tag_name="$tag" name body prerelease target_commitish
+        tag_name="$tag" name body prerelease target_commitish 1>/dev/null 2>&1
+    [ $? -ne 0 ] && gt_log error "Create release failure: $name by $owner_repo $tag" && return 1
+    ___x_cmd_ui tf "true" "Success release" "name: $name" "owner_repo: $owner_repo" "tag: $tag"  && return 0
 }
 
 
@@ -91,7 +94,8 @@ alias ______x_cmd_gt_repo_release_init_owner_repo_and_release="
 "
 
 
-# https://gitee.com/api/v5/swagger#/patchV5ReposOwnerRepoReleasesId
+# shellcheck disable=SC2154,SC2181
+# TODO:https://gitee.com/api/v5/swagger#/patchV5ReposOwnerRepoReleasesId
 ___x_cmd_gt_repo_release_update() {
     local O="${O:-GITEE_DEFAULT}"
     param:scope  "gitee/$O"
@@ -104,12 +108,14 @@ options:
     --prerelease        "Is release version"        <>:bool="false"
 '
     param:run
-
     ______x_cmd_gt_repo_release_init_owner_repo_and_release
     ______x_cmd_gt_patch_json "/v5/repos/${owner_repo}/releases/${release}" \
-        tag_name="$tag" name body prerelease
+        tag_name="$tag" name body prerelease 1>/dev/null 2>&1
+    [ $? -ne 0 ] && gt_log error "Update release failure: $name by $owner_repo $release" && return 1
+    ___x_cmd_ui tf "true" "Success release" "name: $name" "body: $body" "prerelease: $prerelease"  && return 0
 }
 
+# TODO:https://gitee.com/api/v5/swagger#/deleteV5ReposOwnerRepoReleasesId
 ___x_cmd_gt_repo_release_delete() {
     local O="${O:-GITEE_DEFAULT}"
     param:scope  "gitee/$O"
@@ -123,12 +129,13 @@ options:
     ______x_cmd_gt_delete "/v5/repos/${owner_repo}/releases/$release"
 }
 
+# TODO:https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoReleasesLatest
 ___x_cmd_gt_repo_release_latest() {
     local O="${O:-GITEE_DEFAULT}"
     param:scope     "gitee/$O"
     param:dsl    '
 options:
-    #1|--repo              "Repo name"               <>:repo
+    #1|--repo              "Repo name"               <>:RepoName
 '
     param:run
 
@@ -136,6 +143,7 @@ options:
     ______x_cmd_gt_get "/v5/repos/${owner_repo}/releases/latest"
 }
 
+# TODO:https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoReleasesId
 ___x_cmd_gt_repo_release_info() {
     local O="${O:-GITEE_DEFAULT}"
     param:scope     "gitee/$O"
@@ -148,5 +156,3 @@ options:
     ______x_cmd_gt_repo_release_init_owner_repo_and_release
     ______x_cmd_gt_get "/v5/repos/${owner_repo}/releases/${release}"
 }
-
-# EndSection
