Squashed 'mod/gitee/' changes from bfb9b272..d785a1f1
d785a1f1 feat(org): done org import ui show
29fa7e80 fix(repo): update ui select
c4c4a841 feat(user): done user modules
1fc01e6d feat(repo-member): done repo member list add del
3ca356b9 feat(repo): done repo info fetch
bdf623e0 feat(repo): done gitee repo ls
48cb7c64 feat(repo): repo list use ui table
d052f133 feat(gt): use lazyloader to load source

git-subtree-dir: mod/gitee
git-subtree-split: d785a1f1129020cfb551cfc15f87a4af33f09d93

diff --git a/lib/org/main b/lib/org/main
--- a/lib/org/main
+++ b/lib/org/main
@@ -1,6 +1,9 @@
 # shellcheck shell=sh
 # shellcheck disable=SC2039,3043
 
+# define lazy loader
+___x_cmd_definelazyloader   ___x_cmd_gt_org_member           gt/lib/org/member
+
 ___x_cmd_gt_org(){
     param:scope     "gitee/$O"
     param:dsl       '
@@ -33,16 +36,33 @@ options:
     param:run
 
     if [ $# -eq 0 ]; then
-        ______x_cmd_gt_get_multi "/v5/user/orgs" admin page per_page
+        ___ui_table_json "$(printf "%s" "______x_cmd_gt_get_multi \"/v5/user/orgs\" admin page per_page || return 1" )" \
+            Id=.id Name=.name FollowCount=.follow_count Url=.repos_url && return 0
         [ $? -eq 1 ] && return 1
     else
-        ______x_cmd_gt_get "/v5/orgs/${1:?Provide organization}"
-        [ $? -eq 1 ] && return 1
+        local data
+        data="$(______x_cmd_gt_get "/v5/orgs/${1:?Provide organization}")"
+        local id
+        local name
+        local follow_count
+        local public
+        local owner
+        id="$(___x_cmd_gt_json_query "$data" .id)"
+        name="$(___x_cmd_gt_json_query "$data" .name)"
+        public="$(___x_cmd_gt_json_query "$data" .public)"
+        follow_count="$(___x_cmd_gt_json_query "$data" .follow_count)"
+        owner="$(___x_cmd_gt_json_query "$data" .owner.name)"
+        if [ -n "$id" ];then
+            ui tf "true" "Success" "id: $id" "name: $name" "public: $public" "follow_count: $follow_count" "owner: $owner" && return 0
+        else
+            gt_log "err" "Getting organization info failure by $1"   && return 1
+        fi
     fi
     return 0
 }
 
 # It is very rare TODO: batch?
+# shellcheck disable=SC2181
 ___x_cmd_gt_org_create() {
     param:scope     "gitee/$O"
     param:dsl       '
@@ -53,13 +73,9 @@ options:
 '
     param:run
     org=${org:-$1}
-    ______x_cmd_gt_post_json "/v5/users/organization" name="$1" org description
-    local code=$?
-    if [ $code -ne 0 ]; then
-        # TODO: printf http error msg
-        gt_log error "Creating organization failure: $1. Code is $code. "
-        return $code
-    fi
+    ______x_cmd_gt_post_json "/v5/users/organization" name="$1" org description  1>/dev/null
+    [ $? -ne 0 ] && gt_log error "Creating organization failure: $1." && return 1
+                    gt_log info  "Creating organization Successfully" && return 0
 }
 
 ___x_cmd_gt_org_repo(){
@@ -91,9 +107,8 @@ options:
         gt_log error "Please provide organization"
         return 1
     fi
-    O=$O ______x_cmd_gt_get_multi "/v5/orgs/${1:?Provide organization}/repos"
-    # ui table func ______x_cmd_gt_table "\"\$(O=$O ______x_cmd_gt_get_multi \"/v5/orgs/${1:?Provide organization}/repos\" type)\"" \
-        # . id full_name ownerName=owner.name updatedTime="updated_at"
+     ___ui_table_json "$(printf "%s" "O=$O ______x_cmd_gt_get_multi \"/v5/orgs/${1:?Provide organization}/repos\" type || return 1" )" \
+            Id=.id Name=.name public=.public OwnerName=.owner.name DefaultBranch=".default_branch" OpenIssuesCount=.open_issues_count license=.license Url=.html_url && return 0
 }
 
 ___x_cmd_gt_org_quit() {
@@ -117,4 +132,3 @@ options:
     }
     done
 }
-
diff --git a/lib/org/member b/lib/org/member
--- a/lib/org/member
+++ b/lib/org/member
@@ -27,15 +27,21 @@ subcmd:
     "___x_cmd_gt_org_member_$PARAM_SUBCMD" "$@"
 }
 
+# shellcheck disable=SC2154
 ___x_cmd_gt_org_member_ls() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
     #1|--org        "org space address"    <>:address
-    --role          "Repo name"            <>="all"         = admin member all
+    --role          "role"                 <>="all"         = admin member all
 '
     param:run
-    ______x_cmd_gt_get_multi "/v5/orgs/${org##*/}/members" role page per_page
+    # param form bug
+    [ -z "$org" ] && gt_log error "org space address is empty" && return 1
+
+    ___ui_table_json "$(printf "%s" "______x_cmd_gt_get_multi \"/v5/orgs/${org##*/}/members\" role page per_page || return 1" )" \
+            NameSpace=.login Name=.name Role=.member_role Url=.html_url && return 0
+        [ $? -eq 1 ] && return 1
 }
 
 ___x_cmd_gt_org_member_user() {
@@ -46,10 +52,28 @@ options:
     --username          "username: user space address"   <>:name
 '
     param:run
+    [ -z "$org" ] && [ -z "$username" ] && gt_log error "Get member user have empty options" && return 1
 
-    ______x_cmd_gt_get "/v5/orgs/${org##*/}/memberships/${username##*/}"
+    local data
+    data=$(______x_cmd_gt_get "/v5/orgs/${org##*/}/memberships/${username##*/}")
+    # TODO: wait json_awk
+    local organization
+    local name
+    local name_space
+    local role
+    local html_url
+    organization="$(___x_cmd_gt_json_query "$data" .organization.name)"
+    name="$(___x_cmd_gt_json_query "$data" .user.name)"
+    name_space="$(___x_cmd_gt_json_query "$data" .user.login)"
+    role="$(___x_cmd_gt_json_query "$data" .role)"
+    html_url="$(___x_cmd_gt_json_query "$data" .user.html_url)"
+    [ -n "$organization" ] && \
+        ui tf  "true" "Success" "Organization: $organization" "Name: $name" "NameSpace: $name_space" "Role: $role" "UserUrl: $html_url" && \
+        return 0
+    gt_log "error" "Getting organization info failure by $org $username" && return 1
 }
 
+# shellcheck disable=SC2181
 ___x_cmd_gt_org_member_add() {
     param:scope     "gitee/$O"
     param:dsl       '
@@ -66,17 +90,20 @@ options:
         gt_log error "At least one user’s spatial address is needed"
         return 1
     fi
+    # param form bug
+    [ -z "$org" ] && gt_log error "org space address is empty" && return 1
 
         for username in "$@"; do
         {
-            ______x_cmd_gt_put_json "/v5/orgs/${org##*/}/memberships/${username##*/}" role
+            ______x_cmd_gt_put_json "/v5/orgs/${org##*/}/memberships/${username##*/}" role 1>/dev/null
 
-            [ $? -ne 0 ] && gt_log error "Add $username failure"     &&  return 1
-                            gt_log info  "Add $username successfully";   return 0
+            [ $? -ne 0 ] && gt_log error "Add $username failure"      &&   return 1
+                            gt_log info  "Add $username successfully" &&   return 0
         }
     done
 }
 
+# shellcheck disable=SC2181
 ___x_cmd_gt_org_member_del() {
     param:scope     "gitee/$O"
     param:dsl       '
@@ -90,11 +117,13 @@ options:
         gt_log error "At least one user’s spatial address is needed"
         return 1
     fi
+    # param form bug
+    [ -z "$org" ] && gt_log error "org space address is empty" && return 1
 
     local username
     for username in "$@"; do
         {
-            ______x_cmd_gt_delete "/v5/orgs/${org##*/}/memberships/${username##*/}"
+            ______x_cmd_gt_delete "/v5/orgs/${org##*/}/memberships/${username##*/}" role 1>/dev/null
             [ $? -ne 0 ] && gt_log error "Remove $username failure"     &&  return 1
                             gt_log info  "Remove $username successfully.";  return 0
         }
diff --git a/lib/repo/main b/lib/repo/main
--- a/lib/repo/main
+++ b/lib/repo/main
@@ -19,8 +19,8 @@ subcmd:
         ___x_cmd_gt_repo _param_help_doc
         return 1
     fi
-    
-    "___x_cmd_gt_repo_${PARAM_SUBCMD}" "$@" 
+
+    "___x_cmd_gt_repo_${PARAM_SUBCMD}" "$@"
 }
 
 ____x_cmd_gt_repo()(
@@ -52,7 +52,7 @@ option:
     --no_issues             "Provide issue"
     --no_wiki               "Provide wiki"
     --no_comment            "Provide can_comment"
-    --no_auto_init          "auto init README"
+    --no_auto_init          "Not auto init README"
     --gitignore_template    "Git Ignore"                    <>:Ignore=" "
     --license_template      "license"                       <>:license=" "
     --paths                 "repo path"                     <>:url_type=""
@@ -91,9 +91,9 @@ option:
             url="$(___x_cmd_gt_json_query "$data" .html_url)"
             repo_owner="$(___x_cmd_gt_json_query "$data" .owner.login)"
             if [ -n "$repo_id" ];then
-                ui tf "true" "Creating repo $name success" "repo_id:$repo_id" "url:$url" "repo_owner:$repo_owner" 
+                ui tf "true" "Creating repo $name success" "repo_id: $repo_id" "repo_owner: $repo_owner" "url: $url"
             else
-                gt_log error "Creating repo failure: $name. Code is $code. " 
+                gt_log error "Creating repo failure: $name. Code is $code. "
             fi
         }
     done
@@ -148,17 +148,16 @@ option:
         local resp
         {
             ______x_cmd_gt_post_json "/v5/orgs/$org/repos" name description homepage has_issues has_wiki can_comment auto_init \
-             gitignore_template license_template path="$paths" public
+             gitignore_template license_template path="$paths" public 1>/dev/null
             code=$?
             if [ $code -ne 0 ]; then
                 gt_log error "Creating repo failure: $name. Code is $code. "
-                # ______x_cmd_gt_resp_header "" >&2
                 return $code
             else
                 gt_log info "Creating $name repo successfully."
                 return 0
             fi
-        } 
+        }
     done
 }
 
@@ -221,38 +220,31 @@ option:
     return 0
 }
 
-
 ############################
-# Section 5: List Repos TODO:
+# Section 5: List Repos
 ############################
-
-# gt repo list --access inner-source <owner>
-# gt enterprise repo list
+# shellcheck disable=SC2154,SC2145
 ___x_cmd_gt_repo_ls() {
     param:void
-    local owner
-    owner="$1"
-
-    if [ -z "$owner" ]; then
-        ___x_cmd_gt_user_repo "$@"
-        return
-    fi
-
     local owner_type
-    owner_type="$(______x_cmd_gt_owner_type_query "$owner")"
-    if [ -n "$owner_type" ] && [ -n "$owner" ]; then
-        "___x_cmd_gt_${owner_type}_repo" ls "$@"
-        return
+    if [ $# -eq 0 ];then
+        owner_type=user
+    else
+        local owner="$1"
+        owner_type="$(______x_cmd_gt_owner_type_query "$owner")"
     fi
+
+    ___ui_table_json "$(printf "%s" "___x_cmd_gt_${owner_type}_repo ls $@ || return 1" )" \
+        Id=.id Name=.name Owner=.owner.login Url=.html_url && return 0
 
     gt_log error "Please provide owner and owner_type"
     return 1
-    # param_help.show
 }
 
 ############################
 # Section 7: Repo - Deletion & Info & Creation
 ############################
+# shellcheck disable=SC2154
 ___x_cmd_gt_repo_info() {
     param:scope     "gitee/$O"
     param:dsl       '
@@ -261,31 +253,45 @@ options:
 '
     param:run
 
+    # TODO: FIX form not data. wait param debug
+    # get owner_repo by repo
     ___x_cmd_gt_param_init_owner_repo
-    ______x_cmd_gt_get "/v5/repos/${owner_repo}"
-    # ______x_cmd_gt_get "/v5/repos/${owner}/${repo}"
+    local data
+    data=$(______x_cmd_gt_get "/v5/repos/${owner_repo}" || return 1)
+    local id
+    local name
+    local html_url
+    id="$(___x_cmd_gt_json_query "$data" .id)"
+    name="$(___x_cmd_gt_json_query "$data" .name)"
+    html_url="$(___x_cmd_gt_json_query "$data" .html_url)"
+#     ___json_awk_get name=.login html_url=.html_url types=.type <<A
+#     $data
+# A
+    [ -n "$name" ] && ui tf "true" "Success" "id: $id" "name: $name" "url: $html_url" && return 0
+                      gt_log "error" "Fail. Couldn't find any repo: $repo"            && return 1
 }
 
 # https://gitee.com/api/v5/swagger#/deleteV5ReposOwnerRepo
+# shellcheck disable=SC2181
 ___x_cmd_gt_repo_del() {
+    # TODO: -y force del
     param:scope     "gitee/$O"
     param:dsl       '
 options:
     #n      "Provide repo list"    <>
 '
     param:run
-    local confirm
     # TODO: wait fix | input all name then can do it
-    # confirm=$(ui select "text" "Are you sure you want to delete repo $*" "yes" "no")
-    # [ "$confirm" != "yes" ] && return
+    ___x_cmd_ui_select nohelp "Are you sure you want to $(ui bold red delete repo) $(ui bold "$*")" "yes" "no" "---" "---"
+    [ "$___X_CMD_UI_SELECT_CURRENT_ITEM" != "yes" ] && gt_log info "Delete repo has been canceled" &&  return 0
     local i
     for i in "$@"; do
         ______x_cmd_gt_param_normalize_repo "$i"
-        ______x_cmd_gt_delete "/v5/repos/$owner_repo" >/dev/null 
+        ______x_cmd_gt_delete "/v5/repos/$owner_repo" >/dev/null
         if [ $? -eq 0 ]; then
-            ui tf "true" "deleted repo $i"
+            ui tf "true" "Deleted repo $i successfully"
         else
-            gt_log error "Code is $?. Deleting repo failure: $i. Probably because it desn't exists."
+            gt_log error "Deleting repo failure: $i. Probably because it desn't exists."
         fi
     done
 }
@@ -300,11 +306,10 @@ options:
 
     ___x_cmd_gt_param_init_owner_repo
     # TODO: wait fix | input all name then can do it
-    # local confirm
-    # confirm=$(ui select "text" "Are you sure you want to clear repo ${owner_repo}" "yes" "no")
-    # [ "$confirm" != "yes" ] && return
-    ______x_cmd_gt_put_json "/v5/repos/${owner_repo}/clear" && ui tf "true" "Successfully clear ${owner_repo}" && return
-    gt_log error "clear repo failure: $owner_repo"
+    ___x_cmd_ui_select nohelp "Are you sure you want to $(ui bold red clear repo) $(ui bold "${owner_repo}")" "yes" "no" "---" "---"
+    [ "$___X_CMD_UI_SELECT_CURRENT_ITEM" != "yes" ] && gt_log info "Clear repo has been canceled" &&  return 0
+    ______x_cmd_gt_put_json "/v5/repos/${owner_repo}/clear" && ui tf "true" "Successfully clear ${owner_repo}" && return 0
+                                                             gt_log error "Clearing repo failure: $owner_repo" && return 1
 }
 
 ___x_cmd_gt_repo_review(){
diff --git a/lib/repo/member b/lib/repo/member
--- a/lib/repo/member
+++ b/lib/repo/member
@@ -16,11 +16,11 @@ subcmd:
 '
     param:run
     if [ -z "$PARAM_SUBCMD" ]; then
-        gt_log warn "Subcmd Not Found."  
+        gt_log warn "Subcmd Not Found."
         ___x_cmd_gt_repo_member _param_help_doc
         return 1
     fi
-    
+
     "___x_cmd_gt_repo_member_$PARAM_SUBCMD" "$@"
 }
 
@@ -32,21 +32,22 @@ options:
 '
     param:run
     ___x_cmd_gt_param_init_owner_repo
-    ______x_cmd_gt_get_multi "/v5/repos/${owner_repo}/collaborators" page per_page
-    # ui table func ______x_cmd_gt_table "\"\$(O=$O ______x_cmd_gt_get_multi \"/v5/repos/${owner_repo}/collaborators\" page per_page)\"" \
-    #     . id login name push=permissions.push admin=permissions.admin
+    ___ui_table_json "$(printf "%s" "______x_cmd_gt_get_multi "/v5/repos/${owner_repo}/collaborators" page per_page || return 1" )" \
+        NameSpace=.login Name=.name Admin=.permissions.admin PushPermissions=.permissions.push && return 0
 }
 
+# shellcheck disable=SC2181
 ___x_cmd_gt_repo_member_add() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    --repo|-r           "Repo name"             <>:repo
-    --permission|-p     "permission"            <>:permission
-    #n                  "Username list"         <>
+    --repo|-r           "Repo name"                              <>:repo
+    --permission|-p     "permission"                             <>:permission="push"
+    #n                  "Username list"                          <>
 '
     param:run
 
+    # param Design permission:key
     ___x_cmd_gt_param_init_owner_repo
     if [ -z "$1" ];then
         gt_log error "At least one user’s spatial address is needed"
@@ -56,21 +57,15 @@ options:
     for username in "$@"; do
         {
             ______x_cmd_gt_put_json "/v5/repos/$owner_repo/collaborators/${username##*/}" permission 1>/dev/null
-            
-            [ $? -ne 0 ] && gt_log error "add user failure: $username" && return 1
-            
-            ui tf "true" "add $username to $owner_repo successfully"
 
-        # if [ $? -ne 0 ];then
-        #     gt_log error "add user failure: $username"
-        # else
-        #     ui tf "true" "add $username to $owner_repo successfully"
-        # fi
-        }  
+            [ $? -ne 0 ] && gt_log error "add user failure: $username"               && return 1
+                            gt_log info  "add $username to $owner_repo successfully" && return 0
+        }
     done
 }
 
 # https://gitee.com/api/v5/swagger#/deleteV5ReposOwnerRepoCollaboratorsUsername
+# shellcheck disable=SC2181
 ___x_cmd_gt_repo_member_del() {
     param:scope     "gitee/$O"
     param:dsl       '
@@ -85,9 +80,8 @@ options:
     local username
     for username in "$@"; do
         ______x_cmd_gt_delete "/v5/repos/$owner_repo/collaborators/${username##*/}"
-        
-        [ $? -ne 0 ] && gt_log error "delete user failure: $username." && return 1
-            
-        ui tf "true" "successfully deleted $username in $owner_repo"
+
+        [ $? -ne 0 ] && gt_log error "delete user failure: $username"               && return 1
+                        gt_log info  "delete $username to $owner_repo successfully" && return 0
     done
 }
diff --git a/lib/user b/lib/user
--- a/lib/user
+++ b/lib/user
@@ -1,6 +1,8 @@
 # shellcheck shell=sh
 # shellcheck disable=SC2039,3043
 
+# define lazy loader
+___x_cmd_definelazyloader   ___x_cmd_gt_repo_ls             gt/lib/repo/main
 
 ___x_cmd_gt_user(){
     param:scope     "gitee/$O"
@@ -20,33 +22,25 @@ subcmd:
     fi
 
     # list issues of user
-    # list projects of user
-
-    "___x_cmd_gt_user_${PARAM_SUBCMD}" "$@"
+    # list repo of user
+   case "${PARAM_SUBCMD}" in
+       repo)  "___x_cmd_gt_repo_ls"              "$@"    ;;
+       *)     "___x_cmd_gt_user_${PARAM_SUBCMD}" "$@"
+   esac
 }
 
 # Section: info repo email issue
-
-# ___x_cmd_gt_users() {
-#     local O="${O:-GITEE_DEFAULT}"
-#     param <<A
-# scope:  gitee/$O
-# options: 
-#     #1          "Provide owner"
-# A
-#     ______x_cmd_gt_get "/v5/users/$name" | json_extract "html_url"
-# }
 
 ___x_cmd_gt_user_info() {
     param:scope     "gitee/$O"
     param:dsl       '
 options:
-    #1              "Username, if not set, show the user information of current owner, or owner of this token" 
+    #1              "Username, if not set, show the user information of current owner, or owner of this token"
 '
     param:run
-    
+
     local owner="$1"
-    local data name html_url types
+    local data
     if [ -z "$owner" ]; then
         data=$(______x_cmd_gt_get "/v5/user" )
     else
@@ -55,15 +49,18 @@ options:
 
     # TODO: wait json_awk
     local name
+    local email
     local html_url
     local types
     name="$(___x_cmd_gt_json_query "$data" .login)"
+    email="$(___x_cmd_gt_json_query "$data" .email)"
     html_url="$(___x_cmd_gt_json_query "$data" .html_url)"
     types="$(___x_cmd_gt_json_query "$data" .type)"
 #     ___json_awk_get name=.login html_url=.html_url types=.type <<A
 #     $data
 # A
-    [ -n "$name" ] && ui tf "true" "success" "name: $name" "url: $html_url" "type: $types"
+    [ -n "$name" ] && ui tf  "true" "Success" "Name: $name" "Email: $email" "Url: $html_url" "Type: $types" && return 0
+                      gt_log "err" "Can't find any data"                                                    && return 1
 }
 
 # https://gitee.com/api/v5/swagger#/getV5UserRepos
@@ -71,9 +68,9 @@ options:
 ___x_cmd_gt_user_repo() {
     param:scope     "gitee/$O"
     param:dsl       '
-type: 
+type:
     authority = all public private
-    group = owner collaborator organization_member enterprise_member admin 
+    group = owner collaborator organization_member enterprise_member admin
     sort = created updated pushed full_name
     direction = desc asc
 subcmd:
@@ -85,26 +82,23 @@ options:
     --direction     "direction"         <>:direction="desc"
 '
     param:run
-    if [ -n "$PARAM_SUBCMD" ]; then
-        ______x_cmd_gt_get_multi "/v5/users/$1/repos" visibility affiliation sort direction 
-    else
-        ______x_cmd_gt_get_multi "/v5/user/repos" visibility affiliation sort direction
+    if [ "$#" -gt 0 ]; then
+         ______x_cmd_gt_get_multi "/v5/users/$1/repos" visibility affiliation sort direction
+    else ______x_cmd_gt_get_multi "/v5/user/repos"     visibility affiliation sort direction
     fi
 }
 
 # https://gitee.com/api/v5/swagger#/getV5Emails
 ___x_cmd_gt_user_email(){
     param:void
-    [ -t 1 ] && ui table func ______x_cmd_gt_table "\"\$(O=$O ______x_cmd_gt_get_multi \"/v5/emails\")\"" \
-        . email state && return
-
-    ______x_cmd_gt_get_multi "/v5/emails"
+    [ -t 1 ] && ___ui_table_json "$(printf "%s" "______x_cmd_gt_get_multi \"/v5/emails\" || return 1" )" \
+        Email=.email State=.state && return 0
 }
 
 ___x_cmd_gt_user_issue(){
     param:scope     "gitee/$O"
     param:dsl       '
-type: 
+type:
     screen = all assigned created
     sort = open progerssing closed rejected
     direction = desc asc
@@ -122,8 +116,8 @@ options:
     --finished_at   "finish date"                                  <>=""
 '
     param:run
-    ______x_cmd_gt_get_multi "/v5/user/issues" filter state labels direction since \
-        schedule deadline created_at finished_at  
+    ___ui_table_json "$(printf "%s" "______x_cmd_gt_get_multi \"/v5/user/issues\" filter state labels direction since schedule deadline created_at finished_at  || return 1" )" \
+        id=.number State=.issue_state Type=.issue_type Title=.title Url=.html_url && return 0
 }
 
 # EndSection
@@ -135,10 +129,10 @@ ___x_cmd_gt_user_key(){
     param:scope     "gitee/$O"
     param:dsl       '
 subcmd:
-    ls        "Show information"
-    add         "List all repos"
-    get         "get one key"
-    del         "List all issues"
+    ls          "List all key"
+    add         "Add key"
+    get         "Get one key"
+    del         "Delete key"
 '
     param:run
 
@@ -162,9 +156,11 @@ options:
     --per_page    "per_page"                <>:number=20
 '
     param:run
-    ______x_cmd_gt_get "v5/user/keys" page per_page
+    ___ui_table_json "$(printf "%s" "______x_cmd_gt_get \"/v5/user/keys\" page per_page || return 1" )" \
+        Id=.id Title=.title Key=.key Url=.url && return 0
 }
 
+# shellcheck disable=SC2154
 ___x_cmd_gt_user_key_get(){
     param:scope     "gitee/$O"
     param:dsl       '
@@ -172,9 +168,15 @@ options:
     --id        "provided key id"       <>:number
 '
     param:run
-    ______x_cmd_gt_get "v5/user/keys/$id"
+    local data
+    data="$(______x_cmd_gt_get "v5/user/keys/$id")"
+    local key
+    key="$(___x_cmd_gt_json_query "$data" .key)"
+    [ -n "$key" ] && printf "%s" "$key"                     && return 0
+                     gt_log "err" "Can't find key by $id"   && return 1
 }
 
+# shellcheck disable=SC2181
 ___x_cmd_gt_user_key_del(){
     param:scope     "gitee/$O"
     param:dsl       '
@@ -182,7 +184,10 @@ options:
     --id        "provided key id"           <>:number
 '
     param:run
-    ______x_cmd_gt_delete "/v5/user/keys/$id"
+
+    ______x_cmd_gt_delete "/v5/user/keys/$id" 1>/dev/null
+    [ $? -eq 0 ] && ui tf "true" "Deleted key successfully"  && return 0
+                gt_log error "Deleting key failure by $id."  && return 1
 }
 
 ___x_cmd_gt_user_key_add(){
@@ -190,43 +195,19 @@ ___x_cmd_gt_user_key_add(){
     param:dsl       '
 options:
     --key       "add key"                   <>
-    --title     "add key name"              <>
+    --title     "add key title"             <>
 '
     param:run
-    ______x_cmd_gt_post_json "/v5/user/keys" key title
-}
-# TODO
-# ___x_cmd_gt_user_key(){
-#     param <<A
-# scope:  gitee/$O
-# type: 
-#     operate = add get delete 
-# options:
-#     #1          "operate(add,get,delete)"   <>:operate="get"
-#     --id        "key id"                    <>=""
-#     --key       "add key"                   <>=""
-#     --title     "add key name"              <>=""
-# A
-#     case "$1" in
-#         add)
-#         if [ -z "$key" ]||[ -z "$title" ];then
-#             echo "ERROR:no provided key:$key or key title:$title"
-#             return 1
-#         fi
-#            ______x_cmd_gt_post_json "/v5/user/keys" key title
-#            ;;
-#         delete)
-#         if [ -z "$id" ];then
-#             echo "ERROR:no provided keyid:$id"
-#             return 1
-#         fi
-#             ______x_cmd_gt_delete "/v5/user/keys/$id"
-#             ;;
-#         get|*)
-#             ______x_cmd_gt_get "v5/user/keys/$id"  
-#             ;;
-#     esac
-# }
 
-# EndSection
+    local data
+    data="$(______x_cmd_gt_post_json "/v5/user/keys" key title)"
+    local id
+    local title
+    local key
+    id="$(___x_cmd_gt_json_query "$data" .id)"
+    title="$(___x_cmd_gt_json_query "$data" .title)"
+    key="$(___x_cmd_gt_json_query "$data" .key)"
+    [ -n "$id" ] && ui tf  "true" "Success" "Id: $id" "title: $title" "key: $key" && return 0                       && return 0
+                    gt_log "err" "Adding user key failure."   && return 1
+}
 
