Squashed 'mod/gh/' changes from 3869a1ba..0490afe1
0490afe1 update param subcmd
3fd94069 update
3ef53d55 Merge branch 'main' of gitee.com:x-bash/gh
462900d0 update param subcmd

git-subtree-dir: mod/gh
git-subtree-split: 0490afe1a3f8519a93d4b31d15c7b929ec49a1ee

diff --git a/lib/org/member b/lib/org/member
--- a/lib/org/member
+++ b/lib/org/member
@@ -1,17 +1,16 @@
 # shellcheck shell=sh
 # shellcheck disable=SC2039,3043
 ___x_cmd_gh_org_member(){
-    param:dsl       '
-subcmd:
-    ls              "list member"
-    info            "get org member user info"
-    add             "add member"
-    rm              "Remove member"
-'
+    param:subcmd ___x_cmd_gh_org_member             \
+        ls              "list member"               \
+        info            "get org member user info"  \
+        add             "add member"                \
+        rm              "Remove member"
+    param:subcmd:try
     param:run
 
     if [ -z "$PARAM_SUBCMD" ]; then
-        echo "subcommand not found. show help." >&2
+        gh_log error "subcommand not found. show help." >&2
         return 0
     fi
 
