...

diff --git a/mod/advise/lib/man b/mod/advise/lib/man
--- a/mod/advise/lib/man
+++ b/mod/advise/lib/man
@@ -1,5 +1,4 @@
-# shellcheck disable=SC2207,SC2034,SC2012,SC1090,SC1091
-
+# shellcheck shell=bash
 ___x_cmd_advise_man(){
     local op="${1:?Provide subcommand}"; shift
     case "$op" in
@@ -24,59 +23,66 @@ ___x_cmd_advise_completions_exists(){
 
 ___x_cmd_advise_completion_update(){
     local CACHE_COMPLETIONS="$___X_CMD_ROOT/.tmp/advise/$___X_CMD_CUR_SHELL-completions.7z"
-    if ___x_cmd_httpget_gitx static-build "$___X_CMD_CUR_SHELL"-completions main "$___X_CMD_CUR_SHELL-completions.7z" "$CACHE_COMPLETIONS"; then
-        [ -d "$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/$___X_CMD_CUR_SHELL-completions" ] && rm -rf "$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/$___X_CMD_CUR_SHELL-completions" 1>/dev/null 2>&1
-        mkdir -p "$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/$___X_CMD_CUR_SHELL-completions"
-        x uz "$CACHE_COMPLETIONS" "$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/$___X_CMD_CUR_SHELL-completions" >/dev/null
-        x rmrf "$CACHE_COMPLETIONS" 1>/dev/null 2>&1
-    fi
+    local folder="$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/$___X_CMD_CUR_SHELL-completions"
+    ___x_cmd_httpget_gitx static-build "$___X_CMD_CUR_SHELL"-completions main "$___X_CMD_CUR_SHELL-completions.7z" "$CACHE_COMPLETIONS" || {
+        x:log "Fail to update $___X_CMD_CUR_SHELL-completion.7z from x-cmd/advise."
+        return 1
+    }
+
+    { x rmrf "$folder";   x mkdirp "$folder"; } 1>/dev/null 2>&1
+    x uz "$CACHE_COMPLETIONS" "$folder"
+    x rmrf "$CACHE_COMPLETIONS"
 }
 
 ___x_cmd_advise_man_update(){
     local CACHE="$___X_CMD_ROOT/.tmp/advise/all.tgz"
-    if ___x_cmd_httpget_gitx x-cmd advise main "dist/all.tgz" "$CACHE" -; then
-        [ -d "$___X_CMD_ADVISE_MAN_SRC_FOLDER" ] && rm -rf "$___X_CMD_ADVISE_MAN_SRC_FOLDER"
-        mkdir -p "$___X_CMD_ADVISE_MAN_SRC_FOLDER"
-        x uz "$CACHE" "$___X_CMD_ADVISE_MAN_SRC_FOLDER" >/dev/null
-        x rmrf "$CACHE" 1>/dev/null 2>&1
-    fi
+    ___x_cmd_httpget_gitx x-cmd advise main "dist/all.tgz" "$CACHE" - || {
+        x:log "Fail to update from x-cmd/advise."
+        return 1
+    }
+
+    { x rmrf "$___X_CMD_ADVISE_MAN_SRC_FOLDER";   x mkdirp "$___X_CMD_ADVISE_MAN_SRC_FOLDER"; }1>/dev/null 2>&1
+    x uz "$CACHE" "$___X_CMD_ADVISE_MAN_SRC_FOLDER"
+    x rmrf "$CACHE"
 }
 
 ___x_cmd_advise_man_ls(){
-    if ___x_cmd_advise_man_exists || ___x_cmd_advise_man_update; then
-        local line
-        ls "$___X_CMD_ADVISE_MAN_SRC_FOLDER/$*" | while read -r line; do
-            [ "$line" = "LICENSE" ] || printf "%s\n" "$line"
-        done
-    fi
+    ___x_cmd_advise_man_exists || ___x_cmd_advise_man_update || return
+    local line
+    ls "$___X_CMD_ADVISE_MAN_SRC_FOLDER/$*" | while read -r line; do
+        [ "$line" = "LICENSE" ] || printf "%s\n" "$line"
+    done
 }
 
 ___x_cmd_advise_man_which(){
     local name="${1:?Provide name}"
-    local file
-    if ___x_cmd_advise_man_exists || ___x_cmd_advise_man_update; then
-        [ -f "$file" ] || file="$___X_CMD_ADVISE_MAN_SRC_FOLDER/$name/advise.t.json"
-        [ -f "$file" ] || file="$___X_CMD_ADVISE_MAN_SRC_FOLDER/npx/_/$name/advise.t.json"
-        [ -f "$file" ] || file="$___X_CMD_ADVISE_MAN_SRC_FOLDER/pipx/_/$name/advise.t.json"
-        [ -f "$file" ] || return 1
+
+    ___x_cmd_advise_man_exists || ___x_cmd_advise_man_update || return
+
+    local IFS=" ";
+    local file; for file in "$name/advise.t.json" "npx/_/$name/advise.t.json" "pipx/_/$name/advise.t.json"; do
+        file="$___X_CMD_ADVISE_MAN_SRC_FOLDER/$file"
+        [ -f "$file" ] || continue
         printf "%s\n" "$file"
+    done
+}
+
+___x_cmd_advise_man_load_one(){
+    if [ -n "$ZSH_VERSION" ];then                                   compdef "___x_cmd_advise_man_completer" "$@"
+    elif [[ "$BASH_VERSION" =~ (^3.*|^4.[0-3]) ]]; then             complete -F "___x_cmd_advise_man_completer" "$@"
+    else                                                            complete -o nosort -F "___x_cmd_advise_man_completer" "$@"
     fi
 }
 
+___x_cmd_advise_man_load_all(){
+    eval "$(___x_cmd_advise_man_ls | command awk '
+        {                           code = code " " $1;                                         }
+        (NR % 50 == 0){             print "___x_cmd_advise_man_load_one" code;      code = ""   }
+        END {   if (code != "")     print "___x_cmd_advise_man_load_one" code;                  }
+    ')"
+}
+
 ___x_cmd_advise_man_load(){
-
-    if [[ ! "${1:-""}" == "" ]]; then
-        if [ -z "$ZSH_VERSION" ];then
-            if [[ ! "$BASH_VERSION" =~ (^3.*|^4.[0-3]) ]]; then
-                complete -o nosort -F "___x_cmd_advise_man_completer" "$1" && return 1
-            else
-                complete -F "___x_cmd_advise_man_completer" "$1" && return 1
-            fi
-        else
-            compdef "___x_cmd_advise_man_completer" "$1" && return 1
-        fi
-    fi
-
     if ___x_cmd_advise_completions_exists || ___x_cmd_advise_completion_update; then
         local filename="$___X_CMD_ADVISE_MAN_COMPLETIONS_FOLDER/$___X_CMD_CUR_SHELL-completions/completions.sh"
         if [ -f "$filename" ]; then
@@ -84,20 +90,10 @@ ___x_cmd_advise_man_load(){
             .  "$filename"
         fi
     fi
-    local i; for i in $(___x_cmd_advise_man_ls); do
-        if [ -z "$ZSH_VERSION" ];then
-            [[ ! $(complete -p "$i" 2>/dev/null) == *___x_cmd_advise_man_completer* ]] || continue
 
-            if [[ ! "$BASH_VERSION" =~ (^3.*|^4.[0-3]) ]]; then
-                complete -o nosort -F "___x_cmd_advise_man_completer" "$i"
-            else
-                complete -F "___x_cmd_advise_man_completer" "$i"
-            fi
-
-        else
-            compdef "___x_cmd_advise_man_completer" "$i"
-        fi
-    done
+    if [ "$#" -ge 1 ]; then     ___x_cmd_advise_man_load_one "$@"
+    else                        ___x_cmd_advise_man_load_all
+    fi
 }
 
 ___x_cmd_advise_man_rm(){
@@ -113,13 +109,6 @@ ___x_cmd_advise_man_completer() {
     ___ADVISE_RUN_CMD_FOLDER="$___X_CMD_ADVISE_MAN_SRC_FOLDER" ___advise_run ""
 }
 
-
 ## Section man advise
-___x_cmd_advise_man__list(){
-    if [ -n "$1" ]; then
-        candidate_exec_arr=( $(___x_cmd_advise_man_ls "$1"/_ ))
-    else
-        candidate_exec_arr=( $(___x_cmd_advise_man_ls ) )
-    fi
-}
+___x_cmd_advise_man__list(){            candidate_exec_arr=( $(___x_cmd_advise_man_ls ${1:+"$1"/_} ) );      }
 ## EndSection
